"""Executable improve1 capability registry for this PBC.

This module turns the package-local improve1 backlog into code-level evidence.
It is intentionally side-effect free: callers can inspect capability coverage, plan
execution, and verify surface mappings without touching external systems.
"""

from __future__ import annotations

from dataclasses import dataclass

PBC_KEY = 'api_gateway_mesh'


@dataclass(frozen=True)
class Improve1Capability:
    feature_number: int
    title: str
    slug: str
    domain_tags: tuple[str, ...]
    model_artifacts: tuple[str, ...]
    ui_artifacts: tuple[str, ...]
    service_artifacts: tuple[str, ...]
    test_artifacts: tuple[str, ...]
    evidence_artifacts: tuple[str, ...]
    configurable: bool = True
    agent_assisted: bool = True
    side_effect_free_plan: bool = True

    def as_traceability_row(self) -> dict:
        return {
            "feature_number": self.feature_number,
            "title": self.title,
            "slug": self.slug,
            "domain_tags": self.domain_tags,
            "code_artifact_model": self.model_artifacts,
            "ui_surface": self.ui_artifacts,
            "service_api": self.service_artifacts,
            "test": self.test_artifacts,
            "evidence": self.evidence_artifacts,
            "configurable": self.configurable,
            "agent_assisted": self.agent_assisted,
            "side_effect_free_plan": self.side_effect_free_plan,
        }



IMPROVE1_CAPABILITIES: tuple[Improve1Capability, ...] = (
    Improve1Capability(
        feature_number=1,
        title='Route publication safety case',
        slug='route_publication_safety_case',
        domain_tags=('case', 'safety'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=2,
        title='Host, path, and method collision analysis',
        slug='host_path_and_method_collision_analysis',
        domain_tags=('method', 'collision', 'analysis'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=3,
        title='Consumer-facing API product lifecycle',
        slug='consumer_facing_api_product_lifecycle',
        domain_tags=('consumer_facing', 'product', 'lifecycle'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=4,
        title='Backward-compatibility gate for route versions',
        slug='backward_compatibility_gate_for_route_versions',
        domain_tags=('backward_compatibility', 'route', 'versions'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=5,
        title='Tenant-aware route namespace governance',
        slug='tenant_aware_route_namespace_governance',
        domain_tags=('governance',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=6,
        title='Workload identity binding ceremony',
        slug='workload_identity_binding_ceremony',
        domain_tags=('identity',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=7,
        title='Certificate rotation simulation',
        slug='certificate_rotation_simulation',
        domain_tags=('certificate', 'rotation', 'simulation'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=8,
        title='Dynamic authorization decision trace',
        slug='dynamic_authorization_decision_trace',
        domain_tags=('dynamic', 'authorization', 'decision'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=9,
        title='Fine-grained rate-limit hierarchy',
        slug='fine_grained_rate_limit_hierarchy',
        domain_tags=('fine_grained', 'rate_limit', 'hierarchy'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=10,
        title='Quota marketplace and entitlement integration',
        slug='quota_marketplace_and_entitlement_integration',
        domain_tags=('market',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=11,
        title='Adaptive throttling with deterministic guardrails',
        slug='adaptive_throttling_with_deterministic_guardrails',
        domain_tags=('adaptive', 'throttling', 'deterministic'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=12,
        title='Backpressure propagation map',
        slug='backpressure_propagation_map',
        domain_tags=('backpressure', 'propagation'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=13,
        title='Circuit-breaker state machine audit',
        slug='circuit_breaker_state_machine_audit',
        domain_tags=('audit',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=14,
        title='Fallback-route correctness verification',
        slug='fallback_route_correctness_verification',
        domain_tags=('fallback_route', 'correctness', 'verification'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=15,
        title='Retry-budget economics',
        slug='retry_budget_economics',
        domain_tags=('retry_budget', 'economics'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=16,
        title='Idempotency contract registry',
        slug='idempotency_contract_registry',
        domain_tags=('contract', 'registry'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=17,
        title='Request and response redaction policy',
        slug='request_and_response_redaction_policy',
        domain_tags=('policy',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=18,
        title='Schema-aware payload validation at the edge',
        slug='schema_aware_payload_validation_at_the_edge',
        domain_tags=('schema_aware', 'payload', 'validation'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=19,
        title='Error-envelope normalization',
        slug='error_envelope_normalization',
        domain_tags=('error_envelope', 'normalization'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=20,
        title='Correlation and causality propagation',
        slug='correlation_and_causality_propagation',
        domain_tags=('correlation', 'causality', 'propagation'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=21,
        title='Service topology drift detection',
        slug='service_topology_drift_detection',
        domain_tags=('service',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=22,
        title='Route ownership and support accountability',
        slug='route_ownership_and_support_accountability',
        domain_tags=('route', 'ownership', 'support'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=23,
        title='Progressive delivery controller',
        slug='progressive_delivery_controller',
        domain_tags=('progressive', 'delivery', 'controller'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=24,
        title='Consumer cohort routing',
        slug='consumer_cohort_routing',
        domain_tags=('routing',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=25,
        title='Synthetic transaction probes',
        slug='synthetic_transaction_probes',
        domain_tags=('synthetic', 'transaction', 'probes'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=26,
        title='Multi-region ingress posture',
        slug='multi_region_ingress_posture',
        domain_tags=('multi_region', 'ingress', 'posture'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=27,
        title='Residency and sovereignty-aware routing',
        slug='residency_and_sovereignty_aware_routing',
        domain_tags=('routing',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=28,
        title='Gateway configuration blast-radius analysis',
        slug='gateway_configuration_blast_radius_analysis',
        domain_tags=('configuration',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=29,
        title='Rule compiler with test fixtures',
        slug='rule_compiler_with_test_fixtures',
        domain_tags=('compiler', 'fixtures'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=30,
        title='Policy-as-of temporal replay',
        slug='policy_as_of_temporal_replay',
        domain_tags=('policy',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=31,
        title='Abuse-pattern detection for API traffic',
        slug='abuse_pattern_detection_for_api_traffic',
        domain_tags=('abuse_pattern', 'detection', 'traffic'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=32,
        title='Bot, scraper, and automation governance',
        slug='bot_scraper_and_automation_governance',
        domain_tags=('governance',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=33,
        title='Service contract certification workflow',
        slug='service_contract_certification_workflow',
        domain_tags=('contract', 'service', 'workflow'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=34,
        title='Developer self-service onboarding',
        slug='developer_self_service_onboarding',
        domain_tags=('service',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=35,
        title='Contract documentation generation',
        slug='contract_documentation_generation',
        domain_tags=('contract', 'document'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=36,
        title='SLO burn-rate governance',
        slug='slo_burn_rate_governance',
        domain_tags=('governance',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=37,
        title='Maintenance-window routing controls',
        slug='maintenance_window_routing_controls',
        domain_tags=('routing',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=38,
        title='Emergency kill switch governance',
        slug='emergency_kill_switch_governance',
        domain_tags=('governance',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=39,
        title='Partner and external consumer onboarding',
        slug='partner_and_external_consumer_onboarding',
        domain_tags=('partner', 'external', 'consumer'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=40,
        title='Sandbox-to-production promotion',
        slug='sandbox_to_production_promotion',
        domain_tags=('sandbox_to_production', 'promotion'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=41,
        title='Agent-assisted incident triage',
        slug='agent_assisted_incident_triage',
        domain_tags=('agent',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=42,
        title='Agent-safe route change authoring',
        slug='agent_safe_route_change_authoring',
        domain_tags=('agent',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=43,
        title='Request document ingestion',
        slug='request_document_ingestion',
        domain_tags=('document',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=44,
        title='Dead-letter replay workbench',
        slug='dead_letter_replay_workbench',
        domain_tags=('dead_letter', 'replay', 'workbench'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=45,
        title='Projection freshness and dependency health',
        slug='projection_freshness_and_dependency_health',
        domain_tags=('project',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=46,
        title='Release audit for gateway-specific completeness',
        slug='release_audit_for_gateway_specific_completeness',
        domain_tags=('audit',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=47,
        title='UI surface for every operational capability',
        slug='ui_surface_for_every_operational_capability',
        domain_tags=('surface', 'every', 'operational'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=48,
        title='Boundary proof for no shared operational tables',
        slug='boundary_proof_for_no_shared_operational_tables',
        domain_tags=('boundary', 'proof', 'shared'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=49,
        title='Deterministic route optimizer',
        slug='deterministic_route_optimizer',
        domain_tags=('deterministic', 'route', 'optimizer'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=50,
        title='Gateway competency catalog for composed agents',
        slug='gateway_competency_catalog_for_composed_agents',
        domain_tags=('agent',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_workbench_forms_wizards_controls.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
)



def capability_registry() -> dict:
    """Return side-effect-free registry metadata for improve1 capabilities."""
    rows = tuple(capability.as_traceability_row() for capability in IMPROVE1_CAPABILITIES)
    return {
        "ok": len(rows) == 50 and all(row["code_artifact_model"] and row["ui_surface"] and row["service_api"] and row["test"] and row["evidence"] for row in rows),
        "pbc": PBC_KEY,
        "capability_count": len(rows),
        "capabilities": rows,
        "side_effects": (),
    }


def plan_feature_execution(feature_number: int) -> dict:
    """Plan how a feature is exercised without mutating package state."""
    match = next((capability for capability in IMPROVE1_CAPABILITIES if capability.feature_number == feature_number), None)
    if match is None:
        return {"ok": False, "pbc": PBC_KEY, "reason": "unknown_feature", "side_effects": ()}
    return {
        "ok": True,
        "pbc": PBC_KEY,
        "feature_number": match.feature_number,
        "title": match.title,
        "slug": match.slug,
        "domain_tags": match.domain_tags,
        "model_artifacts": match.model_artifacts,
        "ui_artifacts": match.ui_artifacts,
        "service_artifacts": match.service_artifacts,
        "test_artifacts": match.test_artifacts,
        "evidence_artifacts": match.evidence_artifacts,
        "requires_configuration": match.configurable,
        "agent_assisted": match.agent_assisted,
        "side_effects": (),
    }


def validate_improve1_capabilities(expected_titles: tuple[str, ...]) -> dict:
    """Validate registry alignment with parsed improve1 titles."""
    actual_titles = tuple(capability.title for capability in IMPROVE1_CAPABILITIES)
    registry = capability_registry()
    return {
        "ok": len(actual_titles) == 50 and actual_titles == expected_titles and registry["ok"],
        "pbc": PBC_KEY,
        "expected_count": len(expected_titles),
        "actual_count": len(actual_titles),
        "titles_match": actual_titles == expected_titles,
        "registry_ok": registry["ok"],
        "side_effects": (),
    }
