"""Package manifest for the humanitarian_relief_operations PBC."""

PBC_MANIFEST = {'advanced_capabilities': ('humanitarian_relief_operations_event_sourced_operational_history',
                           'humanitarian_relief_operations_multi_tenant_policy_isolation',
                           'humanitarian_relief_operations_schema_evolution_resilience',
                           'humanitarian_relief_operations_autonomous_anomaly_detection',
                           'humanitarian_relief_operations_semantic_document_instruction_understanding',
                           'humanitarian_relief_operations_predictive_risk_scoring',
                           'humanitarian_relief_operations_counterfactual_scenario_simulation',
                           'humanitarian_relief_operations_cryptographic_audit_proofs',
                           'humanitarian_relief_operations_continuous_control_testing',
                           'humanitarian_relief_operations_carbon_and_sustainability_awareness',
                           'humanitarian_relief_operations_cross_pbc_event_federation',
                           'humanitarian_relief_operations_governed_ai_agent_execution'),
 'analytics': ('humanitarian_relief_operations_risk_score',
               'humanitarian_relief_operations_workbench_metric'),
 'apis': ('POST /needs-assessments',
          'POST /aid-items',
          'POST /distribution-events',
          'POST /field-partners',
          'POST /protection-cases',
          'GET /humanitarian-relief-operations-workbench'),
 'capabilities': ('needs_assessment_management',
                  'humanitarian_relief_operations_workflow',
                  'humanitarian_relief_operations_analytics',
                  'configuration_schema',
                  'rule_engine',
                  'parameter_engine',
                  'owned_schema_migrations_models',
                  'appgen_x_outbox_inbox_eventing',
                  'idempotent_handlers',
                  'retry_dead_letter_evidence',
                  'permissions',
                  'seed_data',
                  'workbench',
                  'agentic_document_instruction_intake',
                  'governed_datastore_crud',
                  'ai_agent_task_assistance',
                  'configuration_workbench',
                  'continuous_release_assurance',
                  'humanitarian_relief_operations_event_sourced_operational_history',
                  'humanitarian_relief_operations_multi_tenant_policy_isolation',
                  'humanitarian_relief_operations_schema_evolution_resilience',
                  'humanitarian_relief_operations_autonomous_anomaly_detection',
                  'humanitarian_relief_operations_semantic_document_instruction_understanding',
                  'humanitarian_relief_operations_predictive_risk_scoring',
                  'humanitarian_relief_operations_counterfactual_scenario_simulation',
                  'humanitarian_relief_operations_cryptographic_audit_proofs',
                  'humanitarian_relief_operations_continuous_control_testing',
                  'humanitarian_relief_operations_carbon_and_sustainability_awareness',
                  'humanitarian_relief_operations_cross_pbc_event_federation',
                  'humanitarian_relief_operations_governed_ai_agent_execution'),
 'configuration': ('HUMANITARIAN_RELIEF_OPERATIONS_DATABASE_URL',
                   'HUMANITARIAN_RELIEF_OPERATIONS_EVENT_TOPIC',
                   'HUMANITARIAN_RELIEF_OPERATIONS_RETRY_LIMIT',
                   'HUMANITARIAN_RELIEF_OPERATIONS_DEFAULT_POLICY'),
 'consumes': ('PolicyChanged', 'AuditEventSealed', 'OperationalKpiChanged'),
 'datastore_backend': 'postgresql',
 'description': 'Needs assessment, aid distribution, logistics, protection, field partners, donor '
                'reporting, and relief accountability',
 'docs': ('SPECIFICATION.md', 'RELEASE_EVIDENCE.md'),
 'emits': ('HumanitarianReliefOperationsCreated',
           'HumanitarianReliefOperationsUpdated',
           'HumanitarianReliefOperationsApproved',
           'HumanitarianReliefOperationsExceptionOpened'),
 'label': 'Humanitarian Relief Operations',
 'mesh': 'scl',
 'migrations': ('migrations/001_initial.sql',),
 'pbc': 'humanitarian_relief_operations',
 'permissions': ('humanitarian_relief_operations.read',
                 'humanitarian_relief_operations.create',
                 'humanitarian_relief_operations.update',
                 'humanitarian_relief_operations.approve',
                 'humanitarian_relief_operations.admin'),
 'seed_data': ('seed_data.py',),
 'standard_features': ('needs_assessment_management',
                       'humanitarian_relief_operations_workflow',
                       'humanitarian_relief_operations_analytics',
                       'configuration_schema',
                       'rule_engine',
                       'parameter_engine',
                       'owned_schema_migrations_models',
                       'appgen_x_outbox_inbox_eventing',
                       'idempotent_handlers',
                       'retry_dead_letter_evidence',
                       'permissions',
                       'seed_data',
                       'workbench',
                       'agentic_document_instruction_intake',
                       'governed_datastore_crud',
                       'ai_agent_task_assistance',
                       'configuration_workbench',
                       'continuous_release_assurance'),
 'tables': ('needs_assessment',
            'aid_item',
            'distribution_event',
            'field_partner',
            'protection_case',
            'relief_shipment',
            'donor_accountability',
            'humanitarian_relief_operations_policy_rule',
            'humanitarian_relief_operations_runtime_parameter',
            'humanitarian_relief_operations_schema_extension',
            'humanitarian_relief_operations_control_assertion',
            'humanitarian_relief_operations_governed_model'),
 'template': 'logistics',
 'tests': ('tests/test_contract.py',),
 'ui_fragments': ('HumanitarianReliefOperationsWorkbench',
                  'HumanitarianReliefOperationsDetail',
                  'HumanitarianReliefOperationsAssistantPanel'),
 'version': '1.0.0',
 'workflows': ('humanitarian_relief_operations_create_needs_assessment_workflow',
               'humanitarian_relief_operations_record_aid_item_workflow')}
