"""Executable improve1 capability registry for this PBC.

This module turns the package-local improve1 backlog into code-level evidence.
It is intentionally side-effect free: callers can inspect capability coverage, plan
execution, and verify surface mappings without touching external systems.
"""

from __future__ import annotations

from dataclasses import dataclass

PBC_KEY = 'facility_energy_management'


@dataclass(frozen=True)
class Improve1Capability:
    feature_number: int
    title: str
    slug: str
    domain_tags: tuple[str, ...]
    model_artifacts: tuple[str, ...]
    ui_artifacts: tuple[str, ...]
    service_artifacts: tuple[str, ...]
    test_artifacts: tuple[str, ...]
    evidence_artifacts: tuple[str, ...]
    configurable: bool = True
    agent_assisted: bool = True
    side_effect_free_plan: bool = True

    def as_traceability_row(self) -> dict:
        return {
            "feature_number": self.feature_number,
            "title": self.title,
            "slug": self.slug,
            "domain_tags": self.domain_tags,
            "code_artifact_model": self.model_artifacts,
            "ui_surface": self.ui_artifacts,
            "service_api": self.service_artifacts,
            "test": self.test_artifacts,
            "evidence": self.evidence_artifacts,
            "configurable": self.configurable,
            "agent_assisted": self.agent_assisted,
            "side_effect_free_plan": self.side_effect_free_plan,
        }



IMPROVE1_CAPABILITIES: tuple[Improve1Capability, ...] = (
    Improve1Capability(
        feature_number=1,
        title='Meter and Submeter Topology in `energy_meter`',
        slug='meter_and_submeter_topology_in_energy_meter',
        domain_tags=('meter', 'submeter', 'topology'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=2,
        title='Interval Read Fidelity in `load_profile`',
        slug='interval_read_fidelity_in_load_profile',
        domain_tags=('interval', 'fidelity', 'load_profile'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=3,
        title='Commissioning and Health Evidence for `energy_meter`',
        slug='commissioning_and_health_evidence_for_energy_meter',
        domain_tags=('commissioning', 'health', 'evidence'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=4,
        title='Utility Account and Service Point Mapping in `energy_meter`',
        slug='utility_account_and_service_point_mapping_in_energy_meter',
        domain_tags=('service',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=5,
        title='Estimated Read Provenance and Correction Workflow in `load_profile`',
        slug='estimated_read_provenance_and_correction_workflow_in_load_profile',
        domain_tags=('workflow',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=6,
        title='Seasonal and Time-of-Use Tariff Calendars in `tariff_signal`',
        slug='seasonal_and_time_of_use_tariff_calendars_in_tariff_signal',
        domain_tags=('seasonal', 'time_of_use', 'tariff'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=7,
        title='Demand Charge and Ratchet Determinants in `tariff_signal`',
        slug='demand_charge_and_ratchet_determinants_in_tariff_signal',
        domain_tags=('demand', 'charge', 'ratchet'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=8,
        title='Tariff Scenario Comparison in `energy_optimization`',
        slug='tariff_scenario_comparison_in_energy_optimization',
        domain_tags=('tariff', 'scenario', 'comparison'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=9,
        title='HVAC Schedule Hierarchy in `equipment_schedule`',
        slug='hvac_schedule_hierarchy_in_equipment_schedule',
        domain_tags=('schedule',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=10,
        title='Occupancy, Weather, and Holiday Overrides in `equipment_schedule`',
        slug='occupancy_weather_and_holiday_overrides_in_equipment_schedule',
        domain_tags=('schedule',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=11,
        title='Schedule Conflict Detection and Lock Windows in `equipment_schedule`',
        slug='schedule_conflict_detection_and_lock_windows_in_equipment_schedule',
        domain_tags=('schedule',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=12,
        title='Controls Command Boundary for `energy_optimization`',
        slug='controls_command_boundary_for_energy_optimization',
        domain_tags=('controls', 'command', 'boundary'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=13,
        title='Manual Override Governance in `facility_energy_management_policy_rule`',
        slug='manual_override_governance_in_facility_energy_management_policy_rule',
        domain_tags=('governance', 'policy'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=14,
        title='Critical Load, Generator, and UPS Awareness in `load_profile`',
        slug='critical_load_generator_and_ups_awareness_in_load_profile',
        domain_tags=('critical', 'generator', 'awareness'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=15,
        title='Baseline Versioning in `energy_baseline`',
        slug='baseline_versioning_in_energy_baseline',
        domain_tags=('baseline', 'versioning', 'energy_baseline'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=16,
        title='Weather-Normalized Performance in `energy_baseline`',
        slug='weather_normalized_performance_in_energy_baseline',
        domain_tags=('weather_normalized', 'performance', 'energy_baseline'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=17,
        title='Baseload, After-Hours, and Drift Anomalies in `facility_energy_management_autonomous_anomaly_detection`',
        slug='baseload_after_hours_and_drift_anomalies_in_facility_energy_management_autonomous_anomaly_detection',
        domain_tags=('baseload', 'after_hours', 'drift'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=18,
        title='Investigation Case Packs for `FacilityEnergyManagementExceptionOpened`',
        slug='investigation_case_packs_for_facilityenergymanagementexceptionopened',
        domain_tags=('case',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=19,
        title='HVAC Fault Detection and Diagnostics in `facility_energy_management_workbench_metric`',
        slug='hvac_fault_detection_and_diagnostics_in_facility_energy_management_workbench_metric',
        domain_tags=('fault', 'detection', 'diagnostics'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=20,
        title='Peak Demand Forecasting in `facility_energy_management_risk_score`',
        slug='peak_demand_forecasting_in_facility_energy_management_risk_score',
        domain_tags=('forecast', 'risk'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=21,
        title='Demand Response Asset Eligibility in `demand_response_event`',
        slug='demand_response_asset_eligibility_in_demand_response_event',
        domain_tags=('asset', 'event'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=22,
        title='Demand Response Dispatch Orchestration in `demand_response_event`',
        slug='demand_response_dispatch_orchestration_in_demand_response_event',
        domain_tags=('dispatch', 'event', 'orchestration'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=23,
        title='Curtailment Measurement and Settlement in `demand_response_event`',
        slug='curtailment_measurement_and_settlement_in_demand_response_event',
        domain_tags=('event', 'settlement'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=24,
        title='Comfort and Safety Guardrails in `facility_energy_management_control_assertion`',
        slug='comfort_and_safety_guardrails_in_facility_energy_management_control_assertion',
        domain_tags=('safety',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=25,
        title='Post-Event Rebound Management in `demand_response_event`',
        slug='post_event_rebound_management_in_demand_response_event',
        domain_tags=('event',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=26,
        title='Carbon Factor Registry in `facility_energy_management_carbon_and_sustainability_awareness`',
        slug='carbon_factor_registry_in_facility_energy_management_carbon_and_sustainability_awareness',
        domain_tags=('registry',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=27,
        title='Carbon and Cost Co-Optimization in `energy_optimization`',
        slug='carbon_and_cost_co_optimization_in_energy_optimization',
        domain_tags=('carbon', 'co_optimization', 'energy_optimization'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=28,
        title='Tenant Allocation Rules in `energy_meter`',
        slug='tenant_allocation_rules_in_energy_meter',
        domain_tags=('tenant', 'allocation', 'rules'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=29,
        title='Common-Area Reconciliation in `load_profile`',
        slug='common_area_reconciliation_in_load_profile',
        domain_tags=('reconciliation',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=30,
        title='Retrofit Opportunity Register in `energy_optimization`',
        slug='retrofit_opportunity_register_in_energy_optimization',
        domain_tags=('retrofit', 'opportunity', 'register'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=31,
        title='Savings Persistence Tracking in `energy_baseline`',
        slug='savings_persistence_tracking_in_energy_baseline',
        domain_tags=('savings', 'persistence', 'tracking'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=32,
        title='Retrofit Prioritization Scenarios in `facility_energy_management_counterfactual_scenario_simulation`',
        slug='retrofit_prioritization_scenarios_in_facility_energy_management_counterfactual_scenario_simulation',
        domain_tags=('retrofit', 'prioritization', 'scenarios'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=33,
        title='Tariff and O&M Document Intake in `agentic_document_instruction_intake`',
        slug='tariff_and_o_m_document_intake_in_agentic_document_instruction_intake',
        domain_tags=('agent', 'document'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=34,
        title='Anomaly Triage Skill in `ai_agent_task_assistance`',
        slug='anomaly_triage_skill_in_ai_agent_task_assistance',
        domain_tags=('agent',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=35,
        title='Tenant Allocation Explanation Skill in `FacilityEnergyManagementAssistantPanel`',
        slug='tenant_allocation_explanation_skill_in_facilityenergymanagementassistantpanel',
        domain_tags=('tenant', 'allocation', 'explanation'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=36,
        title='Operator Queue in `FacilityEnergyManagementWorkbench`',
        slug='operator_queue_in_facilityenergymanagementworkbench',
        domain_tags=('operator', 'queue', 'facilityenergymanagementworkbench'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=37,
        title='Sustainability and Carbon Detail View in `FacilityEnergyManagementDetail`',
        slug='sustainability_and_carbon_detail_view_in_facilityenergymanagementdetail',
        domain_tags=('sustainability', 'carbon', 'detail'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=38,
        title='Controls Engineer Tuning Workspace in `configuration_workbench`',
        slug='controls_engineer_tuning_workspace_in_configuration_workbench',
        domain_tags=('configuration',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=39,
        title='Tenant Services Allocation View in `FacilityEnergyManagementWorkbench`',
        slug='tenant_services_allocation_view_in_facilityenergymanagementworkbench',
        domain_tags=('service',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=40,
        title='Command and Query API Coverage Beyond `POST /energy-meters`',
        slug='command_and_query_api_coverage_beyond_post_energy_meters',
        domain_tags=('command', 'query', 'coverage'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=41,
        title='Event Boundary Expansion Beyond `FacilityEnergyManagementCreated`',
        slug='event_boundary_expansion_beyond_facilityenergymanagementcreated',
        domain_tags=('event',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=42,
        title='Replay-Safe Inbox and Outbox Evidence in `appgen_x_outbox_inbox_eventing`',
        slug='replay_safe_inbox_and_outbox_evidence_in_appgen_x_outbox_inbox_eventing',
        domain_tags=('event',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=43,
        title='Policy-Driven Tenant Isolation in `facility_energy_management_multi_tenant_policy_isolation`',
        slug='policy_driven_tenant_isolation_in_facility_energy_management_multi_tenant_policy_isolation',
        domain_tags=('policy',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=44,
        title='Runtime Parameter Governance in `facility_energy_management_runtime_parameter`',
        slug='runtime_parameter_governance_in_facility_energy_management_runtime_parameter',
        domain_tags=('governance',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=45,
        title='Continuous Control Testing in `facility_energy_management_continuous_control_testing`',
        slug='continuous_control_testing_in_facility_energy_management_continuous_control_testing',
        domain_tags=('continuous', 'control', 'testing'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=46,
        title='Schema Extension Registry in `facility_energy_management_schema_extension`',
        slug='schema_extension_registry_in_facility_energy_management_schema_extension',
        domain_tags=('registry',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=47,
        title='Governed Model Lifecycle in `facility_energy_management_governed_model`',
        slug='governed_model_lifecycle_in_facility_energy_management_governed_model',
        domain_tags=('model',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=48,
        title='Consumed-Event Freshness for `PolicyChanged`, `AuditEventSealed`, and `OperationalKpiChanged`',
        slug='consumed_event_freshness_for_policychanged_auditeventsealed_and_operationalkpichanged',
        domain_tags=('audit', 'event', 'policy'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=49,
        title='Regression Narratives in `seed_data.py` and `tests/test_contract.py`',
        slug='regression_narratives_in_seed_data_py_and_tests_test_contract_py',
        domain_tags=('contract',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=50,
        title='End-to-End Release Drill in `RELEASE_EVIDENCE.md`',
        slug='end_to_end_release_drill_in_release_evidence_md',
        domain_tags=('end_to_end', 'release', 'drill'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
)



def capability_registry() -> dict:
    """Return side-effect-free registry metadata for improve1 capabilities."""
    rows = tuple(capability.as_traceability_row() for capability in IMPROVE1_CAPABILITIES)
    return {
        "ok": len(rows) == 50 and all(row["code_artifact_model"] and row["ui_surface"] and row["service_api"] and row["test"] and row["evidence"] for row in rows),
        "pbc": PBC_KEY,
        "capability_count": len(rows),
        "capabilities": rows,
        "side_effects": (),
    }


def plan_feature_execution(feature_number: int) -> dict:
    """Plan how a feature is exercised without mutating package state."""
    match = next((capability for capability in IMPROVE1_CAPABILITIES if capability.feature_number == feature_number), None)
    if match is None:
        return {"ok": False, "pbc": PBC_KEY, "reason": "unknown_feature", "side_effects": ()}
    return {
        "ok": True,
        "pbc": PBC_KEY,
        "feature_number": match.feature_number,
        "title": match.title,
        "slug": match.slug,
        "domain_tags": match.domain_tags,
        "model_artifacts": match.model_artifacts,
        "ui_artifacts": match.ui_artifacts,
        "service_artifacts": match.service_artifacts,
        "test_artifacts": match.test_artifacts,
        "evidence_artifacts": match.evidence_artifacts,
        "requires_configuration": match.configurable,
        "agent_assisted": match.agent_assisted,
        "side_effects": (),
    }


def validate_improve1_capabilities(expected_titles: tuple[str, ...]) -> dict:
    """Validate registry alignment with parsed improve1 titles."""
    actual_titles = tuple(capability.title for capability in IMPROVE1_CAPABILITIES)
    registry = capability_registry()
    return {
        "ok": len(actual_titles) == 50 and actual_titles == expected_titles and registry["ok"],
        "pbc": PBC_KEY,
        "expected_count": len(expected_titles),
        "actual_count": len(actual_titles),
        "titles_match": actual_titles == expected_titles,
        "registry_ok": registry["ok"],
        "side_effects": (),
    }
