"""Generated owned schema evidence for the sustainability_esg_reporting PBC."""

SCHEMA_CONTRACT = {'format': 'appgen.sustainability-esg-reporting-owned-schema-contract.v1',
 'ok': True,
 'tables': ({'logical_table': 'emissions_factor',
             'owned_table': 'sustainability_esg_reporting_emissions_factor',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'activity_data',
             'owned_table': 'sustainability_esg_reporting_activity_data',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'emissions_factor_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'sustainability_esg_reporting_emissions_factor.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'emissions_factor_id',
                                'target_table': 'sustainability_esg_reporting_emissions_factor',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'carbon_ledger_entry',
             'owned_table': 'sustainability_esg_reporting_carbon_ledger_entry',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'emissions_factor_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'sustainability_esg_reporting_emissions_factor.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'emissions_factor_id',
                                'target_table': 'sustainability_esg_reporting_emissions_factor',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'esg_metric',
             'owned_table': 'sustainability_esg_reporting_esg_metric',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'emissions_factor_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'sustainability_esg_reporting_emissions_factor.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'emissions_factor_id',
                                'target_table': 'sustainability_esg_reporting_emissions_factor',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'supplier_disclosure',
             'owned_table': 'sustainability_esg_reporting_supplier_disclosure',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'emissions_factor_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'sustainability_esg_reporting_emissions_factor.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'emissions_factor_id',
                                'target_table': 'sustainability_esg_reporting_emissions_factor',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'assurance_evidence',
             'owned_table': 'sustainability_esg_reporting_assurance_evidence',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'emissions_factor_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'sustainability_esg_reporting_emissions_factor.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'emissions_factor_id',
                                'target_table': 'sustainability_esg_reporting_emissions_factor',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'sustainability_report',
             'owned_table': 'sustainability_esg_reporting_sustainability_report',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'emissions_factor_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'sustainability_esg_reporting_emissions_factor.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'emissions_factor_id',
                                'target_table': 'sustainability_esg_reporting_emissions_factor',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'regulatory_submission',
             'owned_table': 'sustainability_esg_reporting_regulatory_submission',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'emissions_factor_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'sustainability_esg_reporting_emissions_factor.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'emissions_factor_id',
                                'target_table': 'sustainability_esg_reporting_emissions_factor',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'appgen_outbox_event',
             'owned_table': 'sustainability_esg_reporting_appgen_outbox_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'emissions_factor_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'sustainability_esg_reporting_emissions_factor.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'appgen_inbox_event',
             'owned_table': 'sustainability_esg_reporting_appgen_inbox_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'emissions_factor_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'sustainability_esg_reporting_emissions_factor.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'appgen_dead_letter_event',
             'owned_table': 'sustainability_esg_reporting_appgen_dead_letter_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'emissions_factor_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'sustainability_esg_reporting_emissions_factor.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()}),
 'migrations': ('migrations/001_initial.sql',),
 'models': ({'class_name': 'SustainabilityEsgReportingEmissionsFactor',
             'table': 'sustainability_esg_reporting_emissions_factor',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'SustainabilityEsgReportingActivityData',
             'table': 'sustainability_esg_reporting_activity_data',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'emissions_factor_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'sustainability_esg_reporting_emissions_factor.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'emissions_factor_id',
                                'target_table': 'sustainability_esg_reporting_emissions_factor',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'SustainabilityEsgReportingCarbonLedgerEntry',
             'table': 'sustainability_esg_reporting_carbon_ledger_entry',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'emissions_factor_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'sustainability_esg_reporting_emissions_factor.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'emissions_factor_id',
                                'target_table': 'sustainability_esg_reporting_emissions_factor',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'SustainabilityEsgReportingEsgMetric',
             'table': 'sustainability_esg_reporting_esg_metric',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'emissions_factor_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'sustainability_esg_reporting_emissions_factor.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'emissions_factor_id',
                                'target_table': 'sustainability_esg_reporting_emissions_factor',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'SustainabilityEsgReportingSupplierDisclosure',
             'table': 'sustainability_esg_reporting_supplier_disclosure',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'emissions_factor_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'sustainability_esg_reporting_emissions_factor.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'emissions_factor_id',
                                'target_table': 'sustainability_esg_reporting_emissions_factor',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'SustainabilityEsgReportingAssuranceEvidence',
             'table': 'sustainability_esg_reporting_assurance_evidence',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'emissions_factor_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'sustainability_esg_reporting_emissions_factor.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'emissions_factor_id',
                                'target_table': 'sustainability_esg_reporting_emissions_factor',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'SustainabilityEsgReportingSustainabilityReport',
             'table': 'sustainability_esg_reporting_sustainability_report',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'emissions_factor_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'sustainability_esg_reporting_emissions_factor.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'emissions_factor_id',
                                'target_table': 'sustainability_esg_reporting_emissions_factor',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'SustainabilityEsgReportingRegulatorySubmission',
             'table': 'sustainability_esg_reporting_regulatory_submission',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'emissions_factor_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'sustainability_esg_reporting_emissions_factor.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'emissions_factor_id',
                                'target_table': 'sustainability_esg_reporting_emissions_factor',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'SustainabilityEsgReportingAppgenOutboxEvent',
             'table': 'sustainability_esg_reporting_appgen_outbox_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'emissions_factor_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'sustainability_esg_reporting_emissions_factor.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'SustainabilityEsgReportingAppgenInboxEvent',
             'table': 'sustainability_esg_reporting_appgen_inbox_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'emissions_factor_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'sustainability_esg_reporting_emissions_factor.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'SustainabilityEsgReportingAppgenDeadLetterEvent',
             'table': 'sustainability_esg_reporting_appgen_dead_letter_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'emissions_factor_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'sustainability_esg_reporting_emissions_factor.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()}),
 'datastore_backends': ('postgresql', 'mysql', 'mariadb'),
 'database_backends': ('postgresql', 'mysql', 'mariadb'),
 'shared_table_access': False,
 'pbc': 'sustainability_esg_reporting',
 'owned_tables': ('sustainability_esg_reporting_emissions_factor',
                  'sustainability_esg_reporting_activity_data',
                  'sustainability_esg_reporting_carbon_ledger_entry',
                  'sustainability_esg_reporting_esg_metric',
                  'sustainability_esg_reporting_supplier_disclosure',
                  'sustainability_esg_reporting_assurance_evidence',
                  'sustainability_esg_reporting_sustainability_report',
                  'sustainability_esg_reporting_regulatory_submission',
                  'sustainability_esg_reporting_appgen_outbox_event',
                  'sustainability_esg_reporting_appgen_inbox_event',
                  'sustainability_esg_reporting_appgen_dead_letter_event')}


def build_schema_contract():
    """Return generated owned schema, migration, and model evidence."""
    return dict(SCHEMA_CONTRACT)


def validate_schema_contract():
    contract = build_schema_contract()
    pbc = contract['pbc']
    owned_tables = tuple(contract.get('owned_tables', ()))
    model_tables = tuple(model['table'] for model in contract.get('models', ()))
    allowed_backends = {'postgresql', 'mysql', 'mariadb'}
    invalid_backends = tuple(backend for backend in contract.get('database_backends', ()) if backend not in allowed_backends)
    missing_models = tuple(table for table in owned_tables if table not in model_tables)
    invalid_tables = tuple(table for table in owned_tables if not table.startswith(f'{pbc}_'))
    return {'ok': contract.get('ok') is True and bool(owned_tables) and bool(contract.get('migrations')) and not invalid_tables and not missing_models and not invalid_backends and contract.get('shared_table_access') is False, 'pbc': pbc, 'owned_tables': owned_tables, 'model_tables': model_tables, 'migration_paths': tuple(contract.get('migrations', ())), 'invalid_tables': invalid_tables, 'missing_models': missing_models, 'invalid_backends': invalid_backends, 'side_effects': ()}


def smoke_test():
    return validate_schema_contract()
