"""Executable improve1 capability registry for this PBC.

This module turns the package-local improve1 backlog into code-level evidence.
It is intentionally side-effect free: callers can inspect capability coverage, plan
execution, and verify surface mappings without touching external systems.
"""

from __future__ import annotations

from dataclasses import dataclass

PBC_KEY = 'ap_automation'


@dataclass(frozen=True)
class Improve1Capability:
    feature_number: int
    title: str
    slug: str
    domain_tags: tuple[str, ...]
    model_artifacts: tuple[str, ...]
    ui_artifacts: tuple[str, ...]
    service_artifacts: tuple[str, ...]
    test_artifacts: tuple[str, ...]
    evidence_artifacts: tuple[str, ...]
    configurable: bool = True
    agent_assisted: bool = True
    side_effect_free_plan: bool = True

    def as_traceability_row(self) -> dict:
        return {
            "feature_number": self.feature_number,
            "title": self.title,
            "code_artifact_model": self.model_artifacts,
            "ui_surface": self.ui_artifacts,
            "service_api": self.service_artifacts,
            "test": self.test_artifacts,
            "evidence": self.evidence_artifacts,
            "configurable": self.configurable,
            "agent_assisted": self.agent_assisted,
            "side_effect_free_plan": self.side_effect_free_plan,
        }



IMPROVE1_CAPABILITIES: tuple[Improve1Capability, ...] = (
    Improve1Capability(
        feature_number=1,
        title='Vendor onboarding evidence pack',
        slug='vendor_onboarding_evidence_pack',
        domain_tags=('vendor',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=2,
        title='Vendor master lifecycle and change control',
        slug='vendor_master_lifecycle_and_change_control',
        domain_tags=('vendor',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=3,
        title='Beneficial ownership and related-party graph',
        slug='beneficial_ownership_and_related_party_graph',
        domain_tags=('domain_capability',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=4,
        title='Vendor bank account validation workflow',
        slug='vendor_bank_account_validation_workflow',
        domain_tags=('workflow', 'vendor'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=5,
        title='Payment hold and release governance',
        slug='payment_hold_and_release_governance',
        domain_tags=('payment',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=6,
        title='Vendor tax profile completeness gate',
        slug='vendor_tax_profile_completeness_gate',
        domain_tags=('vendor',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=7,
        title='E-invoice jurisdiction compliance matrix',
        slug='e_invoice_jurisdiction_compliance_matrix',
        domain_tags=('invoice',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=8,
        title='Multi-channel invoice capture normalization',
        slug='multi_channel_invoice_capture_normalization',
        domain_tags=('invoice',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=9,
        title='OCR and extraction confidence governance',
        slug='ocr_and_extraction_confidence_governance',
        domain_tags=('domain_capability',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=10,
        title='Semantic invoice-to-contract alignment',
        slug='semantic_invoice_to_contract_alignment',
        domain_tags=('invoice',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=11,
        title='Two-way and three-way match policy compiler',
        slug='two_way_and_three_way_match_policy_compiler',
        domain_tags=('policy',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=12,
        title='Probabilistic match explanation',
        slug='probabilistic_match_explanation',
        domain_tags=('domain_capability',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=13,
        title='Service invoice acceptance workflow',
        slug='service_invoice_acceptance_workflow',
        domain_tags=('workflow', 'invoice'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=14,
        title='Freight, tax, and miscellaneous charge matching',
        slug='freight_tax_and_miscellaneous_charge_matching',
        domain_tags=('domain_capability',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=15,
        title='Duplicate invoice detection across weak signals',
        slug='duplicate_invoice_detection_across_weak_signals',
        domain_tags=('invoice',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=16,
        title='Credit memo and debit memo lifecycle',
        slug='credit_memo_and_debit_memo_lifecycle',
        domain_tags=('credit',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=17,
        title='Invoice exception case management',
        slug='invoice_exception_case_management',
        domain_tags=('invoice',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=18,
        title='Approval route optimization with SoD',
        slug='approval_route_optimization_with_sod',
        domain_tags=('domain_capability',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=19,
        title='Delegation and out-of-office handling',
        slug='delegation_and_out_of_office_handling',
        domain_tags=('domain_capability',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=20,
        title='Dynamic discount capture strategy',
        slug='dynamic_discount_capture_strategy',
        domain_tags=('domain_capability',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=21,
        title='Payment scheduling with liquidity constraints',
        slug='payment_scheduling_with_liquidity_constraints',
        domain_tags=('payment',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=22,
        title='Payment batch approval and release control',
        slug='payment_batch_approval_and_release_control',
        domain_tags=('payment',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=23,
        title='Payment rail selection and failover',
        slug='payment_rail_selection_and_failover',
        domain_tags=('payment',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=24,
        title='Remittance advice lifecycle',
        slug='remittance_advice_lifecycle',
        domain_tags=('domain_capability',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=25,
        title='Vendor statement reconciliation',
        slug='vendor_statement_reconciliation',
        domain_tags=('reconciliation', 'vendor'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=26,
        title='Withholding tax calculation and certificate expiry',
        slug='withholding_tax_calculation_and_certificate_expiry',
        domain_tags=('domain_capability',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=27,
        title='Tax engine handoff proof',
        slug='tax_engine_handoff_proof',
        domain_tags=('domain_capability',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=28,
        title='GL accrual and liability handoff',
        slug='gl_accrual_and_liability_handoff',
        domain_tags=('domain_capability',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=29,
        title='Accrual for received-not-invoiced items',
        slug='accrual_for_received_not_invoiced_items',
        domain_tags=('invoice',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=30,
        title='Prepayment and advance management',
        slug='prepayment_and_advance_management',
        domain_tags=('payment',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=31,
        title='Supplier financing and reverse factoring',
        slug='supplier_financing_and_reverse_factoring',
        domain_tags=('domain_capability',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=32,
        title='Fraud pattern detection',
        slug='fraud_pattern_detection',
        domain_tags=('domain_capability',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=33,
        title='Split invoice and threshold avoidance detection',
        slug='split_invoice_and_threshold_avoidance_detection',
        domain_tags=('invoice',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=34,
        title='Vendor risk scoring governance',
        slug='vendor_risk_scoring_governance',
        domain_tags=('risk', 'vendor'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=35,
        title='Supplier communication workspace',
        slug='supplier_communication_workspace',
        domain_tags=('domain_capability',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=36,
        title='Vendor portal task queue',
        slug='vendor_portal_task_queue',
        domain_tags=('vendor',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=37,
        title='AP close cockpit',
        slug='ap_close_cockpit',
        domain_tags=('close',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=38,
        title='Aging and working-capital analytics',
        slug='aging_and_working_capital_analytics',
        domain_tags=('analytics',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=39,
        title='Payment recovery and overpayment management',
        slug='payment_recovery_and_overpayment_management',
        domain_tags=('payment',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=40,
        title='Cash forecast feedback loop',
        slug='cash_forecast_feedback_loop',
        domain_tags=('domain_capability',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=41,
        title='Cross-border payment compliance',
        slug='cross_border_payment_compliance',
        domain_tags=('payment',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=42,
        title='Payment execution idempotency ledger',
        slug='payment_execution_idempotency_ledger',
        domain_tags=('payment', 'ledger'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=43,
        title='Dead-letter and payment failure recovery',
        slug='dead_letter_and_payment_failure_recovery',
        domain_tags=('payment',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=44,
        title='Agent-safe invoice ingestion',
        slug='agent_safe_invoice_ingestion',
        domain_tags=('agent', 'invoice'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=45,
        title='Agent-safe payment actions',
        slug='agent_safe_payment_actions',
        domain_tags=('agent', 'payment'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=46,
        title='AP rules and parameter simulation',
        slug='ap_rules_and_parameter_simulation',
        domain_tags=('rule',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=47,
        title='Workbench surface for all AP capabilities',
        slug='workbench_surface_for_all_ap_capabilities',
        domain_tags=('domain_capability',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=48,
        title='Boundary proof for AP-only ownership',
        slug='boundary_proof_for_ap_only_ownership',
        domain_tags=('domain_capability',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=49,
        title='AP release readiness score',
        slug='ap_release_readiness_score',
        domain_tags=('domain_capability',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
    Improve1Capability(
        feature_number=50,
        title='End-to-end procure-to-pay trace',
        slug='end_to_end_procure_to_pay_trace',
        domain_tags=('domain_capability',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py'),
        service_artifacts=('services.py', 'routes.py', 'runtime.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_implementation.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone_surfaces.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md'),
    ),
)



def capability_registry() -> dict:
    """Return side-effect-free registry metadata for improve1 capabilities."""
    rows = tuple(capability.as_traceability_row() for capability in IMPROVE1_CAPABILITIES)
    return {
        "ok": len(rows) == 50 and all(row["code_artifact_model"] and row["ui_surface"] and row["service_api"] and row["test"] and row["evidence"] for row in rows),
        "pbc": PBC_KEY,
        "capability_count": len(rows),
        "capabilities": rows,
        "side_effects": (),
    }


def plan_feature_execution(feature_number: int) -> dict:
    """Plan how a feature is exercised without mutating package state."""
    match = next((capability for capability in IMPROVE1_CAPABILITIES if capability.feature_number == feature_number), None)
    if match is None:
        return {"ok": False, "pbc": PBC_KEY, "reason": "unknown_feature", "side_effects": ()}
    return {
        "ok": True,
        "pbc": PBC_KEY,
        "feature_number": match.feature_number,
        "title": match.title,
        "domain_tags": match.domain_tags,
        "model_artifacts": match.model_artifacts,
        "ui_artifacts": match.ui_artifacts,
        "service_artifacts": match.service_artifacts,
        "test_artifacts": match.test_artifacts,
        "evidence_artifacts": match.evidence_artifacts,
        "requires_configuration": match.configurable,
        "agent_assisted": match.agent_assisted,
        "side_effects": (),
    }


def validate_improve1_capabilities(expected_titles: tuple[str, ...]) -> dict:
    """Validate registry alignment with parsed improve1 titles."""
    actual_titles = tuple(capability.title for capability in IMPROVE1_CAPABILITIES)
    return {
        "ok": len(actual_titles) == 50 and actual_titles == expected_titles and capability_registry()["ok"],
        "pbc": PBC_KEY,
        "expected_count": len(expected_titles),
        "actual_count": len(actual_titles),
        "titles_match": actual_titles == expected_titles,
        "side_effects": (),
    }
