"""Package manifest for the master_data_governance PBC."""

PBC_MANIFEST = {'pbc': 'master_data_governance',
 'label': 'Master Data Governance',
 'mesh': 'platform',
 'description': 'Golden records, stewardship workflows, match and merge, validation rules, survivorship, change '
                'approvals, and downstream sync events.',
 'version': '1.0.0',
 'datastore_backend': 'postgresql',
 'tables': ('master_record',
            'golden_record',
            'match_candidate',
            'merge_decision',
            'survivorship_rule',
            'data_quality_rule',
            'stewardship_task',
            'downstream_sync_event'),
 'apis': ('POST /master-records',
          'POST /match-candidates',
          'POST /merge-decisions',
          'POST /stewardship-tasks',
          'GET /master-data-workbench'),
 'emits': ('GoldenRecordPublished', 'MergeDecisionApproved', 'StewardshipTaskOpened', 'MasterDataSynced'),
 'consumes': ('CustomerUpdated', 'SupplierQualified', 'ProductPublished'),
 'template': None,
 'ui_fragments': ('MasterDataGovernanceWorkbench', 'MasterDataGovernanceDetail', 'MasterDataGovernanceAssistantPanel'),
 'permissions': ('master_data_governance.read',
                 'master_data_governance.create',
                 'master_data_governance.update',
                 'master_data_governance.approve',
                 'master_data_governance.admin'),
 'configuration': ('MASTER_DATA_GOVERNANCE_DATABASE_URL',
                   'MASTER_DATA_GOVERNANCE_EVENT_TOPIC',
                   'MASTER_DATA_GOVERNANCE_RETRY_LIMIT',
                   'MASTER_DATA_GOVERNANCE_DEFAULT_POLICY'),
 'migrations': ('migrations/001_initial.sql',),
 'seed_data': ('seed_data.py',),
 'tests': ('tests/test_contract.py',),
 'docs': ('SPECIFICATION.md', 'RELEASE_EVIDENCE.md'),
 'capabilities': ('master_record_management',
                  'master_data_governance_workflow',
                  'master_data_governance_analytics',
                  'configuration_schema',
                  'rule_engine',
                  'parameter_engine',
                  'owned_schema_migrations_models',
                  'appgen_x_outbox_inbox_eventing',
                  'idempotent_handlers',
                  'retry_dead_letter_evidence',
                  'permissions',
                  'seed_data',
                  'workbench',
                  'agentic_document_instruction_intake',
                  'governed_datastore_crud',
                  'master_data_governance_event_sourced_operational_history',
                  'master_data_governance_multi_tenant_policy_isolation',
                  'master_data_governance_schema_evolution_resilience',
                  'master_data_governance_autonomous_anomaly_detection',
                  'master_data_governance_semantic_document_instruction_understanding',
                  'master_data_governance_predictive_risk_scoring',
                  'master_data_governance_counterfactual_scenario_simulation',
                  'master_data_governance_cryptographic_audit_proofs',
                  'master_data_governance_continuous_control_testing',
                  'master_data_governance_carbon_and_sustainability_awareness',
                  'master_data_governance_cross_pbc_event_federation',
                  'master_data_governance_governed_ai_agent_execution'),
 'standard_features': ('master_record_management',
                       'master_data_governance_workflow',
                       'master_data_governance_analytics',
                       'configuration_schema',
                       'rule_engine',
                       'parameter_engine',
                       'owned_schema_migrations_models',
                       'appgen_x_outbox_inbox_eventing',
                       'idempotent_handlers',
                       'retry_dead_letter_evidence',
                       'permissions',
                       'seed_data',
                       'workbench',
                       'agentic_document_instruction_intake',
                       'governed_datastore_crud'),
 'advanced_capabilities': ('master_data_governance_event_sourced_operational_history',
                           'master_data_governance_multi_tenant_policy_isolation',
                           'master_data_governance_schema_evolution_resilience',
                           'master_data_governance_autonomous_anomaly_detection',
                           'master_data_governance_semantic_document_instruction_understanding',
                           'master_data_governance_predictive_risk_scoring',
                           'master_data_governance_counterfactual_scenario_simulation',
                           'master_data_governance_cryptographic_audit_proofs',
                           'master_data_governance_continuous_control_testing',
                           'master_data_governance_carbon_and_sustainability_awareness',
                           'master_data_governance_cross_pbc_event_federation',
                           'master_data_governance_governed_ai_agent_execution'),
 'workflows': ('master_record_workflow', 'master_data_governance_approval_workflow'),
 'analytics': ('master_data_governance_risk_score', 'master_data_governance_workbench_metric')}
