"""Generated owned schema evidence for the master_data_governance PBC."""

SCHEMA_CONTRACT = {'format': 'appgen.master-data-governance-owned-schema-contract.v1',
 'ok': True,
 'tables': ({'logical_table': 'master_record',
             'owned_table': 'master_data_governance_master_record',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'golden_record',
             'owned_table': 'master_data_governance_golden_record',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'master_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'master_data_governance_master_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'master_record_id',
                                'target_table': 'master_data_governance_master_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'match_candidate',
             'owned_table': 'master_data_governance_match_candidate',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'master_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'master_data_governance_master_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'master_record_id',
                                'target_table': 'master_data_governance_master_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'merge_decision',
             'owned_table': 'master_data_governance_merge_decision',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'master_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'master_data_governance_master_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'master_record_id',
                                'target_table': 'master_data_governance_master_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'survivorship_rule',
             'owned_table': 'master_data_governance_survivorship_rule',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'master_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'master_data_governance_master_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'master_record_id',
                                'target_table': 'master_data_governance_master_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'data_quality_rule',
             'owned_table': 'master_data_governance_data_quality_rule',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'master_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'master_data_governance_master_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'master_record_id',
                                'target_table': 'master_data_governance_master_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'stewardship_task',
             'owned_table': 'master_data_governance_stewardship_task',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'master_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'master_data_governance_master_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'master_record_id',
                                'target_table': 'master_data_governance_master_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'downstream_sync_event',
             'owned_table': 'master_data_governance_downstream_sync_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'master_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'master_data_governance_master_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'master_record_id',
                                'target_table': 'master_data_governance_master_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'appgen_outbox_event',
             'owned_table': 'master_data_governance_appgen_outbox_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'master_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'master_data_governance_master_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'appgen_inbox_event',
             'owned_table': 'master_data_governance_appgen_inbox_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'master_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'master_data_governance_master_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'appgen_dead_letter_event',
             'owned_table': 'master_data_governance_appgen_dead_letter_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'master_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'master_data_governance_master_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()}),
 'migrations': ('migrations/001_initial.sql',),
 'models': ({'class_name': 'MasterDataGovernanceMasterRecord',
             'table': 'master_data_governance_master_record',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'MasterDataGovernanceGoldenRecord',
             'table': 'master_data_governance_golden_record',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'master_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'master_data_governance_master_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'master_record_id',
                                'target_table': 'master_data_governance_master_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'MasterDataGovernanceMatchCandidate',
             'table': 'master_data_governance_match_candidate',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'master_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'master_data_governance_master_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'master_record_id',
                                'target_table': 'master_data_governance_master_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'MasterDataGovernanceMergeDecision',
             'table': 'master_data_governance_merge_decision',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'master_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'master_data_governance_master_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'master_record_id',
                                'target_table': 'master_data_governance_master_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'MasterDataGovernanceSurvivorshipRule',
             'table': 'master_data_governance_survivorship_rule',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'master_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'master_data_governance_master_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'master_record_id',
                                'target_table': 'master_data_governance_master_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'MasterDataGovernanceDataQualityRule',
             'table': 'master_data_governance_data_quality_rule',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'master_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'master_data_governance_master_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'master_record_id',
                                'target_table': 'master_data_governance_master_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'MasterDataGovernanceStewardshipTask',
             'table': 'master_data_governance_stewardship_task',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'master_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'master_data_governance_master_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'master_record_id',
                                'target_table': 'master_data_governance_master_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'MasterDataGovernanceDownstreamSyncEvent',
             'table': 'master_data_governance_downstream_sync_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'master_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'master_data_governance_master_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'master_record_id',
                                'target_table': 'master_data_governance_master_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'MasterDataGovernanceAppgenOutboxEvent',
             'table': 'master_data_governance_appgen_outbox_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'master_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'master_data_governance_master_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'MasterDataGovernanceAppgenInboxEvent',
             'table': 'master_data_governance_appgen_inbox_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'master_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'master_data_governance_master_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'MasterDataGovernanceAppgenDeadLetterEvent',
             'table': 'master_data_governance_appgen_dead_letter_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'master_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'master_data_governance_master_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()}),
 'datastore_backends': ('postgresql', 'mysql', 'mariadb'),
 'database_backends': ('postgresql', 'mysql', 'mariadb'),
 'shared_table_access': False,
 'pbc': 'master_data_governance',
 'owned_tables': ('master_data_governance_master_record',
                  'master_data_governance_golden_record',
                  'master_data_governance_match_candidate',
                  'master_data_governance_merge_decision',
                  'master_data_governance_survivorship_rule',
                  'master_data_governance_data_quality_rule',
                  'master_data_governance_stewardship_task',
                  'master_data_governance_downstream_sync_event',
                  'master_data_governance_appgen_outbox_event',
                  'master_data_governance_appgen_inbox_event',
                  'master_data_governance_appgen_dead_letter_event')}


def build_schema_contract():
    """Return generated owned schema, migration, and model evidence."""
    return dict(SCHEMA_CONTRACT)


def validate_schema_contract():
    contract = build_schema_contract()
    pbc = contract['pbc']
    owned_tables = tuple(contract.get('owned_tables', ()))
    model_tables = tuple(model['table'] for model in contract.get('models', ()))
    allowed_backends = {'postgresql', 'mysql', 'mariadb'}
    invalid_backends = tuple(backend for backend in contract.get('database_backends', ()) if backend not in allowed_backends)
    missing_models = tuple(table for table in owned_tables if table not in model_tables)
    invalid_tables = tuple(table for table in owned_tables if not table.startswith(f'{pbc}_'))
    return {'ok': contract.get('ok') is True and bool(owned_tables) and bool(contract.get('migrations')) and not invalid_tables and not missing_models and not invalid_backends and contract.get('shared_table_access') is False, 'pbc': pbc, 'owned_tables': owned_tables, 'model_tables': model_tables, 'migration_paths': tuple(contract.get('migrations', ())), 'invalid_tables': invalid_tables, 'missing_models': missing_models, 'invalid_backends': invalid_backends, 'side_effects': ()}


def smoke_test():
    return validate_schema_contract()
