"""Package manifest for the cybersecurity_operations_center PBC."""

PBC_MANIFEST = {'advanced_capabilities': ('cybersecurity_operations_center_event_sourced_operational_history',
                           'cybersecurity_operations_center_multi_tenant_policy_isolation',
                           'cybersecurity_operations_center_schema_evolution_resilience',
                           'cybersecurity_operations_center_autonomous_anomaly_detection',
                           'cybersecurity_operations_center_semantic_document_instruction_understanding',
                           'cybersecurity_operations_center_predictive_risk_scoring',
                           'cybersecurity_operations_center_counterfactual_scenario_simulation',
                           'cybersecurity_operations_center_cryptographic_audit_proofs',
                           'cybersecurity_operations_center_continuous_control_testing',
                           'cybersecurity_operations_center_carbon_and_sustainability_awareness',
                           'cybersecurity_operations_center_cross_pbc_event_federation',
                           'cybersecurity_operations_center_governed_ai_agent_execution'),
 'analytics': ('cybersecurity_operations_center_risk_score',
               'cybersecurity_operations_center_workbench_metric'),
 'apis': ('POST /security-alerts',
          'POST /security-incidents',
          'POST /asset-exposures',
          'POST /threat-intels',
          'POST /playbook-runs',
          'GET /cybersecurity-operations-center-workbench'),
 'capabilities': ('security_alert_management',
                  'cybersecurity_operations_center_workflow',
                  'cybersecurity_operations_center_analytics',
                  'configuration_schema',
                  'rule_engine',
                  'parameter_engine',
                  'owned_schema_migrations_models',
                  'appgen_x_outbox_inbox_eventing',
                  'idempotent_handlers',
                  'retry_dead_letter_evidence',
                  'permissions',
                  'seed_data',
                  'workbench',
                  'agentic_document_instruction_intake',
                  'governed_datastore_crud',
                  'ai_agent_task_assistance',
                  'configuration_workbench',
                  'continuous_release_assurance',
                  'cybersecurity_operations_center_event_sourced_operational_history',
                  'cybersecurity_operations_center_multi_tenant_policy_isolation',
                  'cybersecurity_operations_center_schema_evolution_resilience',
                  'cybersecurity_operations_center_autonomous_anomaly_detection',
                  'cybersecurity_operations_center_semantic_document_instruction_understanding',
                  'cybersecurity_operations_center_predictive_risk_scoring',
                  'cybersecurity_operations_center_counterfactual_scenario_simulation',
                  'cybersecurity_operations_center_cryptographic_audit_proofs',
                  'cybersecurity_operations_center_continuous_control_testing',
                  'cybersecurity_operations_center_carbon_and_sustainability_awareness',
                  'cybersecurity_operations_center_cross_pbc_event_federation',
                  'cybersecurity_operations_center_governed_ai_agent_execution'),
 'configuration': ('CYBERSECURITY_OPERATIONS_CENTER_DATABASE_URL',
                   'CYBERSECURITY_OPERATIONS_CENTER_EVENT_TOPIC',
                   'CYBERSECURITY_OPERATIONS_CENTER_RETRY_LIMIT',
                   'CYBERSECURITY_OPERATIONS_CENTER_DEFAULT_POLICY'),
 'consumes': ('PolicyChanged', 'AuditEventSealed', 'OperationalKpiChanged'),
 'datastore_backend': 'postgresql',
 'description': 'Security alerts, incidents, assets, threat intelligence, playbooks, containment, '
                'and response evidence',
 'docs': ('SPECIFICATION.md', 'RELEASE_EVIDENCE.md'),
 'emits': ('CybersecurityOperationsCenterCreated',
           'CybersecurityOperationsCenterUpdated',
           'CybersecurityOperationsCenterApproved',
           'CybersecurityOperationsCenterExceptionOpened'),
 'label': 'Cybersecurity Operations Center',
 'mesh': 'platform',
 'migrations': ('migrations/001_initial.sql',),
 'pbc': 'cybersecurity_operations_center',
 'permissions': ('cybersecurity_operations_center.read',
                 'cybersecurity_operations_center.create',
                 'cybersecurity_operations_center.update',
                 'cybersecurity_operations_center.approve',
                 'cybersecurity_operations_center.admin'),
 'seed_data': ('seed_data.py',),
 'standard_features': ('security_alert_management',
                       'cybersecurity_operations_center_workflow',
                       'cybersecurity_operations_center_analytics',
                       'configuration_schema',
                       'rule_engine',
                       'parameter_engine',
                       'owned_schema_migrations_models',
                       'appgen_x_outbox_inbox_eventing',
                       'idempotent_handlers',
                       'retry_dead_letter_evidence',
                       'permissions',
                       'seed_data',
                       'workbench',
                       'agentic_document_instruction_intake',
                       'governed_datastore_crud',
                       'ai_agent_task_assistance',
                       'configuration_workbench',
                       'continuous_release_assurance'),
 'tables': ('security_alert',
            'security_incident',
            'asset_exposure',
            'threat_intel',
            'playbook_run',
            'containment_action',
            'response_evidence',
            'cybersecurity_operations_center_policy_rule',
            'cybersecurity_operations_center_runtime_parameter',
            'cybersecurity_operations_center_schema_extension',
            'cybersecurity_operations_center_control_assertion',
            'cybersecurity_operations_center_governed_model'),
 'template': None,
 'tests': ('tests/test_contract.py',),
 'ui_fragments': ('CybersecurityOperationsCenterWorkbench',
                  'CybersecurityOperationsCenterDetail',
                  'CybersecurityOperationsCenterAssistantPanel'),
 'version': '1.0.0',
 'workflows': ('cybersecurity_operations_center_create_security_alert_workflow',
               'cybersecurity_operations_center_record_security_incident_workflow')}
