"""Domain forms for the maritime_shipping_operations PBC."""
from __future__ import annotations
PBC_KEY = "maritime_shipping_operations"
FORM_CATALOG = (
    {"key":"voyage_rotation_form","title":"Voyage legs, rotations, and schedule baseline","target_table":"maritime_shipping_operations_voyage","fields":("voyage_id","service_string","trade_lane","vessel_id","legs","proforma_eta","revised_eta","actual_eta","delay_buckets","status"),"validations":("legs_ordered","etas_reconciled","delay_reason_required"),"permission":"maritime_shipping_operations.create"},
    {"key":"vessel_readiness_form","title":"Vessel and crewing-boundary readiness","target_table":"maritime_shipping_operations_vessel","fields":("vessel_id","imo","class_status","minimum_safe_manning_valid","crew_readiness_signal","certificate_expiry","cargo_gear_status","readiness_verdict"),"validations":("certificates_valid","crewing_signal_consumed_not_owned","gear_ready"),"permission":"maritime_shipping_operations.approve"},
    {"key":"cargo_booking_form","title":"Cargo booking, cutoff, bill, and allocation","target_table":"maritime_shipping_operations_cargo_booking","fields":("booking_id","voyage_id","leg","shipper","consignee","commodity","teu","weight","reefer_setpoint","dg_class","cutoffs","bill_status"),"validations":("capacity_available","cutoffs_open_or_approved","bill_party_screened"),"permission":"maritime_shipping_operations.create"},
    {"key":"charter_clause_form","title":"Charter party clause and laytime setup","target_table":"maritime_shipping_operations_charter_party","fields":("charter_id","voyage_id","laycan","load_rate","discharge_rate","demurrage_rate","despatch_rate","shex_shinc","weather_exception","notice_requirements"),"validations":("clause_versioned","rates_present","notice_rule_present"),"permission":"maritime_shipping_operations.approve"},
    {"key":"port_call_sof_form","title":"Port call window and statement of facts","target_table":"maritime_shipping_operations_port_call","fields":("port_call_id","voyage_id","terminal","berth_window","pilot_ordered","tugs","gangs","nor_tendered","all_fast","cargo_ops_start","cargo_ops_stop","weather_interruptions"),"validations":("timezone_present","sof_sequence_valid","attachments_present"),"permission":"maritime_shipping_operations.update"},
    {"key":"stowage_special_cargo_form","title":"Stowage, dangerous goods, OOG, and reefer controls","target_table":"maritime_shipping_operations_cargo_booking","fields":("booking_id","bay_row_tier","discharge_sequence","stack_weight","segregation_rule","lashing_required","imdg_docs","oog_dimensions","pti_confirmed","temperature_monitoring"),"validations":("stowage_sequence_possible","special_cargo_docs_complete","reefer_plug_reserved"),"permission":"maritime_shipping_operations.approve"},
    {"key":"demurrage_claim_form","title":"Laytime, demurrage, detention, and claim dossier","target_table":"maritime_shipping_operations_demurrage_claim","fields":("claim_id","voyage_id","port_call_id","laytime_used","demurrage_amount","detention_amount","responsible_party","dossier_documents","dispute_status","settlement_amount"),"validations":("laytime_trace_present","dossier_complete","approval_limit_checked"),"permission":"maritime_shipping_operations.approve"},
    {"key":"bunker_carbon_form","title":"Bunker uplift, ROB, consumption, and carbon view","target_table":"maritime_shipping_operations_bunker_event","fields":("bunker_id","voyage_id","uplift_port","supplier","grade","quantity","price_basis","departure_rob","arrival_rob","consumption_variance","emissions_tonnes","cii_exposure"),"validations":("rob_sufficient","sulfur_context_valid","variance_explained"),"permission":"maritime_shipping_operations.update"},
    {"key":"compliance_register_form","title":"Voyage compliance and restricted-party register","target_table":"maritime_shipping_operations_maritime_shipping_operations_control_assertion","fields":("obligation_id","voyage_id","port_call_id","cargo_booking_id","obligation_type","due_date","status","accountable_role","regulation_source","screening_disposition"),"validations":("due_date_present","restricted_parties_cleared","closure_evidence_present"),"permission":"maritime_shipping_operations.approve"},
)
def form_catalog() -> dict:
    return {"ok": True, "pbc": PBC_KEY, "forms": FORM_CATALOG, "side_effects": ()}
def smoke_test() -> dict:
    return {"ok": len(FORM_CATALOG) >= 9 and all(f["target_table"].startswith(f"{PBC_KEY}_") for f in FORM_CATALOG), "side_effects": ()}
