"""Executable improve1 capability registry for this PBC.

This module turns the package-local improve1 backlog into code-level evidence.
It is intentionally side-effect free: callers can inspect capability coverage, plan
execution, and verify surface mappings without touching external systems.
"""

from __future__ import annotations

from dataclasses import dataclass

PBC_KEY = 'dom'


@dataclass(frozen=True)
class Improve1Capability:
    feature_number: int
    title: str
    slug: str
    domain_tags: tuple[str, ...]
    model_artifacts: tuple[str, ...]
    ui_artifacts: tuple[str, ...]
    service_artifacts: tuple[str, ...]
    test_artifacts: tuple[str, ...]
    evidence_artifacts: tuple[str, ...]
    configurable: bool = True
    agent_assisted: bool = True
    side_effect_free_plan: bool = True

    def as_traceability_row(self) -> dict:
        return {
            "feature_number": self.feature_number,
            "title": self.title,
            "slug": self.slug,
            "domain_tags": self.domain_tags,
            "code_artifact_model": self.model_artifacts,
            "ui_surface": self.ui_artifacts,
            "service_api": self.service_artifacts,
            "test": self.test_artifacts,
            "evidence": self.evidence_artifacts,
            "configurable": self.configurable,
            "agent_assisted": self.agent_assisted,
            "side_effect_free_plan": self.side_effect_free_plan,
        }



IMPROVE1_CAPABILITIES: tuple[Improve1Capability, ...] = (
    Improve1Capability(
        feature_number=1,
        title='Order capture readiness gate',
        slug='order_capture_readiness_gate',
        domain_tags=('order', 'capture', 'readiness'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=2,
        title='Channel context normalization',
        slug='channel_context_normalization',
        domain_tags=('channel', 'context', 'normalization'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=3,
        title='Order line integrity engine',
        slug='order_line_integrity_engine',
        domain_tags=('order', 'integrity', 'engine'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=4,
        title='Order status state machine',
        slug='order_status_state_machine',
        domain_tags=('order', 'status', 'state'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=5,
        title='Hold and release governance',
        slug='hold_and_release_governance',
        domain_tags=('governance',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=6,
        title='Customer projection confidence',
        slug='customer_projection_confidence',
        domain_tags=('customer', 'project'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=7,
        title='Customer identity reconciliation',
        slug='customer_identity_reconciliation',
        domain_tags=('customer', 'identity', 'reconciliation'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=8,
        title='Tax projection gating',
        slug='tax_projection_gating',
        domain_tags=('project', 'tax'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=9,
        title='Payment authorization projection handling',
        slug='payment_authorization_projection_handling',
        domain_tags=('payment', 'project'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=10,
        title='Fraud signal fusion',
        slug='fraud_signal_fusion',
        domain_tags=('fraud', 'signal', 'fusion'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=11,
        title='Fraud review workflow',
        slug='fraud_review_workflow',
        domain_tags=('workflow',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=12,
        title='Order verification proof',
        slug='order_verification_proof',
        domain_tags=('order', 'verification', 'proof'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=13,
        title='Price component trace',
        slug='price_component_trace',
        domain_tags=('price', 'component', 'trace'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=14,
        title='Discount and promotion projection governance',
        slug='discount_and_promotion_projection_governance',
        domain_tags=('governance', 'project'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=15,
        title='Allocation confidence model',
        slug='allocation_confidence_model',
        domain_tags=('model',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=16,
        title='Inventory node candidate scoring',
        slug='inventory_node_candidate_scoring',
        domain_tags=('inventory',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=17,
        title='Fulfillment policy compiler',
        slug='fulfillment_policy_compiler',
        domain_tags=('policy',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=18,
        title='Split shipment governance',
        slug='split_shipment_governance',
        domain_tags=('governance',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=19,
        title='Backorder lifecycle',
        slug='backorder_lifecycle',
        domain_tags=('backorder', 'lifecycle'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=20,
        title='Substitution eligibility engine',
        slug='substitution_eligibility_engine',
        domain_tags=('substitution', 'eligibility', 'engine'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=21,
        title='Cancellation request workflow',
        slug='cancellation_request_workflow',
        domain_tags=('workflow',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=22,
        title='Promise date governance',
        slug='promise_date_governance',
        domain_tags=('governance',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=23,
        title='Demand and promise forecasting',
        slug='demand_and_promise_forecasting',
        domain_tags=('forecast',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=24,
        title='Fulfillment plan lifecycle',
        slug='fulfillment_plan_lifecycle',
        domain_tags=('fulfillment', 'lifecycle'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=25,
        title='Route selection replay',
        slug='route_selection_replay',
        domain_tags=('route', 'selection', 'replay'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=26,
        title='Shipment projection reconciliation',
        slug='shipment_projection_reconciliation',
        domain_tags=('project', 'reconciliation'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=27,
        title='Order exception taxonomy',
        slug='order_exception_taxonomy',
        domain_tags=('tax',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=28,
        title='Exception resolution recommender',
        slug='exception_resolution_recommender',
        domain_tags=('exception', 'resolution', 'recommender'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=29,
        title='Order anomaly detection',
        slug='order_anomaly_detection',
        domain_tags=('order', 'anomaly', 'detection'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=30,
        title='Stochastic fulfillment exposure',
        slug='stochastic_fulfillment_exposure',
        domain_tags=('stochastic', 'fulfillment', 'exposure'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=31,
        title='Carbon-aware fulfillment planning',
        slug='carbon_aware_fulfillment_planning',
        domain_tags=('carbon_aware', 'fulfillment', 'planning'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=32,
        title='Fulfillment optimization with constraints',
        slug='fulfillment_optimization_with_constraints',
        domain_tags=('fulfillment', 'optimization', 'constraints'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=33,
        title='Mechanism-design allocation across channels',
        slug='mechanism_design_allocation_across_channels',
        domain_tags=('mechanism_design', 'allocation', 'across'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=34,
        title='Order federation without shared tables',
        slug='order_federation_without_shared_tables',
        domain_tags=('order', 'federation', 'without'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=35,
        title='AppGen-X event reliability cockpit',
        slug='appgen_x_event_reliability_cockpit',
        domain_tags=('event',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=36,
        title='Order audit trace and hash chain',
        slug='order_audit_trace_and_hash_chain',
        domain_tags=('audit',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=37,
        title='Zero-knowledge order verification proof',
        slug='zero_knowledge_order_verification_proof',
        domain_tags=('zero_knowledge', 'order', 'verification'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=38,
        title='Dynamic order policy screening',
        slug='dynamic_order_policy_screening',
        domain_tags=('policy',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=39,
        title='Rule and parameter simulation',
        slug='rule_and_parameter_simulation',
        domain_tags=('parameter', 'simulation'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=40,
        title='Order MLOps governance',
        slug='order_mlops_governance',
        domain_tags=('governance',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=41,
        title='Multi-channel and tenant isolation',
        slug='multi_channel_and_tenant_isolation',
        domain_tags=('multi_channel', 'tenant', 'isolation'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=42,
        title='Order workbench coverage',
        slug='order_workbench_coverage',
        domain_tags=('order', 'workbench', 'coverage'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=43,
        title='Agent-safe order document intake',
        slug='agent_safe_order_document_intake',
        domain_tags=('agent', 'document'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=44,
        title='Agent-safe orchestration planning',
        slug='agent_safe_orchestration_planning',
        domain_tags=('agent', 'orchestration'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=45,
        title='Customer communication readiness',
        slug='customer_communication_readiness',
        domain_tags=('customer',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=46,
        title='Chaos-engineered orchestration tolerance',
        slug='chaos_engineered_orchestration_tolerance',
        domain_tags=('orchestration',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=47,
        title='Continuous order control testing',
        slug='continuous_order_control_testing',
        domain_tags=('continuous', 'order', 'control'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=48,
        title='Order close and lifecycle completeness',
        slug='order_close_and_lifecycle_completeness',
        domain_tags=('close',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=49,
        title='DOM readiness score',
        slug='dom_readiness_score',
        domain_tags=('readiness', 'score'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=50,
        title='End-to-end order orchestration proof',
        slug='end_to_end_order_orchestration_proof',
        domain_tags=('orchestration',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_runtime_capabilities.py', 'tests/test_standalone.py', 'tests/test_standalone_dom.py', 'tests/test_domain_behavior.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
)



def capability_registry() -> dict:
    """Return side-effect-free registry metadata for improve1 capabilities."""
    rows = tuple(capability.as_traceability_row() for capability in IMPROVE1_CAPABILITIES)
    return {
        "ok": len(rows) == 50 and all(row["code_artifact_model"] and row["ui_surface"] and row["service_api"] and row["test"] and row["evidence"] for row in rows),
        "pbc": PBC_KEY,
        "capability_count": len(rows),
        "capabilities": rows,
        "side_effects": (),
    }


def plan_feature_execution(feature_number: int) -> dict:
    """Plan how a feature is exercised without mutating package state."""
    match = next((capability for capability in IMPROVE1_CAPABILITIES if capability.feature_number == feature_number), None)
    if match is None:
        return {"ok": False, "pbc": PBC_KEY, "reason": "unknown_feature", "side_effects": ()}
    return {
        "ok": True,
        "pbc": PBC_KEY,
        "feature_number": match.feature_number,
        "title": match.title,
        "slug": match.slug,
        "domain_tags": match.domain_tags,
        "model_artifacts": match.model_artifacts,
        "ui_artifacts": match.ui_artifacts,
        "service_artifacts": match.service_artifacts,
        "test_artifacts": match.test_artifacts,
        "evidence_artifacts": match.evidence_artifacts,
        "requires_configuration": match.configurable,
        "agent_assisted": match.agent_assisted,
        "side_effects": (),
    }


def validate_improve1_capabilities(expected_titles: tuple[str, ...]) -> dict:
    """Validate registry alignment with parsed improve1 titles."""
    actual_titles = tuple(capability.title for capability in IMPROVE1_CAPABILITIES)
    registry = capability_registry()
    return {
        "ok": len(actual_titles) == 50 and actual_titles == expected_titles and registry["ok"],
        "pbc": PBC_KEY,
        "expected_count": len(expected_titles),
        "actual_count": len(actual_titles),
        "titles_match": actual_titles == expected_titles,
        "registry_ok": registry["ok"],
        "side_effects": (),
    }
