# 'gl_core' source package manifest
PBC_MANIFEST = {
    "pbc": "gl_core",
    "label": "General Ledger Core",
    "mesh": "finops",
    "description": "Standalone general ledger truth with journal governance, close controls, and AppGen-X event synchronization.",
    "datastore_backend": "postgresql",
    "tables": (
        "ledger_event_log",
        "journal_event",
        "journal_entry",
        "journal_line",
        "ledger_account",
        "accounting_period",
        "ledger_projection",
        "account_projection",
        "consensus_replica",
        "schema_extension",
        "tenant_ledger_partition",
        "probabilistic_posting",
        "close_snapshot",
        "causal_scenario",
        "reconciliation_case",
        "semantic_source_document",
        "regulatory_rule_version",
        "policy_rule",
        "predictive_validation_run",
        "audit_proof",
        "policy_decision",
        "control_assertion",
        "ledger_federation_link",
        "identity_credential",
        "resilience_drill",
        "crypto_key_epoch",
        "carbon_execution_window",
        "financial_model",
        "appgen_outbox_event",
        "appgen_inbox_event",
        "dead_letter_event",
    ),
    "apis": (
        "POST /gl/journal-events",
        "POST /gl/journals/validate",
        "GET /gl/projections",
        "GET /gl/trial-balance",
        "POST /gl/close-snapshots",
        "POST /gl/reconciliations",
        "POST /gl/policy-rules",
        "POST /gl/events/inbox",
        "GET /gl/audit-proof",
        "GET /gl/workbench",
    ),
    "emits": (
        "JournalPosted",
        "CloseSnapshotCreated",
        "ReconciliationSuggested",
        "PostingPolicyChanged",
        "LedgerProjectionBuilt",
    ),
    "consumes": (
        "InvoiceApproved",
        "PaymentCaptured",
        "PayrollPosted",
        "AssetDepreciated",
        "TaxCalculated",
    ),
    "template": "standalone_one_pbc_app",
    "ui_fragments": (
        "GeneralLedgerWorkbench",
        "JournalEntryConsole",
        "TrialBalanceView",
        "AccountProjectionExplorer",
        "CloseCommandCenter",
        "ReconciliationQueue",
        "PolicyRuleStudio",
        "LedgerParameterConsole",
        "LedgerConfigurationPanel",
        "AuditProofViewer",
        "ControlsDashboard",
    ),
    "permissions": (
        "gl_core.read",
        "gl_core.post",
        "gl_core.close",
        "gl_core.reconcile",
        "gl_core.audit",
        "gl_core.configure",
        "gl_core.event",
    ),
    "configuration": (
        "GL_CORE_DATABASE_URL",
        "GL_CORE_EVENT_TOPIC",
        "GL_CORE_RETRY_LIMIT",
        "GL_CORE_DEFAULT_CURRENCY",
        "GL_CORE_DEFAULT_TIMEZONE",
    ),
    "capabilities": (
        "gl_core.ledger_event_log",
        "gl_core.journal_entry",
        "gl_core.journal_line",
        "gl_core.ledger_account",
        "gl_core.accounting_period",
        "gl_core.ledger_projection",
        "gl_core.account_projection",
        "gl_core.consensus_replica",
        "gl_core.schema_extension",
        "gl_core.tenant_ledger_partition",
        "gl_core.probabilistic_posting",
        "gl_core.close_snapshot",
        "gl_core.causal_scenario",
        "gl_core.reconciliation_case",
        "gl_core.semantic_source_document",
        "gl_core.regulatory_rule_version",
        "gl_core.policy_rule",
        "gl_core.predictive_validation_run",
        "gl_core.audit_proof",
        "gl_core.policy_decision",
        "gl_core.control_assertion",
        "gl_core.ledger_federation_link",
        "gl_core.identity_credential",
        "gl_core.resilience_drill",
        "gl_core.crypto_key_epoch",
        "gl_core.carbon_execution_window",
        "gl_core.financial_model",
    ),
    "standard_features": (
        "configuration_schema",
        "rule_engine",
        "parameter_engine",
        "chart_of_accounts",
        "journal_entry",
        "journal_line_balancing",
        "posting_periods",
        "trial_balance",
        "ledger_projection",
        "account_reconciliation",
        "financial_statement_projection",
        "financial_statement_mapping",
        "period_close",
        "recurring_journals",
        "reversal_entries",
        "accruals_and_deferrals",
        "allocations",
        "consolidation",
        "retained_earnings_rollforward",
        "audit_trail",
        "approval_policy",
        "tax_and_reporting_dimensions",
        "segment_reporting",
        "statutory_reporting",
        "electronic_audit_file",
        "multi_entity_tenant_isolation",
        "currency_and_revaluation",
        "currency_translation",
        "intercompany_support",
        "subledger_integration",
        "budget_control",
        "attachments_and_source_documents",
        "idempotent_handlers",
        "retry_dead_letter",
        "permissions",
        "seed_data",
        "appgen_event_contract",
        "workbench",
    ),
    "workflows": (
        "configure_runtime",
        "set_parameter",
        "register_rule",
        "register_schema_extension",
        "plan_journal_draft",
        "append_ledger_event",
        "build_projection",
        "create_continuous_close_snapshot",
        "suggest_reconciliation",
        "receive_event",
        "generate_audit_proof",
        "build_workbench_view",
        "agent_assisted_adjustment",
    ),
    "analytics": (
        "trial_balance_variance",
        "close_readiness_score",
        "policy_exception_count",
        "reconciliation_confidence",
        "projection_freshness",
        "dead_letter_exceptions",
    ),
    "advanced_capabilities": (
        "event_sourced_ledger_core",
        "distributed_consensus_protocol",
        "schema_on_read_extensibility",
        "multi_tenant_isolation",
        "real_time_olap_oltp_convergence",
        "probabilistic_accounting_primitives",
        "continuous_close_architecture",
        "causal_inference_engine",
        "autonomous_reconciliation",
        "semantic_transaction_understanding",
        "regulatory_logic_compilation",
        "predictive_posting_validation",
        "zero_knowledge_audit_proofs",
        "dynamic_policy_enforcement",
        "immutable_regulatory_trail",
        "automated_control_testing",
        "universal_api_contract",
        "cross_system_ledger_federation",
        "event_driven_subledger_synchronization",
        "decentralized_identity_integration",
        "chaos_engineered_fault_tolerance",
        "quantum_resistant_cryptography",
        "carbon_aware_processing",
        "temporal_accounting_algebra",
        "homomorphic_encryption_for_consolidation",
        "game_theoretic_reconciliation",
        "information_theoretic_auditability",
        "formal_methods_ledger_invariants",
        "distributed_systems_runtime",
        "cryptographic_engineering",
        "financial_mlops",
    ),
    "migrations": ("migrations/001_initial.sql",),
    "seed_data": ("seed_data.py",),
    "tests": (
        "tests/test_contract.py",
        "tests/test_standalone.py",
    ),
    "docs": (
        "README.md",
        "SPECIFICATION.md",
        "implementation-plan.md",
        "implementation-status.md",
        "RELEASE_EVIDENCE.md",
    ),
}
