"""Manifest for the predictive_demand PBC."""

PBC_KEY = 'predictive_demand'

PREDICTIVE_DEMAND_TABLES = (
    "forecast_model",
    "forecast_run",
    "demand_signal",
    "forecast_result",
    "planning_horizon",
    "forecast_driver",
    "consensus_adjustment",
    "scenario_version",
    "shortage_risk",
    "replenishment_recommendation",
    "forecast_exception",
    "model_drift_signal",
    "planning_rule",
    "planning_parameter",
    "governed_model_evidence",
    "forecast_audit_proof",
)

PBC_MANIFEST = {
    "pbc": "predictive_demand",
    "label": "Predictive Demand Forecasting",
    "mesh": "intelligence",
    "description": "Time-series prediction for demand, depletion, cash flow, and resource constraints.",
    "datastore_backend": "postgresql",
    "tables": PREDICTIVE_DEMAND_TABLES,
    "apis": (
        "POST /forecast-models",
        "POST /forecast-runs",
        "POST /demand-signals",
        "POST /forecast-results",
        "POST /planning-horizons",
        "POST /forecast-drivers",
        "POST /consensus-adjustments",
        "POST /scenario-versions",
        "POST /shortage-risks",
        "POST /replenishment-recommendations",
        "POST /forecast-exceptions",
        "POST /forecast-exceptions/resolve",
        "POST /model-drift-signals",
        "POST /governed-model-evidence",
        "POST /forecast-audit-proofs",
        "POST /predictive-demand/events/inbox",
        "GET /forecast-results",
        "GET /predictive-demand/schema-contract",
        "GET /predictive-demand/service-contract",
        "GET /predictive-demand/release-evidence",
    ),
    "emits": ("ForecastUpdated", "MaterialShortageDetected"),
    "consumes": ("OperationalKpiChanged", "OrderShipped", "InventoryPoolChanged"),
    "template": None,
    "ui_fragments": ("PredictiveDemandWorkbench", "PredictiveDemandDetail"),
    "permissions": (
        "predictive_demand.read",
        "predictive_demand.create",
        "predictive_demand.update",
        "predictive_demand.approve",
        "predictive_demand.admin",
    ),
    "configuration": (
        "PREDICTIVE_DEMAND_DATABASE_URL",
        "PREDICTIVE_DEMAND_EVENT_TOPIC",
        "PREDICTIVE_DEMAND_RETRY_LIMIT",
    ),
    "capabilities": tuple(f"predictive_demand.{table}" for table in PREDICTIVE_DEMAND_TABLES),
    "standard_features": (
        "forecast_models",
        "forecast_runs",
        "demand_signals",
        "forecast_results",
        "planning_horizons",
        "forecast_drivers",
        "consensus_adjustments",
        "scenario_versions",
        "shortage_risks",
        "replenishment_recommendations",
        "forecast_exceptions",
        "model_drift_signals",
        "planning_rules",
        "planning_parameters",
        "governed_model_evidence",
        "forecast_audit_proofs",
        "shipment_projection",
        "inventory_pool_projection",
        "operational_kpi_projection",
        "baseline_forecast",
        "planner_overrides",
        "promotion_lift_controls",
        "seasonality_controls",
        "service_level_targets",
        "safety_stock_guidance",
        "shortage_detection",
        "inventory_coverage",
        "causal_drivers",
        "model_governance",
        "tenant_isolation",
        "appgen_x_outbox",
        "appgen_x_inbox",
        "idempotent_handlers",
        "retry_dead_letter_evidence",
        "permissions",
        "configuration_schema",
        "rule_engine",
        "parameter_engine",
        "seed_data",
        "schema_contract",
        "service_contract",
        "release_evidence",
        "workbench",
    ),
    "workflows": (
        "command_forecast_models",
        "command_forecast_runs",
        "command_demand_signals",
        "command_forecast_results",
        "command_planning_horizons",
        "command_forecast_drivers",
        "command_consensus_adjustments",
        "command_scenario_versions",
        "command_shortage_risks",
        "command_replenishment_recommendations",
        "command_forecast_exceptions",
        "command_model_drift_signals",
        "command_governed_model_evidence",
        "command_forecast_audit_proofs",
        "query_forecast_results",
    ),
    "analytics": (
        "prediction_quality",
        "drift_score",
        "decision_latency",
        "risk_precision",
        "forecast_updated_throughput",
        "material_shortage_detected_throughput",
    ),
    "advanced_capabilities": (
        "event_sourced_demand_signal_lifecycle",
        "owned_planning_schema_boundary",
        "multi_tenant_planning_isolation",
        "schema_evolution_resilient_demand_context",
        "forecast_model_registry",
        "demand_signal_ingestion",
        "event_driven_signal_projection",
        "forecast_run_orchestration",
        "forecast_result_publication",
        "inventory_shortage_detection",
        "consensus_demand_planning",
        "service_level_and_safety_stock_controls",
        "causal_driver_modeling",
        "promotion_and_override_adjustments",
        "probabilistic_forecast_banding",
        "counterfactual_scenario_simulation",
        "temporal_replenishment_forecasting",
        "autonomous_forecast_exception_resolution",
        "semantic_planning_rule_understanding",
        "predictive_material_constraint_risk",
        "self_healing_model_retraining",
        "cryptographic_forecast_proof",
        "immutable_planning_audit_trail",
        "dynamic_policy_screening",
        "automated_forecast_control_testing",
        "cross_system_order_inventory_operations_federation",
        "appgen_x_outbox_inbox_eventing",
        "idempotent_handlers",
        "retry_dead_letter_evidence",
        "permissions_governance_evidence",
        "configuration_schema",
        "parameter_engine",
        "rule_engine",
        "seed_data",
        "workbench_ui",
        "governed_model_evidence",
    ),
    "migrations": ("migrations/001_initial.sql",),
    "seed_data": ("seed_data.py",),
    "tests": ("tests/test_contract.py",),
    "docs": ("RELEASE_EVIDENCE.md",),
}
