"""Generated owned schema evidence for the predictive_demand PBC."""

SCHEMA_CONTRACT = {'format': 'appgen.predictive-demand-owned-schema-contract.v1',
 'ok': True,
 'tables': ({'logical_table': 'forecast_model',
             'owned_table': 'predictive_demand_forecast_model',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'model_id', 'type': 'string', 'required': True},
                        {'name': 'sku', 'type': 'string', 'required': True},
                        {'name': 'location', 'type': 'string', 'required': True},
                        {'name': 'algorithm', 'type': 'string', 'required': True},
                        {'name': 'version', 'type': 'integer', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'forecast_run',
             'owned_table': 'predictive_demand_forecast_run',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'run_id', 'type': 'string', 'required': True},
                        {'name': 'model_id', 'type': 'string', 'required': True},
                        {'name': 'sku', 'type': 'string', 'required': True},
                        {'name': 'location', 'type': 'string', 'required': True},
                        {'name': 'signal_count', 'type': 'integer', 'required': True},
                        {'name': 'forecast_quantity', 'type': 'string', 'required': True},
                        {'name': 'shortage_quantity', 'type': 'string', 'required': True},
                        {'name': 'confidence', 'type': 'decimal', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'demand_signal',
             'owned_table': 'predictive_demand_demand_signal',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'signal_id', 'type': 'string', 'required': True},
                        {'name': 'signal_type', 'type': 'string', 'required': True},
                        {'name': 'sku', 'type': 'string', 'required': True},
                        {'name': 'location', 'type': 'string', 'required': True},
                        {'name': 'region', 'type': 'string', 'required': True},
                        {'name': 'quantity', 'type': 'string', 'required': True},
                        {'name': 'source', 'type': 'string', 'required': True},
                        {'name': 'driver_weight', 'type': 'string', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'forecast_result',
             'owned_table': 'predictive_demand_forecast_result',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'result_id', 'type': 'string', 'required': True},
                        {'name': 'run_id', 'type': 'string', 'required': True},
                        {'name': 'model_id', 'type': 'string', 'required': True},
                        {'name': 'sku', 'type': 'string', 'required': True},
                        {'name': 'location', 'type': 'string', 'required': True},
                        {'name': 'forecast_quantity', 'type': 'string', 'required': True},
                        {'name': 'recommended_supply', 'type': 'string', 'required': True},
                        {'name': 'shortage_quantity', 'type': 'string', 'required': True},
                        {'name': 'confidence_band', 'type': 'decimal', 'required': True},
                        {'name': 'planning_action', 'type': 'string', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'planning_horizon',
             'owned_table': 'predictive_demand_planning_horizon',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'horizon_id', 'type': 'string', 'required': True},
                        {'name': 'sku', 'type': 'string', 'required': True},
                        {'name': 'location', 'type': 'string', 'required': True},
                        {'name': 'granularity', 'type': 'string', 'required': True},
                        {'name': 'starts_on', 'type': 'string', 'required': True},
                        {'name': 'ends_on', 'type': 'string', 'required': True},
                        {'name': 'freeze_window_days', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'forecast_driver',
             'owned_table': 'predictive_demand_forecast_driver',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'driver_id', 'type': 'string', 'required': True},
                        {'name': 'sku', 'type': 'string', 'required': True},
                        {'name': 'location', 'type': 'string', 'required': True},
                        {'name': 'driver_type', 'type': 'string', 'required': True},
                        {'name': 'driver_value', 'type': 'string', 'required': True},
                        {'name': 'weight', 'type': 'string', 'required': True},
                        {'name': 'source', 'type': 'string', 'required': True},
                        {'name': 'effective_on', 'type': 'string', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'consensus_adjustment',
             'owned_table': 'predictive_demand_consensus_adjustment',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'adjustment_id', 'type': 'string', 'required': True},
                        {'name': 'run_id', 'type': 'string', 'required': True},
                        {'name': 'planner_id', 'type': 'string', 'required': True},
                        {'name': 'adjustment_quantity', 'type': 'string', 'required': True},
                        {'name': 'reason_code', 'type': 'string', 'required': True},
                        {'name': 'approval_status', 'type': 'string', 'required': True},
                        {'name': 'policy_result', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'scenario_version',
             'owned_table': 'predictive_demand_scenario_version',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'scenario_id', 'type': 'string', 'required': True},
                        {'name': 'run_id', 'type': 'string', 'required': True},
                        {'name': 'scenario_name', 'type': 'string', 'required': True},
                        {'name': 'assumption_set', 'type': 'string', 'required': True},
                        {'name': 'forecast_quantity', 'type': 'string', 'required': True},
                        {'name': 'confidence', 'type': 'decimal', 'required': True},
                        {'name': 'selected', 'type': 'string', 'required': True},
                        {'name': 'created_by', 'type': 'string', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'shortage_risk',
             'owned_table': 'predictive_demand_shortage_risk',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'risk_id', 'type': 'string', 'required': True},
                        {'name': 'result_id', 'type': 'string', 'required': True},
                        {'name': 'sku', 'type': 'string', 'required': True},
                        {'name': 'location', 'type': 'string', 'required': True},
                        {'name': 'shortage_quantity', 'type': 'string', 'required': True},
                        {'name': 'risk_band', 'type': 'string', 'required': True},
                        {'name': 'material_constraint', 'type': 'string', 'required': True},
                        {'name': 'alert_due_on', 'type': 'string', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'replenishment_recommendation',
             'owned_table': 'predictive_demand_replenishment_recommendation',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'recommendation_id', 'type': 'string', 'required': True},
                        {'name': 'result_id', 'type': 'string', 'required': True},
                        {'name': 'sku', 'type': 'string', 'required': True},
                        {'name': 'location', 'type': 'string', 'required': True},
                        {'name': 'recommended_quantity', 'type': 'string', 'required': True},
                        {'name': 'recommended_date', 'type': 'datetime', 'required': True},
                        {'name': 'service_level_target', 'type': 'string', 'required': True},
                        {'name': 'action_status', 'type': 'string', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'forecast_exception',
             'owned_table': 'predictive_demand_forecast_exception',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'exception_id', 'type': 'string', 'required': True},
                        {'name': 'run_id', 'type': 'string', 'required': True},
                        {'name': 'exception_type', 'type': 'string', 'required': True},
                        {'name': 'severity', 'type': 'string', 'required': True},
                        {'name': 'detected_value', 'type': 'string', 'required': True},
                        {'name': 'threshold', 'type': 'decimal', 'required': True},
                        {'name': 'resolution_status', 'type': 'string', 'required': True},
                        {'name': 'assigned_to', 'type': 'string', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'model_drift_signal',
             'owned_table': 'predictive_demand_model_drift_signal',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'drift_id', 'type': 'string', 'required': True},
                        {'name': 'model_id', 'type': 'string', 'required': True},
                        {'name': 'metric_name', 'type': 'string', 'required': True},
                        {'name': 'metric_value', 'type': 'string', 'required': True},
                        {'name': 'threshold', 'type': 'decimal', 'required': True},
                        {'name': 'drift_band', 'type': 'string', 'required': True},
                        {'name': 'retrain_recommended', 'type': 'string', 'required': True},
                        {'name': 'observed_at', 'type': 'datetime', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'planning_rule',
             'owned_table': 'predictive_demand_planning_rule',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'rule_id', 'type': 'string', 'required': True},
                        {'name': 'scope', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'allowed_signal_types', 'type': 'string', 'required': True},
                        {'name': 'allowed_regions', 'type': 'string', 'required': True},
                        {'name': 'forecast_policy', 'type': 'string', 'required': True},
                        {'name': 'shortage_policy', 'type': 'string', 'required': True},
                        {'name': 'compiled_hash', 'type': 'string', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'planning_parameter',
             'owned_table': 'predictive_demand_planning_parameter',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'parameter_id', 'type': 'string', 'required': True},
                        {'name': 'name', 'type': 'string', 'required': True},
                        {'name': 'value', 'type': 'string', 'required': True},
                        {'name': 'bounds', 'type': 'string', 'required': True},
                        {'name': 'changed_by', 'type': 'string', 'required': True},
                        {'name': 'effective_from', 'type': 'datetime', 'required': True},
                        {'name': 'effective_to', 'type': 'string', 'required': True},
                        {'name': 'compiled_hash', 'type': 'string', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'governed_model_evidence',
             'owned_table': 'predictive_demand_governed_model_evidence',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'evidence_id', 'type': 'json', 'required': True},
                        {'name': 'model_id', 'type': 'string', 'required': True},
                        {'name': 'algorithm', 'type': 'string', 'required': True},
                        {'name': 'training_window', 'type': 'string', 'required': True},
                        {'name': 'validation_metrics', 'type': 'string', 'required': True},
                        {'name': 'approval_status', 'type': 'string', 'required': True},
                        {'name': 'approved_by', 'type': 'string', 'required': True},
                        {'name': 'approved_at', 'type': 'datetime', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'forecast_audit_proof',
             'owned_table': 'predictive_demand_forecast_audit_proof',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'proof_id', 'type': 'string', 'required': True},
                        {'name': 'entity_type', 'type': 'string', 'required': True},
                        {'name': 'entity_id', 'type': 'string', 'required': True},
                        {'name': 'proof_hash', 'type': 'string', 'required': True},
                        {'name': 'previous_hash', 'type': 'string', 'required': True},
                        {'name': 'signature', 'type': 'string', 'required': True},
                        {'name': 'control_assertions', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()}),
 'migrations': ('migrations/001_initial.sql',),
 'models': ({'class_name': 'PredictiveDemandForecastModel',
             'table': 'predictive_demand_forecast_model',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'model_id', 'type': 'string', 'required': True},
                        {'name': 'sku', 'type': 'string', 'required': True},
                        {'name': 'location', 'type': 'string', 'required': True},
                        {'name': 'algorithm', 'type': 'string', 'required': True},
                        {'name': 'version', 'type': 'integer', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'PredictiveDemandForecastRun',
             'table': 'predictive_demand_forecast_run',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'run_id', 'type': 'string', 'required': True},
                        {'name': 'model_id', 'type': 'string', 'required': True},
                        {'name': 'sku', 'type': 'string', 'required': True},
                        {'name': 'location', 'type': 'string', 'required': True},
                        {'name': 'signal_count', 'type': 'integer', 'required': True},
                        {'name': 'forecast_quantity', 'type': 'string', 'required': True},
                        {'name': 'shortage_quantity', 'type': 'string', 'required': True},
                        {'name': 'confidence', 'type': 'decimal', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'PredictiveDemandDemandSignal',
             'table': 'predictive_demand_demand_signal',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'signal_id', 'type': 'string', 'required': True},
                        {'name': 'signal_type', 'type': 'string', 'required': True},
                        {'name': 'sku', 'type': 'string', 'required': True},
                        {'name': 'location', 'type': 'string', 'required': True},
                        {'name': 'region', 'type': 'string', 'required': True},
                        {'name': 'quantity', 'type': 'string', 'required': True},
                        {'name': 'source', 'type': 'string', 'required': True},
                        {'name': 'driver_weight', 'type': 'string', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'PredictiveDemandForecastResult',
             'table': 'predictive_demand_forecast_result',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'result_id', 'type': 'string', 'required': True},
                        {'name': 'run_id', 'type': 'string', 'required': True},
                        {'name': 'model_id', 'type': 'string', 'required': True},
                        {'name': 'sku', 'type': 'string', 'required': True},
                        {'name': 'location', 'type': 'string', 'required': True},
                        {'name': 'forecast_quantity', 'type': 'string', 'required': True},
                        {'name': 'recommended_supply', 'type': 'string', 'required': True},
                        {'name': 'shortage_quantity', 'type': 'string', 'required': True},
                        {'name': 'confidence_band', 'type': 'decimal', 'required': True},
                        {'name': 'planning_action', 'type': 'string', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'PredictiveDemandPlanningHorizon',
             'table': 'predictive_demand_planning_horizon',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'horizon_id', 'type': 'string', 'required': True},
                        {'name': 'sku', 'type': 'string', 'required': True},
                        {'name': 'location', 'type': 'string', 'required': True},
                        {'name': 'granularity', 'type': 'string', 'required': True},
                        {'name': 'starts_on', 'type': 'string', 'required': True},
                        {'name': 'ends_on', 'type': 'string', 'required': True},
                        {'name': 'freeze_window_days', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'PredictiveDemandForecastDriver',
             'table': 'predictive_demand_forecast_driver',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'driver_id', 'type': 'string', 'required': True},
                        {'name': 'sku', 'type': 'string', 'required': True},
                        {'name': 'location', 'type': 'string', 'required': True},
                        {'name': 'driver_type', 'type': 'string', 'required': True},
                        {'name': 'driver_value', 'type': 'string', 'required': True},
                        {'name': 'weight', 'type': 'string', 'required': True},
                        {'name': 'source', 'type': 'string', 'required': True},
                        {'name': 'effective_on', 'type': 'string', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'PredictiveDemandConsensusAdjustment',
             'table': 'predictive_demand_consensus_adjustment',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'adjustment_id', 'type': 'string', 'required': True},
                        {'name': 'run_id', 'type': 'string', 'required': True},
                        {'name': 'planner_id', 'type': 'string', 'required': True},
                        {'name': 'adjustment_quantity', 'type': 'string', 'required': True},
                        {'name': 'reason_code', 'type': 'string', 'required': True},
                        {'name': 'approval_status', 'type': 'string', 'required': True},
                        {'name': 'policy_result', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'PredictiveDemandScenarioVersion',
             'table': 'predictive_demand_scenario_version',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'scenario_id', 'type': 'string', 'required': True},
                        {'name': 'run_id', 'type': 'string', 'required': True},
                        {'name': 'scenario_name', 'type': 'string', 'required': True},
                        {'name': 'assumption_set', 'type': 'string', 'required': True},
                        {'name': 'forecast_quantity', 'type': 'string', 'required': True},
                        {'name': 'confidence', 'type': 'decimal', 'required': True},
                        {'name': 'selected', 'type': 'string', 'required': True},
                        {'name': 'created_by', 'type': 'string', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'PredictiveDemandShortageRisk',
             'table': 'predictive_demand_shortage_risk',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'risk_id', 'type': 'string', 'required': True},
                        {'name': 'result_id', 'type': 'string', 'required': True},
                        {'name': 'sku', 'type': 'string', 'required': True},
                        {'name': 'location', 'type': 'string', 'required': True},
                        {'name': 'shortage_quantity', 'type': 'string', 'required': True},
                        {'name': 'risk_band', 'type': 'string', 'required': True},
                        {'name': 'material_constraint', 'type': 'string', 'required': True},
                        {'name': 'alert_due_on', 'type': 'string', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'PredictiveDemandReplenishmentRecommendation',
             'table': 'predictive_demand_replenishment_recommendation',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'recommendation_id', 'type': 'string', 'required': True},
                        {'name': 'result_id', 'type': 'string', 'required': True},
                        {'name': 'sku', 'type': 'string', 'required': True},
                        {'name': 'location', 'type': 'string', 'required': True},
                        {'name': 'recommended_quantity', 'type': 'string', 'required': True},
                        {'name': 'recommended_date', 'type': 'datetime', 'required': True},
                        {'name': 'service_level_target', 'type': 'string', 'required': True},
                        {'name': 'action_status', 'type': 'string', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'PredictiveDemandForecastException',
             'table': 'predictive_demand_forecast_exception',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'exception_id', 'type': 'string', 'required': True},
                        {'name': 'run_id', 'type': 'string', 'required': True},
                        {'name': 'exception_type', 'type': 'string', 'required': True},
                        {'name': 'severity', 'type': 'string', 'required': True},
                        {'name': 'detected_value', 'type': 'string', 'required': True},
                        {'name': 'threshold', 'type': 'decimal', 'required': True},
                        {'name': 'resolution_status', 'type': 'string', 'required': True},
                        {'name': 'assigned_to', 'type': 'string', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'PredictiveDemandModelDriftSignal',
             'table': 'predictive_demand_model_drift_signal',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'drift_id', 'type': 'string', 'required': True},
                        {'name': 'model_id', 'type': 'string', 'required': True},
                        {'name': 'metric_name', 'type': 'string', 'required': True},
                        {'name': 'metric_value', 'type': 'string', 'required': True},
                        {'name': 'threshold', 'type': 'decimal', 'required': True},
                        {'name': 'drift_band', 'type': 'string', 'required': True},
                        {'name': 'retrain_recommended', 'type': 'string', 'required': True},
                        {'name': 'observed_at', 'type': 'datetime', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'PredictiveDemandPlanningRule',
             'table': 'predictive_demand_planning_rule',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'rule_id', 'type': 'string', 'required': True},
                        {'name': 'scope', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'allowed_signal_types', 'type': 'string', 'required': True},
                        {'name': 'allowed_regions', 'type': 'string', 'required': True},
                        {'name': 'forecast_policy', 'type': 'string', 'required': True},
                        {'name': 'shortage_policy', 'type': 'string', 'required': True},
                        {'name': 'compiled_hash', 'type': 'string', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'PredictiveDemandPlanningParameter',
             'table': 'predictive_demand_planning_parameter',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'parameter_id', 'type': 'string', 'required': True},
                        {'name': 'name', 'type': 'string', 'required': True},
                        {'name': 'value', 'type': 'string', 'required': True},
                        {'name': 'bounds', 'type': 'string', 'required': True},
                        {'name': 'changed_by', 'type': 'string', 'required': True},
                        {'name': 'effective_from', 'type': 'datetime', 'required': True},
                        {'name': 'effective_to', 'type': 'string', 'required': True},
                        {'name': 'compiled_hash', 'type': 'string', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'PredictiveDemandGovernedModelEvidence',
             'table': 'predictive_demand_governed_model_evidence',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'evidence_id', 'type': 'json', 'required': True},
                        {'name': 'model_id', 'type': 'string', 'required': True},
                        {'name': 'algorithm', 'type': 'string', 'required': True},
                        {'name': 'training_window', 'type': 'string', 'required': True},
                        {'name': 'validation_metrics', 'type': 'string', 'required': True},
                        {'name': 'approval_status', 'type': 'string', 'required': True},
                        {'name': 'approved_by', 'type': 'string', 'required': True},
                        {'name': 'approved_at', 'type': 'datetime', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'PredictiveDemandForecastAuditProof',
             'table': 'predictive_demand_forecast_audit_proof',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'proof_id', 'type': 'string', 'required': True},
                        {'name': 'entity_type', 'type': 'string', 'required': True},
                        {'name': 'entity_id', 'type': 'string', 'required': True},
                        {'name': 'proof_hash', 'type': 'string', 'required': True},
                        {'name': 'previous_hash', 'type': 'string', 'required': True},
                        {'name': 'signature', 'type': 'string', 'required': True},
                        {'name': 'control_assertions', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'audit_proof', 'type': 'string', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()}),
 'datastore_backends': ('postgresql', 'mysql', 'mariadb'),
 'database_backends': ('postgresql', 'mysql', 'mariadb'),
 'shared_table_access': False,
 'pbc': 'predictive_demand',
 'owned_tables': ('predictive_demand_forecast_model',
                  'predictive_demand_forecast_run',
                  'predictive_demand_demand_signal',
                  'predictive_demand_forecast_result',
                  'predictive_demand_planning_horizon',
                  'predictive_demand_forecast_driver',
                  'predictive_demand_consensus_adjustment',
                  'predictive_demand_scenario_version',
                  'predictive_demand_shortage_risk',
                  'predictive_demand_replenishment_recommendation',
                  'predictive_demand_forecast_exception',
                  'predictive_demand_model_drift_signal',
                  'predictive_demand_planning_rule',
                  'predictive_demand_planning_parameter',
                  'predictive_demand_governed_model_evidence',
                  'predictive_demand_forecast_audit_proof')}


def build_schema_contract():
    """Return generated owned schema, migration, and model evidence."""
    return dict(SCHEMA_CONTRACT)


def validate_schema_contract():
    """Validate owned table, migration, model, and datastore evidence."""
    contract = build_schema_contract()
    pbc = contract['pbc']
    owned_tables = tuple(contract.get('owned_tables', ()))
    raw_model_tables = tuple(
        model.get('table')
        for model in contract.get('models', ())
        if isinstance(model, dict) and model.get('table')
    )
    model_tables = tuple(
        table if table.startswith(f'{pbc}_') else f'{pbc}_{table}'
        for table in raw_model_tables
    )
    migration_paths = tuple(contract.get('migrations', ()))
    allowed_backends = {'postgresql', 'mysql', 'mariadb'}
    invalid_tables = tuple(table for table in owned_tables if not table.startswith(f'{pbc}_'))
    missing_models = tuple(table for table in owned_tables if model_tables and table not in model_tables)
    invalid_backends = tuple(
        backend for backend in contract.get('database_backends', ()) if backend not in allowed_backends
    )
    return {
        'ok': contract.get('ok') is True
        and bool(owned_tables)
        and bool(migration_paths)
        and not invalid_tables
        and not missing_models
        and not invalid_backends
        and contract.get('shared_table_access') is False,
        'pbc': pbc,
        'owned_tables': owned_tables,
        'raw_model_tables': raw_model_tables,
        'model_tables': model_tables,
        'migration_paths': migration_paths,
        'invalid_tables': invalid_tables,
        'missing_models': missing_models,
        'invalid_backends': invalid_backends,
        'side_effects': (),
    }


def smoke_test():
    """Exercise schema validation side-effect-free."""
    return validate_schema_contract()
