"""Generated owned schema evidence for the cross_border_trade PBC."""

SCHEMA_CONTRACT = {'format': 'appgen.cross-border-trade-owned-schema-contract.v1',
 'ok': True,
 'tables': ({'logical_table': 'hs_classification',
             'owned_table': 'cross_border_trade_hs_classification',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'classification_id', 'type': 'string', 'required': True},
                        {'name': 'product_id', 'type': 'string', 'required': True},
                        {'name': 'description', 'type': 'string', 'required': True},
                        {'name': 'hs_code', 'type': 'string', 'required': True},
                        {'name': 'country_of_origin', 'type': 'string', 'required': True},
                        {'name': 'destination_country', 'type': 'string', 'required': True},
                        {'name': 'confidence', 'type': 'decimal', 'required': True},
                        {'name': 'review_required', 'type': 'string', 'required': True},
                        {'name': 'evidence_hash', 'type': 'json', 'required': True},
                        {'name': 'audit_evidence_hash', 'type': 'json', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'classification_id',
                                'target_table': 'cross_border_trade_landed_cost_quote',
                                'target_column': 'classification_id',
                                'cardinality': 'owned_reference',
                                'ownership': 'same_pbc'},
                               {'field': 'classification_id',
                                'target_table': 'cross_border_trade_export_control_check',
                                'target_column': 'classification_id',
                                'cardinality': 'owned_reference',
                                'ownership': 'same_pbc'})},
            {'logical_table': 'landed_cost_quote',
             'owned_table': 'cross_border_trade_landed_cost_quote',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'quote_id', 'type': 'string', 'required': True},
                        {'name': 'order_id', 'type': 'string', 'required': True},
                        {'name': 'classification_id', 'type': 'string', 'required': True},
                        {'name': 'incoterm', 'type': 'string', 'required': True},
                        {'name': 'origin_country', 'type': 'string', 'required': True},
                        {'name': 'destination_country', 'type': 'string', 'required': True},
                        {'name': 'goods_value', 'type': 'string', 'required': True},
                        {'name': 'shipping_cost', 'type': 'decimal', 'required': True},
                        {'name': 'duty', 'type': 'string', 'required': True},
                        {'name': 'tax', 'type': 'string', 'required': True},
                        {'name': 'insurance', 'type': 'string', 'required': True},
                        {'name': 'broker_fee', 'type': 'string', 'required': True},
                        {'name': 'landed_total', 'type': 'string', 'required': True},
                        {'name': 'currency', 'type': 'string', 'required': True},
                        {'name': 'evidence_hash', 'type': 'json', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'quote_id',
                                'target_table': 'cross_border_trade_customs_declaration',
                                'target_column': 'quote_id',
                                'cardinality': 'owned_reference',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'export_control_check',
             'owned_table': 'cross_border_trade_export_control_check',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'check_id', 'type': 'string', 'required': True},
                        {'name': 'order_id', 'type': 'string', 'required': True},
                        {'name': 'classification_id', 'type': 'string', 'required': True},
                        {'name': 'destination_country', 'type': 'string', 'required': True},
                        {'name': 'risk_score', 'type': 'decimal', 'required': True},
                        {'name': 'decision', 'type': 'string', 'required': True},
                        {'name': 'license_required', 'type': 'string', 'required': True},
                        {'name': 'denied_party_hits', 'type': 'string', 'required': True},
                        {'name': 'country_restriction_status', 'type': 'string', 'required': True},
                        {'name': 'compliance_hold', 'type': 'string', 'required': True},
                        {'name': 'evidence_hash', 'type': 'json', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'check_id',
                                'target_table': 'cross_border_trade_denied_party_screening',
                                'target_column': 'check_id',
                                'cardinality': 'owned_reference',
                                'ownership': 'same_pbc'},
                               {'field': 'check_id',
                                'target_table': 'cross_border_trade_customs_declaration',
                                'target_column': 'check_id',
                                'cardinality': 'owned_reference',
                                'ownership': 'same_pbc'})},
            {'logical_table': 'customs_declaration',
             'owned_table': 'cross_border_trade_customs_declaration',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'declaration_id', 'type': 'string', 'required': True},
                        {'name': 'order_id', 'type': 'string', 'required': True},
                        {'name': 'quote_id', 'type': 'string', 'required': True},
                        {'name': 'check_id', 'type': 'string', 'required': True},
                        {'name': 'document_packet_id', 'type': 'string', 'required': True},
                        {'name': 'broker_handoff_id', 'type': 'string', 'required': True},
                        {'name': 'carrier_handoff_id', 'type': 'string', 'required': True},
                        {'name': 'country_restriction_status', 'type': 'string', 'required': True},
                        {'name': 'compliance_hold', 'type': 'string', 'required': True},
                        {'name': 'customs_documents_complete', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'audit_evidence_hash', 'type': 'json', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'declaration_id',
                                'target_table': 'cross_border_trade_trade_document_packet',
                                'target_column': 'declaration_id',
                                'cardinality': 'owned_reference',
                                'ownership': 'same_pbc'},
                               {'field': 'declaration_id',
                                'target_table': 'cross_border_trade_broker_handoff',
                                'target_column': 'declaration_id',
                                'cardinality': 'owned_reference',
                                'ownership': 'same_pbc'},
                               {'field': 'declaration_id',
                                'target_table': 'cross_border_trade_carrier_handoff',
                                'target_column': 'declaration_id',
                                'cardinality': 'owned_reference',
                                'ownership': 'same_pbc'},
                               {'field': 'declaration_id',
                                'target_table': 'cross_border_trade_trade_compliance_hold',
                                'target_column': 'entity_id',
                                'cardinality': 'owned_reference',
                                'ownership': 'same_pbc'})},
            {'logical_table': 'denied_party_screening',
             'owned_table': 'cross_border_trade_denied_party_screening',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'screening_id', 'type': 'string', 'required': True},
                        {'name': 'check_id', 'type': 'string', 'required': True},
                        {'name': 'matches', 'type': 'string', 'required': True},
                        {'name': 'risk_score', 'type': 'decimal', 'required': True},
                        {'name': 'decision', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'trade_document_packet',
             'owned_table': 'cross_border_trade_trade_document_packet',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'packet_id', 'type': 'string', 'required': True},
                        {'name': 'declaration_id', 'type': 'string', 'required': True},
                        {'name': 'documents', 'type': 'string', 'required': True},
                        {'name': 'missing_documents', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'broker_handoff',
             'owned_table': 'cross_border_trade_broker_handoff',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'handoff_id', 'type': 'string', 'required': True},
                        {'name': 'declaration_id', 'type': 'string', 'required': True},
                        {'name': 'broker_id', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'submission_payload', 'type': 'json', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'carrier_handoff',
             'owned_table': 'cross_border_trade_carrier_handoff',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'handoff_id', 'type': 'string', 'required': True},
                        {'name': 'declaration_id', 'type': 'string', 'required': True},
                        {'name': 'order_id', 'type': 'string', 'required': True},
                        {'name': 'carrier_ref', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'trade_compliance_hold',
             'owned_table': 'cross_border_trade_trade_compliance_hold',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'hold_id', 'type': 'string', 'required': True},
                        {'name': 'entity_id', 'type': 'string', 'required': True},
                        {'name': 'reason', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'released_at', 'type': 'datetime', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'country_restriction_policy',
             'owned_table': 'cross_border_trade_country_restriction_policy',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'restriction_id', 'type': 'string', 'required': True},
                        {'name': 'destination_country', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'restriction_basis', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'trade_rule',
             'owned_table': 'cross_border_trade_trade_rule',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'rule_id', 'type': 'string', 'required': True},
                        {'name': 'scope', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'classification_policy', 'type': 'string', 'required': True},
                        {'name': 'landed_cost_policy', 'type': 'decimal', 'required': True},
                        {'name': 'export_control_policy', 'type': 'string', 'required': True},
                        {'name': 'declaration_policy', 'type': 'string', 'required': True},
                        {'name': 'compiled_hash', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'trade_parameter',
             'owned_table': 'cross_border_trade_trade_parameter',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'name', 'type': 'string', 'required': True},
                        {'name': 'value', 'type': 'string', 'required': True},
                        {'name': 'bounds', 'type': 'string', 'required': True},
                        {'name': 'compiled_hash', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'trade_configuration',
             'owned_table': 'cross_border_trade_trade_configuration',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'database_backend', 'type': 'string', 'required': True},
                        {'name': 'event_topic', 'type': 'string', 'required': True},
                        {'name': 'required_event_topic', 'type': 'string', 'required': True},
                        {'name': 'retry_limit', 'type': 'string', 'required': True},
                        {'name': 'default_currency', 'type': 'string', 'required': True},
                        {'name': 'supported_countries', 'type': 'string', 'required': True},
                        {'name': 'supported_incoterms', 'type': 'string', 'required': True},
                        {'name': 'workbench_limit', 'type': 'string', 'required': True},
                        {'name': 'configuration_hash', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'trade_schema_extension',
             'owned_table': 'cross_border_trade_trade_schema_extension',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'entity', 'type': 'string', 'required': True},
                        {'name': 'fields', 'type': 'string', 'required': True},
                        {'name': 'compatible', 'type': 'string', 'required': True},
                        {'name': 'migration', 'type': 'string', 'required': True},
                        {'name': 'projection_rebuild_required', 'type': 'string', 'required': True},
                        {'name': 'extension_hash', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'trade_audit_evidence',
             'owned_table': 'cross_border_trade_trade_audit_evidence',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'artifact_type', 'type': 'string', 'required': True},
                        {'name': 'artifact_id', 'type': 'string', 'required': True},
                        {'name': 'hash', 'type': 'string', 'required': True},
                        {'name': 'captured_at', 'type': 'datetime', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'appgen_outbox_event',
             'owned_table': 'cross_border_trade_appgen_outbox_event',
             'fields': ({'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'event_id', 'type': 'string', 'required': True},
                        {'name': 'event_type', 'type': 'string', 'required': True},
                        {'name': 'aggregate_id', 'type': 'string', 'required': True},
                        {'name': 'topic', 'type': 'string', 'required': True},
                        {'name': 'event_contract', 'type': 'string', 'required': True},
                        {'name': 'idempotency_key', 'type': 'string', 'required': True},
                        {'name': 'payload_hash', 'type': 'json', 'required': True},
                        {'name': 'payload', 'type': 'json', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'appgen_inbox_event',
             'owned_table': 'cross_border_trade_appgen_inbox_event',
             'fields': ({'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'event_id', 'type': 'string', 'required': True},
                        {'name': 'event_type', 'type': 'string', 'required': True},
                        {'name': 'idempotency_key', 'type': 'string', 'required': True},
                        {'name': 'payload_hash', 'type': 'json', 'required': True},
                        {'name': 'handled', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'dead_letter_event',
             'owned_table': 'cross_border_trade_dead_letter_event',
             'fields': ({'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'event_id', 'type': 'string', 'required': True},
                        {'name': 'event_type', 'type': 'string', 'required': True},
                        {'name': 'idempotency_key', 'type': 'string', 'required': True},
                        {'name': 'attempts', 'type': 'integer', 'required': True},
                        {'name': 'reason', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()}),
 'migrations': ('migrations/001_initial.sql',),
 'models': ({'class_name': 'CrossBorderTradeHsClassification',
             'table': 'cross_border_trade_hs_classification',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'classification_id', 'type': 'string', 'required': True},
                        {'name': 'product_id', 'type': 'string', 'required': True},
                        {'name': 'description', 'type': 'string', 'required': True},
                        {'name': 'hs_code', 'type': 'string', 'required': True},
                        {'name': 'country_of_origin', 'type': 'string', 'required': True},
                        {'name': 'destination_country', 'type': 'string', 'required': True},
                        {'name': 'confidence', 'type': 'decimal', 'required': True},
                        {'name': 'review_required', 'type': 'string', 'required': True},
                        {'name': 'evidence_hash', 'type': 'json', 'required': True},
                        {'name': 'audit_evidence_hash', 'type': 'json', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'classification_id',
                                'target_table': 'cross_border_trade_landed_cost_quote',
                                'target_column': 'classification_id',
                                'cardinality': 'owned_reference',
                                'ownership': 'same_pbc'},
                               {'field': 'classification_id',
                                'target_table': 'cross_border_trade_export_control_check',
                                'target_column': 'classification_id',
                                'cardinality': 'owned_reference',
                                'ownership': 'same_pbc'})},
            {'class_name': 'CrossBorderTradeLandedCostQuote',
             'table': 'cross_border_trade_landed_cost_quote',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'quote_id', 'type': 'string', 'required': True},
                        {'name': 'order_id', 'type': 'string', 'required': True},
                        {'name': 'classification_id', 'type': 'string', 'required': True},
                        {'name': 'incoterm', 'type': 'string', 'required': True},
                        {'name': 'origin_country', 'type': 'string', 'required': True},
                        {'name': 'destination_country', 'type': 'string', 'required': True},
                        {'name': 'goods_value', 'type': 'string', 'required': True},
                        {'name': 'shipping_cost', 'type': 'decimal', 'required': True},
                        {'name': 'duty', 'type': 'string', 'required': True},
                        {'name': 'tax', 'type': 'string', 'required': True},
                        {'name': 'insurance', 'type': 'string', 'required': True},
                        {'name': 'broker_fee', 'type': 'string', 'required': True},
                        {'name': 'landed_total', 'type': 'string', 'required': True},
                        {'name': 'currency', 'type': 'string', 'required': True},
                        {'name': 'evidence_hash', 'type': 'json', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'quote_id',
                                'target_table': 'cross_border_trade_customs_declaration',
                                'target_column': 'quote_id',
                                'cardinality': 'owned_reference',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'CrossBorderTradeExportControlCheck',
             'table': 'cross_border_trade_export_control_check',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'check_id', 'type': 'string', 'required': True},
                        {'name': 'order_id', 'type': 'string', 'required': True},
                        {'name': 'classification_id', 'type': 'string', 'required': True},
                        {'name': 'destination_country', 'type': 'string', 'required': True},
                        {'name': 'risk_score', 'type': 'decimal', 'required': True},
                        {'name': 'decision', 'type': 'string', 'required': True},
                        {'name': 'license_required', 'type': 'string', 'required': True},
                        {'name': 'denied_party_hits', 'type': 'string', 'required': True},
                        {'name': 'country_restriction_status', 'type': 'string', 'required': True},
                        {'name': 'compliance_hold', 'type': 'string', 'required': True},
                        {'name': 'evidence_hash', 'type': 'json', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'check_id',
                                'target_table': 'cross_border_trade_denied_party_screening',
                                'target_column': 'check_id',
                                'cardinality': 'owned_reference',
                                'ownership': 'same_pbc'},
                               {'field': 'check_id',
                                'target_table': 'cross_border_trade_customs_declaration',
                                'target_column': 'check_id',
                                'cardinality': 'owned_reference',
                                'ownership': 'same_pbc'})},
            {'class_name': 'CrossBorderTradeCustomsDeclaration',
             'table': 'cross_border_trade_customs_declaration',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'declaration_id', 'type': 'string', 'required': True},
                        {'name': 'order_id', 'type': 'string', 'required': True},
                        {'name': 'quote_id', 'type': 'string', 'required': True},
                        {'name': 'check_id', 'type': 'string', 'required': True},
                        {'name': 'document_packet_id', 'type': 'string', 'required': True},
                        {'name': 'broker_handoff_id', 'type': 'string', 'required': True},
                        {'name': 'carrier_handoff_id', 'type': 'string', 'required': True},
                        {'name': 'country_restriction_status', 'type': 'string', 'required': True},
                        {'name': 'compliance_hold', 'type': 'string', 'required': True},
                        {'name': 'customs_documents_complete', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'audit_evidence_hash', 'type': 'json', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'declaration_id',
                                'target_table': 'cross_border_trade_trade_document_packet',
                                'target_column': 'declaration_id',
                                'cardinality': 'owned_reference',
                                'ownership': 'same_pbc'},
                               {'field': 'declaration_id',
                                'target_table': 'cross_border_trade_broker_handoff',
                                'target_column': 'declaration_id',
                                'cardinality': 'owned_reference',
                                'ownership': 'same_pbc'},
                               {'field': 'declaration_id',
                                'target_table': 'cross_border_trade_carrier_handoff',
                                'target_column': 'declaration_id',
                                'cardinality': 'owned_reference',
                                'ownership': 'same_pbc'},
                               {'field': 'declaration_id',
                                'target_table': 'cross_border_trade_trade_compliance_hold',
                                'target_column': 'entity_id',
                                'cardinality': 'owned_reference',
                                'ownership': 'same_pbc'})},
            {'class_name': 'CrossBorderTradeDeniedPartyScreening',
             'table': 'cross_border_trade_denied_party_screening',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'screening_id', 'type': 'string', 'required': True},
                        {'name': 'check_id', 'type': 'string', 'required': True},
                        {'name': 'matches', 'type': 'string', 'required': True},
                        {'name': 'risk_score', 'type': 'decimal', 'required': True},
                        {'name': 'decision', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'CrossBorderTradeTradeDocumentPacket',
             'table': 'cross_border_trade_trade_document_packet',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'packet_id', 'type': 'string', 'required': True},
                        {'name': 'declaration_id', 'type': 'string', 'required': True},
                        {'name': 'documents', 'type': 'string', 'required': True},
                        {'name': 'missing_documents', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'CrossBorderTradeBrokerHandoff',
             'table': 'cross_border_trade_broker_handoff',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'handoff_id', 'type': 'string', 'required': True},
                        {'name': 'declaration_id', 'type': 'string', 'required': True},
                        {'name': 'broker_id', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'submission_payload', 'type': 'json', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'CrossBorderTradeCarrierHandoff',
             'table': 'cross_border_trade_carrier_handoff',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'handoff_id', 'type': 'string', 'required': True},
                        {'name': 'declaration_id', 'type': 'string', 'required': True},
                        {'name': 'order_id', 'type': 'string', 'required': True},
                        {'name': 'carrier_ref', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'CrossBorderTradeTradeComplianceHold',
             'table': 'cross_border_trade_trade_compliance_hold',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'hold_id', 'type': 'string', 'required': True},
                        {'name': 'entity_id', 'type': 'string', 'required': True},
                        {'name': 'reason', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'released_at', 'type': 'datetime', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'CrossBorderTradeCountryRestrictionPolicy',
             'table': 'cross_border_trade_country_restriction_policy',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'restriction_id', 'type': 'string', 'required': True},
                        {'name': 'destination_country', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'restriction_basis', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'CrossBorderTradeTradeRule',
             'table': 'cross_border_trade_trade_rule',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'rule_id', 'type': 'string', 'required': True},
                        {'name': 'scope', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'classification_policy', 'type': 'string', 'required': True},
                        {'name': 'landed_cost_policy', 'type': 'decimal', 'required': True},
                        {'name': 'export_control_policy', 'type': 'string', 'required': True},
                        {'name': 'declaration_policy', 'type': 'string', 'required': True},
                        {'name': 'compiled_hash', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'CrossBorderTradeTradeParameter',
             'table': 'cross_border_trade_trade_parameter',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'name', 'type': 'string', 'required': True},
                        {'name': 'value', 'type': 'string', 'required': True},
                        {'name': 'bounds', 'type': 'string', 'required': True},
                        {'name': 'compiled_hash', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'CrossBorderTradeTradeConfiguration',
             'table': 'cross_border_trade_trade_configuration',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'database_backend', 'type': 'string', 'required': True},
                        {'name': 'event_topic', 'type': 'string', 'required': True},
                        {'name': 'required_event_topic', 'type': 'string', 'required': True},
                        {'name': 'retry_limit', 'type': 'string', 'required': True},
                        {'name': 'default_currency', 'type': 'string', 'required': True},
                        {'name': 'supported_countries', 'type': 'string', 'required': True},
                        {'name': 'supported_incoterms', 'type': 'string', 'required': True},
                        {'name': 'workbench_limit', 'type': 'string', 'required': True},
                        {'name': 'configuration_hash', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'CrossBorderTradeTradeSchemaExtension',
             'table': 'cross_border_trade_trade_schema_extension',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'entity', 'type': 'string', 'required': True},
                        {'name': 'fields', 'type': 'string', 'required': True},
                        {'name': 'compatible', 'type': 'string', 'required': True},
                        {'name': 'migration', 'type': 'string', 'required': True},
                        {'name': 'projection_rebuild_required', 'type': 'string', 'required': True},
                        {'name': 'extension_hash', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'CrossBorderTradeTradeAuditEvidence',
             'table': 'cross_border_trade_trade_audit_evidence',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'artifact_type', 'type': 'string', 'required': True},
                        {'name': 'artifact_id', 'type': 'string', 'required': True},
                        {'name': 'hash', 'type': 'string', 'required': True},
                        {'name': 'captured_at', 'type': 'datetime', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'CrossBorderTradeAppgenOutboxEvent',
             'table': 'cross_border_trade_appgen_outbox_event',
             'fields': ({'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'event_id', 'type': 'string', 'required': True},
                        {'name': 'event_type', 'type': 'string', 'required': True},
                        {'name': 'aggregate_id', 'type': 'string', 'required': True},
                        {'name': 'topic', 'type': 'string', 'required': True},
                        {'name': 'event_contract', 'type': 'string', 'required': True},
                        {'name': 'idempotency_key', 'type': 'string', 'required': True},
                        {'name': 'payload_hash', 'type': 'json', 'required': True},
                        {'name': 'payload', 'type': 'json', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'CrossBorderTradeAppgenInboxEvent',
             'table': 'cross_border_trade_appgen_inbox_event',
             'fields': ({'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'event_id', 'type': 'string', 'required': True},
                        {'name': 'event_type', 'type': 'string', 'required': True},
                        {'name': 'idempotency_key', 'type': 'string', 'required': True},
                        {'name': 'payload_hash', 'type': 'json', 'required': True},
                        {'name': 'handled', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'CrossBorderTradeDeadLetterEvent',
             'table': 'cross_border_trade_dead_letter_event',
             'fields': ({'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'event_id', 'type': 'string', 'required': True},
                        {'name': 'event_type', 'type': 'string', 'required': True},
                        {'name': 'idempotency_key', 'type': 'string', 'required': True},
                        {'name': 'attempts', 'type': 'integer', 'required': True},
                        {'name': 'reason', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()}),
 'datastore_backends': ('postgresql', 'mysql', 'mariadb'),
 'database_backends': ('postgresql', 'mysql', 'mariadb'),
 'shared_table_access': False,
 'pbc': 'cross_border_trade',
 'owned_tables': ('cross_border_trade_hs_classification',
                  'cross_border_trade_landed_cost_quote',
                  'cross_border_trade_export_control_check',
                  'cross_border_trade_customs_declaration',
                  'cross_border_trade_denied_party_screening',
                  'cross_border_trade_trade_document_packet',
                  'cross_border_trade_broker_handoff',
                  'cross_border_trade_carrier_handoff',
                  'cross_border_trade_trade_compliance_hold',
                  'cross_border_trade_country_restriction_policy',
                  'cross_border_trade_trade_rule',
                  'cross_border_trade_trade_parameter',
                  'cross_border_trade_trade_configuration',
                  'cross_border_trade_trade_schema_extension',
                  'cross_border_trade_trade_audit_evidence',
                  'cross_border_trade_appgen_outbox_event',
                  'cross_border_trade_appgen_inbox_event',
                  'cross_border_trade_dead_letter_event')}


def build_schema_contract():
    """Return generated owned schema, migration, and model evidence."""
    return dict(SCHEMA_CONTRACT)


def validate_schema_contract():
    """Validate owned table, migration, model, and datastore evidence."""
    contract = build_schema_contract()
    pbc = contract['pbc']
    owned_tables = tuple(contract.get('owned_tables', ()))
    raw_model_tables = tuple(
        model.get('table')
        for model in contract.get('models', ())
        if isinstance(model, dict) and model.get('table')
    )
    model_tables = tuple(
        table if table.startswith(f'{pbc}_') else f'{pbc}_{table}'
        for table in raw_model_tables
    )
    migration_paths = tuple(contract.get('migrations', ()))
    allowed_backends = {'postgresql', 'mysql', 'mariadb'}
    invalid_tables = tuple(table for table in owned_tables if not table.startswith(f'{pbc}_'))
    missing_models = tuple(table for table in owned_tables if model_tables and table not in model_tables)
    invalid_backends = tuple(
        backend for backend in contract.get('database_backends', ()) if backend not in allowed_backends
    )
    return {
        'ok': contract.get('ok') is True
        and bool(owned_tables)
        and bool(migration_paths)
        and not invalid_tables
        and not missing_models
        and not invalid_backends
        and contract.get('shared_table_access') is False,
        'pbc': pbc,
        'owned_tables': owned_tables,
        'raw_model_tables': raw_model_tables,
        'model_tables': model_tables,
        'migration_paths': migration_paths,
        'invalid_tables': invalid_tables,
        'missing_models': missing_models,
        'invalid_backends': invalid_backends,
        'side_effects': (),
    }


def smoke_test():
    """Exercise schema validation side-effect-free."""
    return validate_schema_contract()
