"""Generated owned schema evidence for the field_service_management PBC."""

SCHEMA_CONTRACT = {'format': 'appgen.field-service-management-owned-schema-contract.v1',
 'ok': True,
 'tables': ({'logical_table': 'field_work_order',
             'owned_table': 'field_service_management_field_work_order',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'dispatch_assignment',
             'owned_table': 'field_service_management_dispatch_assignment',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'field_work_order_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'field_service_management_field_work_order.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'field_work_order_id',
                                'target_table': 'field_service_management_field_work_order',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'technician_profile',
             'owned_table': 'field_service_management_technician_profile',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'field_work_order_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'field_service_management_field_work_order.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'field_work_order_id',
                                'target_table': 'field_service_management_field_work_order',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'mobile_task',
             'owned_table': 'field_service_management_mobile_task',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'field_work_order_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'field_service_management_field_work_order.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'field_work_order_id',
                                'target_table': 'field_service_management_field_work_order',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'parts_usage',
             'owned_table': 'field_service_management_parts_usage',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'field_work_order_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'field_service_management_field_work_order.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'field_work_order_id',
                                'target_table': 'field_service_management_field_work_order',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'service_sla',
             'owned_table': 'field_service_management_service_sla',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'field_work_order_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'field_service_management_field_work_order.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'field_work_order_id',
                                'target_table': 'field_service_management_field_work_order',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'service_history',
             'owned_table': 'field_service_management_service_history',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'field_work_order_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'field_service_management_field_work_order.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'field_work_order_id',
                                'target_table': 'field_service_management_field_work_order',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'customer_service_update',
             'owned_table': 'field_service_management_customer_service_update',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'field_work_order_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'field_service_management_field_work_order.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'field_work_order_id',
                                'target_table': 'field_service_management_field_work_order',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'appgen_outbox_event',
             'owned_table': 'field_service_management_appgen_outbox_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'field_work_order_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'field_service_management_field_work_order.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'appgen_inbox_event',
             'owned_table': 'field_service_management_appgen_inbox_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'field_work_order_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'field_service_management_field_work_order.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'appgen_dead_letter_event',
             'owned_table': 'field_service_management_appgen_dead_letter_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'field_work_order_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'field_service_management_field_work_order.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()}),
 'migrations': ('migrations/001_initial.sql',),
 'models': ({'class_name': 'FieldServiceManagementFieldWorkOrder',
             'table': 'field_service_management_field_work_order',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'FieldServiceManagementDispatchAssignment',
             'table': 'field_service_management_dispatch_assignment',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'field_work_order_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'field_service_management_field_work_order.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'field_work_order_id',
                                'target_table': 'field_service_management_field_work_order',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'FieldServiceManagementTechnicianProfile',
             'table': 'field_service_management_technician_profile',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'field_work_order_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'field_service_management_field_work_order.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'field_work_order_id',
                                'target_table': 'field_service_management_field_work_order',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'FieldServiceManagementMobileTask',
             'table': 'field_service_management_mobile_task',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'field_work_order_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'field_service_management_field_work_order.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'field_work_order_id',
                                'target_table': 'field_service_management_field_work_order',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'FieldServiceManagementPartsUsage',
             'table': 'field_service_management_parts_usage',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'field_work_order_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'field_service_management_field_work_order.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'field_work_order_id',
                                'target_table': 'field_service_management_field_work_order',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'FieldServiceManagementServiceSla',
             'table': 'field_service_management_service_sla',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'field_work_order_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'field_service_management_field_work_order.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'field_work_order_id',
                                'target_table': 'field_service_management_field_work_order',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'FieldServiceManagementServiceHistory',
             'table': 'field_service_management_service_history',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'field_work_order_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'field_service_management_field_work_order.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'field_work_order_id',
                                'target_table': 'field_service_management_field_work_order',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'FieldServiceManagementCustomerServiceUpdate',
             'table': 'field_service_management_customer_service_update',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'field_work_order_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'field_service_management_field_work_order.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'field_work_order_id',
                                'target_table': 'field_service_management_field_work_order',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'FieldServiceManagementAppgenOutboxEvent',
             'table': 'field_service_management_appgen_outbox_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'field_work_order_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'field_service_management_field_work_order.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'FieldServiceManagementAppgenInboxEvent',
             'table': 'field_service_management_appgen_inbox_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'field_work_order_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'field_service_management_field_work_order.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'FieldServiceManagementAppgenDeadLetterEvent',
             'table': 'field_service_management_appgen_dead_letter_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'field_work_order_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'field_service_management_field_work_order.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()}),
 'datastore_backends': ('postgresql', 'mysql', 'mariadb'),
 'database_backends': ('postgresql', 'mysql', 'mariadb'),
 'shared_table_access': False,
 'pbc': 'field_service_management',
 'owned_tables': ('field_service_management_field_work_order',
                  'field_service_management_dispatch_assignment',
                  'field_service_management_technician_profile',
                  'field_service_management_mobile_task',
                  'field_service_management_parts_usage',
                  'field_service_management_service_sla',
                  'field_service_management_service_history',
                  'field_service_management_customer_service_update',
                  'field_service_management_appgen_outbox_event',
                  'field_service_management_appgen_inbox_event',
                  'field_service_management_appgen_dead_letter_event')}


def build_schema_contract():
    """Return generated owned schema, migration, and model evidence."""
    return dict(SCHEMA_CONTRACT)


def validate_schema_contract():
    contract = build_schema_contract()
    pbc = contract['pbc']
    owned_tables = tuple(contract.get('owned_tables', ()))
    model_tables = tuple(model['table'] for model in contract.get('models', ()))
    allowed_backends = {'postgresql', 'mysql', 'mariadb'}
    invalid_backends = tuple(backend for backend in contract.get('database_backends', ()) if backend not in allowed_backends)
    missing_models = tuple(table for table in owned_tables if table not in model_tables)
    invalid_tables = tuple(table for table in owned_tables if not table.startswith(f'{pbc}_'))
    return {'ok': contract.get('ok') is True and bool(owned_tables) and bool(contract.get('migrations')) and not invalid_tables and not missing_models and not invalid_backends and contract.get('shared_table_access') is False, 'pbc': pbc, 'owned_tables': owned_tables, 'model_tables': model_tables, 'migration_paths': tuple(contract.get('migrations', ())), 'invalid_tables': invalid_tables, 'missing_models': missing_models, 'invalid_backends': invalid_backends, 'side_effects': ()}


def smoke_test():
    return validate_schema_contract()
