"""Executable improve1 capability registry for this PBC.

This module turns the package-local improve1 backlog into code-level evidence.
It is intentionally side-effect free: callers can inspect capability coverage, plan
execution, and verify surface mappings without touching external systems.
"""

from __future__ import annotations

from dataclasses import dataclass

PBC_KEY = 'capital_projects_delivery'


@dataclass(frozen=True)
class Improve1Capability:
    feature_number: int
    title: str
    slug: str
    domain_tags: tuple[str, ...]
    model_artifacts: tuple[str, ...]
    ui_artifacts: tuple[str, ...]
    service_artifacts: tuple[str, ...]
    test_artifacts: tuple[str, ...]
    evidence_artifacts: tuple[str, ...]
    configurable: bool = True
    agent_assisted: bool = True
    side_effect_free_plan: bool = True

    def as_traceability_row(self) -> dict:
        return {
            "feature_number": self.feature_number,
            "title": self.title,
            "slug": self.slug,
            "domain_tags": self.domain_tags,
            "code_artifact_model": self.model_artifacts,
            "ui_surface": self.ui_artifacts,
            "service_api": self.service_artifacts,
            "test": self.test_artifacts,
            "evidence": self.evidence_artifacts,
            "configurable": self.configurable,
            "agent_assisted": self.agent_assisted,
            "side_effect_free_plan": self.side_effect_free_plan,
        }



IMPROVE1_CAPABILITIES: tuple[Improve1Capability, ...] = (
    Improve1Capability(
        feature_number=1,
        title='Stage-gate lifecycle aligned to capital project phases',
        slug='stage_gate_lifecycle_aligned_to_capital_project_phases',
        domain_tags=('project',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=2,
        title='Work breakdown structure as a governed hierarchy',
        slug='work_breakdown_structure_as_a_governed_hierarchy',
        domain_tags=('breakdown', 'structure', 'governed'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=3,
        title='Estimate class and basis-of-estimate control',
        slug='estimate_class_and_basis_of_estimate_control',
        domain_tags=('estimate', 'class', 'basis_of_estimate'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=4,
        title='Baseline schedule governance with critical path traceability',
        slug='baseline_schedule_governance_with_critical_path_traceability',
        domain_tags=('governance', 'schedule', 'traceability'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=5,
        title='Milestone library for engineering, procurement, construction, and startup',
        slug='milestone_library_for_engineering_procurement_construction_and_startup',
        domain_tags=('milestone', 'library', 'engineering'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=6,
        title='Package-level commitment, accrual, and forecast control',
        slug='package_level_commitment_accrual_and_forecast_control',
        domain_tags=('forecast',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=7,
        title='Earned progress rules tied to measurable work',
        slug='earned_progress_rules_tied_to_measurable_work',
        domain_tags=('earned', 'progress', 'rules'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=8,
        title='Schedule and cost performance index tracking',
        slug='schedule_and_cost_performance_index_tracking',
        domain_tags=('schedule',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=9,
        title='Change order pipeline from field cause to approved recovery plan',
        slug='change_order_pipeline_from_field_cause_to_approved_recovery_plan',
        domain_tags=('change', 'order', 'pipeline'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=10,
        title='Early warning and claims avoidance register',
        slug='early_warning_and_claims_avoidance_register',
        domain_tags=('claim',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=11,
        title='Risk register with quantitative exposure and trigger logic',
        slug='risk_register_with_quantitative_exposure_and_trigger_logic',
        domain_tags=('risk',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=12,
        title='Opportunity management alongside threats',
        slug='opportunity_management_alongside_threats',
        domain_tags=('opportunity', 'management', 'alongside'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=13,
        title='Permit dependency matrix by authority and workfront',
        slug='permit_dependency_matrix_by_authority_and_workfront',
        domain_tags=('permit', 'dependency', 'matrix'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=14,
        title='Long-lead equipment tracking through procurement and site readiness',
        slug='long_lead_equipment_tracking_through_procurement_and_site_readiness',
        domain_tags=('long_lead', 'equipment', 'tracking'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=15,
        title='Contractor package readiness before notice to proceed',
        slug='contractor_package_readiness_before_notice_to_proceed',
        domain_tags=('contract',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=16,
        title='Field constraint log tied to package and area',
        slug='field_constraint_log_tied_to_package_and_area',
        domain_tags=('field', 'constraint', 'package'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=17,
        title='Interface management across EPC packages',
        slug='interface_management_across_epc_packages',
        domain_tags=('interface', 'management', 'across'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=18,
        title='Mechanical completion by system and subsystem',
        slug='mechanical_completion_by_system_and_subsystem',
        domain_tags=('mechanical', 'completion', 'system'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=19,
        title='Punch list severity and closeout thresholds',
        slug='punch_list_severity_and_closeout_thresholds',
        domain_tags=('close',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=20,
        title='Pre-commissioning activity tracking',
        slug='pre_commissioning_activity_tracking',
        domain_tags=('pre_commissioning', 'activity', 'tracking'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=21,
        title='Commissioning sequence and startup window control',
        slug='commissioning_sequence_and_startup_window_control',
        domain_tags=('commissioning', 'sequence', 'startup'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=22,
        title='Handover dossier completeness before owner acceptance',
        slug='handover_dossier_completeness_before_owner_acceptance',
        domain_tags=('handover', 'dossier', 'completeness'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=23,
        title='Defect liability and post-handover obligation tracking',
        slug='defect_liability_and_post_handover_obligation_tracking',
        domain_tags=('defect', 'liability', 'post_handover'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=24,
        title='Funding approval and appropriation checkpoints',
        slug='funding_approval_and_appropriation_checkpoints',
        domain_tags=('approval',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=25,
        title='Contingency drawdown discipline',
        slug='contingency_drawdown_discipline',
        domain_tags=('contingency', 'drawdown', 'discipline'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=26,
        title='Resource and productivity risk tracking',
        slug='resource_and_productivity_risk_tracking',
        domain_tags=('risk',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=27,
        title='Weather and seasonal disruption modeling',
        slug='weather_and_seasonal_disruption_modeling',
        domain_tags=('model',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=28,
        title='Quality hold-point and release boundary management',
        slug='quality_hold_point_and_release_boundary_management',
        domain_tags=('quality',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=29,
        title='Construction sequence of work visualization in the workbench',
        slug='construction_sequence_of_work_visualization_in_the_workbench',
        domain_tags=('construction', 'sequence', 'visualization'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=30,
        title='Monthly project review pack generation',
        slug='monthly_project_review_pack_generation',
        domain_tags=('project',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=31,
        title='Release evidence tailored to capital project readiness',
        slug='release_evidence_tailored_to_capital_project_readiness',
        domain_tags=('project',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=32,
        title='Assistant skills for project controls roles',
        slug='assistant_skills_for_project_controls_roles',
        domain_tags=('project',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=33,
        title='Document instruction intake for contractor and owner artifacts',
        slug='document_instruction_intake_for_contractor_and_owner_artifacts',
        domain_tags=('contract', 'document'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=34,
        title='Event boundary refinement for lifecycle and control decisions',
        slug='event_boundary_refinement_for_lifecycle_and_control_decisions',
        domain_tags=('event',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=35,
        title='Consumed event handling with explicit capital project effects',
        slug='consumed_event_handling_with_explicit_capital_project_effects',
        domain_tags=('event', 'project'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=36,
        title='API boundary hardening around workbench and mutation routes',
        slug='api_boundary_hardening_around_workbench_and_mutation_routes',
        domain_tags=('boundary', 'hardening', 'around'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=37,
        title='Idempotent handling for repeated field and document updates',
        slug='idempotent_handling_for_repeated_field_and_document_updates',
        domain_tags=('document',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=38,
        title='Dead-letter triage for operational exceptions',
        slug='dead_letter_triage_for_operational_exceptions',
        domain_tags=('dead_letter', 'triage', 'operational'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=39,
        title='Configuration workbench for project controls calendars and thresholds',
        slug='configuration_workbench_for_project_controls_calendars_and_thresholds',
        domain_tags=('configuration', 'project'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=40,
        title='Policy rule library for capital delivery controls',
        slug='policy_rule_library_for_capital_delivery_controls',
        domain_tags=('policy',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=41,
        title='Control assertions for monthly and gate review readiness',
        slug='control_assertions_for_monthly_and_gate_review_readiness',
        domain_tags=('control', 'assertions', 'monthly'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=42,
        title='Schema extension governance for owner-specific fields',
        slug='schema_extension_governance_for_owner_specific_fields',
        domain_tags=('governance',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=43,
        title='Governed model definitions for package and system semantics',
        slug='governed_model_definitions_for_package_and_system_semantics',
        domain_tags=('model',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=44,
        title='Multi-project portfolio rollup with drill-back to delivery drivers',
        slug='multi_project_portfolio_rollup_with_drill_back_to_delivery_drivers',
        domain_tags=('project',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=45,
        title='Cross-PBC boundary map for adjacent delivery domains',
        slug='cross_pbc_boundary_map_for_adjacent_delivery_domains',
        domain_tags=('cross_pbc', 'boundary', 'adjacent'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=46,
        title='Startup readiness review workflow',
        slug='startup_readiness_review_workflow',
        domain_tags=('workflow',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=47,
        title='Handover to operations with training and spare-parts verification',
        slug='handover_to_operations_with_training_and_spare_parts_verification',
        domain_tags=('handover', 'operations', 'training'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=48,
        title='Live project onboarding and baseline migration discipline',
        slug='live_project_onboarding_and_baseline_migration_discipline',
        domain_tags=('project',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=49,
        title='Continuous release assurance against domain scenarios',
        slug='continuous_release_assurance_against_domain_scenarios',
        domain_tags=('continuous', 'release', 'assurance'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=50,
        title='Capital project closeout knowledge capture',
        slug='capital_project_closeout_knowledge_capture',
        domain_tags=('close', 'project'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_lifecycle_app_slice.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
)



def capability_registry() -> dict:
    """Return side-effect-free registry metadata for improve1 capabilities."""
    rows = tuple(capability.as_traceability_row() for capability in IMPROVE1_CAPABILITIES)
    return {
        "ok": len(rows) == 50 and all(row["code_artifact_model"] and row["ui_surface"] and row["service_api"] and row["test"] and row["evidence"] for row in rows),
        "pbc": PBC_KEY,
        "capability_count": len(rows),
        "capabilities": rows,
        "side_effects": (),
    }


def plan_feature_execution(feature_number: int) -> dict:
    """Plan how a feature is exercised without mutating package state."""
    match = next((capability for capability in IMPROVE1_CAPABILITIES if capability.feature_number == feature_number), None)
    if match is None:
        return {"ok": False, "pbc": PBC_KEY, "reason": "unknown_feature", "side_effects": ()}
    return {
        "ok": True,
        "pbc": PBC_KEY,
        "feature_number": match.feature_number,
        "title": match.title,
        "slug": match.slug,
        "domain_tags": match.domain_tags,
        "model_artifacts": match.model_artifacts,
        "ui_artifacts": match.ui_artifacts,
        "service_artifacts": match.service_artifacts,
        "test_artifacts": match.test_artifacts,
        "evidence_artifacts": match.evidence_artifacts,
        "requires_configuration": match.configurable,
        "agent_assisted": match.agent_assisted,
        "side_effects": (),
    }


def validate_improve1_capabilities(expected_titles: tuple[str, ...]) -> dict:
    """Validate registry alignment with parsed improve1 titles."""
    actual_titles = tuple(capability.title for capability in IMPROVE1_CAPABILITIES)
    registry = capability_registry()
    return {
        "ok": len(actual_titles) == 50 and actual_titles == expected_titles and registry["ok"],
        "pbc": PBC_KEY,
        "expected_count": len(expected_titles),
        "actual_count": len(actual_titles),
        "titles_match": actual_titles == expected_titles,
        "registry_ok": registry["ok"],
        "side_effects": (),
    }
