"""Package manifest for the travel_management PBC."""

PBC_LITERAL = 'travel_management'

PBC_MANIFEST = {'advanced_capabilities': ('travel_management_event_sourced_operational_history',
                           'travel_management_multi_tenant_policy_isolation',
                           'travel_management_schema_evolution_resilience',
                           'travel_management_autonomous_anomaly_detection',
                           'travel_management_semantic_document_instruction_understanding',
                           'travel_management_predictive_risk_scoring',
                           'travel_management_counterfactual_scenario_simulation',
                           'travel_management_cryptographic_audit_proofs',
                           'travel_management_continuous_control_testing',
                           'travel_management_carbon_and_sustainability_awareness',
                           'travel_management_cross_pbc_event_federation',
                           'travel_management_governed_ai_agent_execution'),
 'analytics': ('travel_management_risk_score', 'travel_management_workbench_metric'),
 'apis': ('POST /travel-requests',
          'POST /travel-bookings',
          'POST /itineraries',
          'POST /policy-checks',
          'GET /travel-workbench'),
 'capabilities': ('travel_request_management',
                  'travel_management_workflow',
                  'travel_management_analytics',
                  'configuration_schema',
                  'rule_engine',
                  'parameter_engine',
                  'owned_schema_migrations_models',
                  'appgen_x_outbox_inbox_eventing',
                  'idempotent_handlers',
                  'retry_dead_letter_evidence',
                  'permissions',
                  'seed_data',
                  'workbench',
                  'agentic_document_instruction_intake',
                  'governed_datastore_crud',
                  'ai_agent_task_assistance',
                  'configuration_workbench',
                  'continuous_release_assurance',
                  'travel_management_event_sourced_operational_history',
                  'travel_management_multi_tenant_policy_isolation',
                  'travel_management_schema_evolution_resilience',
                  'travel_management_autonomous_anomaly_detection',
                  'travel_management_semantic_document_instruction_understanding',
                  'travel_management_predictive_risk_scoring',
                  'travel_management_counterfactual_scenario_simulation',
                  'travel_management_cryptographic_audit_proofs',
                  'travel_management_continuous_control_testing',
                  'travel_management_carbon_and_sustainability_awareness',
                  'travel_management_cross_pbc_event_federation',
                  'travel_management_governed_ai_agent_execution'),
 'configuration': ('TRAVEL_MANAGEMENT_DATABASE_URL',
                   'TRAVEL_MANAGEMENT_EVENT_TOPIC',
                   'TRAVEL_MANAGEMENT_RETRY_LIMIT',
                   'TRAVEL_MANAGEMENT_DEFAULT_POLICY'),
 'consumes': ('EmployeeProvisioned', 'ExpenseApproved', 'SupplierQualified'),
 'datastore_backend': 'postgresql',
 'description': 'Travel requests, bookings, itineraries, policy compliance, duty of care, expense '
                'handoff, supplier feeds, and carbon tracking.',
 'docs': ('SPECIFICATION.md', 'RELEASE_EVIDENCE.md', 'README.md', 'implementation-plan.md', 'implementation-status.md'),
 'emits': ('TravelApproved', 'TravelBooked', 'DutyOfCareAlerted', 'TravelExpenseHandedOff'),
 'label': 'Travel Management',
 'mesh': 'hcm',
 'migrations': ('migrations/001_initial.sql',),
 'pbc': 'travel_management',
 'permissions': ('travel_management.read',
                 'travel_management.create',
                 'travel_management.update',
                 'travel_management.approve',
                 'travel_management.admin'),
 'seed_data': ('seed_data.py',),
 'standard_features': ('travel_request_management',
 'travel_management_workflow',
 'travel_management_analytics',
 'configuration_schema',
 'rule_engine',
 'parameter_engine',
 'owned_schema_migrations_models',
 'appgen_x_outbox_inbox_eventing',
 'idempotent_handlers',
 'retry_dead_letter_evidence',
 'permissions',
 'seed_data',
 'workbench',
 'agentic_document_instruction_intake',
 'governed_datastore_crud',
 'ai_agent_task_assistance',
 'configuration_workbench',
 'continuous_release_assurance'),
 'tables': ('travel_request',
            'travel_booking',
            'travel_itinerary',
            'travel_policy_check',
            'duty_of_care_alert',
            'supplier_travel_feed',
            'travel_expense_handoff',
            'travel_carbon_record'),
 'template': 'workflow',
 'tests': ('tests/test_contract.py', 'tests/test_standalone.py'),
 'ui_fragments': ('TravelManagementWorkbench',
                  'TravelManagementDetail',
                  'TravelManagementAssistantPanel',
                  'TripRequestReadinessForm',
                  'TripRequestReadinessWizard',
                  'BookingIntentWizard',
                  'DutyOfCareResponseWizard',
                  'DisruptionRebookingWizard',
                  'ExpenseHandoffWizard'),
 'version': '1.0.0',
 'workflows': ('travel_request_workflow', 'travel_management_approval_workflow')}
