"""Package manifest for the contract_lifecycle PBC."""

PBC_MANIFEST = {'pbc': 'contract_lifecycle',
 'label': 'Contract Lifecycle Management',
 'mesh': 'relationship',
 'description': 'Contract authoring, clauses, obligations, approvals, renewals, risk scoring, documents, and '
                'transaction events.',
 'version': '1.0.0',
 'datastore_backend': 'postgresql',
 'tables': ('contract_record',
            'contract_party',
            'clause_library',
            'contract_obligation',
            'approval_workflow',
            'renewal_event',
            'contract_risk_assessment',
            'contract_document_packet'),
 'apis': ('POST /contracts',
          'POST /contracts/{id}/clauses',
          'POST /contracts/{id}/obligations',
          'POST /contracts/{id}/approvals',
          'POST /contracts/{id}/renewals',
          'GET /contract-lifecycle-workbench'),
 'emits': ('ContractAuthored', 'ObligationActivated', 'ContractApproved', 'RenewalScheduled'),
 'consumes': ('CustomerUpdated', 'SupplierQualified', 'PolicyChanged'),
 'template': 'workflow',
 'ui_fragments': ('ContractLifecycleWorkbench', 'ContractLifecycleDetail', 'ContractLifecycleAssistantPanel'),
 'permissions': ('contract_lifecycle.read',
                 'contract_lifecycle.create',
                 'contract_lifecycle.update',
                 'contract_lifecycle.approve',
                 'contract_lifecycle.admin'),
 'configuration': ('CONTRACT_LIFECYCLE_DATABASE_URL',
                   'CONTRACT_LIFECYCLE_EVENT_TOPIC',
                   'CONTRACT_LIFECYCLE_RETRY_LIMIT',
                   'CONTRACT_LIFECYCLE_DEFAULT_POLICY'),
 'migrations': ('migrations/001_initial.sql',),
 'seed_data': ('seed_data.py',),
 'tests': ('tests/test_contract.py',),
 'docs': ('SPECIFICATION.md', 'RELEASE_EVIDENCE.md'),
 'capabilities': ('contract_record_management',
                  'contract_lifecycle_workflow',
                  'contract_lifecycle_analytics',
                  'configuration_schema',
                  'rule_engine',
                  'parameter_engine',
                  'owned_schema_migrations_models',
                  'appgen_x_outbox_inbox_eventing',
                  'idempotent_handlers',
                  'retry_dead_letter_evidence',
                  'permissions',
                  'seed_data',
                  'workbench',
                  'agentic_document_instruction_intake',
                  'governed_datastore_crud',
                  'contract_lifecycle_event_sourced_operational_history',
                  'contract_lifecycle_multi_tenant_policy_isolation',
                  'contract_lifecycle_schema_evolution_resilience',
                  'contract_lifecycle_autonomous_anomaly_detection',
                  'contract_lifecycle_semantic_document_instruction_understanding',
                  'contract_lifecycle_predictive_risk_scoring',
                  'contract_lifecycle_counterfactual_scenario_simulation',
                  'contract_lifecycle_cryptographic_audit_proofs',
                  'contract_lifecycle_continuous_control_testing',
                  'contract_lifecycle_carbon_and_sustainability_awareness',
                  'contract_lifecycle_cross_pbc_event_federation',
                  'contract_lifecycle_governed_ai_agent_execution'),
 'standard_features': ('contract_record_management',
                       'contract_lifecycle_workflow',
                       'contract_lifecycle_analytics',
                       'configuration_schema',
                       'rule_engine',
                       'parameter_engine',
                       'owned_schema_migrations_models',
                       'appgen_x_outbox_inbox_eventing',
                       'idempotent_handlers',
                       'retry_dead_letter_evidence',
                       'permissions',
                       'seed_data',
                       'workbench',
                       'agentic_document_instruction_intake',
                       'governed_datastore_crud'),
 'advanced_capabilities': ('contract_lifecycle_event_sourced_operational_history',
                           'contract_lifecycle_multi_tenant_policy_isolation',
                           'contract_lifecycle_schema_evolution_resilience',
                           'contract_lifecycle_autonomous_anomaly_detection',
                           'contract_lifecycle_semantic_document_instruction_understanding',
                           'contract_lifecycle_predictive_risk_scoring',
                           'contract_lifecycle_counterfactual_scenario_simulation',
                           'contract_lifecycle_cryptographic_audit_proofs',
                           'contract_lifecycle_continuous_control_testing',
                           'contract_lifecycle_carbon_and_sustainability_awareness',
                           'contract_lifecycle_cross_pbc_event_federation',
                           'contract_lifecycle_governed_ai_agent_execution'),
 'workflows': ('contract_record_workflow', 'contract_lifecycle_approval_workflow'),
 'analytics': ('contract_lifecycle_risk_score', 'contract_lifecycle_workbench_metric')}
