"""Owned model metadata for the contract_lifecycle PBC."""
PBC_KEY = 'contract_lifecycle'
OWNED_SCHEMA = {'schema': 'contract_lifecycle',
 'table_prefix': 'contract_lifecycle_',
 'tables': ({'logical_table': 'contract_record',
             'owned_table': 'contract_lifecycle_contract_record',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'contract_party',
             'owned_table': 'contract_lifecycle_contract_party',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'contract_record_id',
                                'target_table': 'contract_lifecycle_contract_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'clause_library',
             'owned_table': 'contract_lifecycle_clause_library',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'contract_record_id',
                                'target_table': 'contract_lifecycle_contract_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'contract_obligation',
             'owned_table': 'contract_lifecycle_contract_obligation',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'contract_record_id',
                                'target_table': 'contract_lifecycle_contract_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'approval_workflow',
             'owned_table': 'contract_lifecycle_approval_workflow',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'contract_record_id',
                                'target_table': 'contract_lifecycle_contract_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'renewal_event',
             'owned_table': 'contract_lifecycle_renewal_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'contract_record_id',
                                'target_table': 'contract_lifecycle_contract_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'contract_risk_assessment',
             'owned_table': 'contract_lifecycle_contract_risk_assessment',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'contract_record_id',
                                'target_table': 'contract_lifecycle_contract_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'contract_document_packet',
             'owned_table': 'contract_lifecycle_contract_document_packet',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'contract_record_id',
                                'target_table': 'contract_lifecycle_contract_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'appgen_outbox_event',
             'owned_table': 'contract_lifecycle_appgen_outbox_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'appgen_inbox_event',
             'owned_table': 'contract_lifecycle_appgen_inbox_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'appgen_dead_letter_event',
             'owned_table': 'contract_lifecycle_appgen_dead_letter_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()})}
MODELS = ({'class_name': 'ContractLifecycleContractRecord',
  'table': 'contract_lifecycle_contract_record',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
             {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
             {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
             {'name': 'payload', 'type': 'json', 'required': False},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'ContractLifecycleContractParty',
  'table': 'contract_lifecycle_contract_party',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'contract_record_id',
              'type': 'integer',
              'required': True,
              'references': 'contract_lifecycle_contract_record.id'},
             {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
             {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
             {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
             {'name': 'payload', 'type': 'json', 'required': False},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ({'field': 'contract_record_id',
                     'target_table': 'contract_lifecycle_contract_record',
                     'target_column': 'id',
                     'cardinality': 'many-to-one',
                     'ownership': 'same_pbc'},)},
 {'class_name': 'ContractLifecycleClauseLibrary',
  'table': 'contract_lifecycle_clause_library',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'contract_record_id',
              'type': 'integer',
              'required': True,
              'references': 'contract_lifecycle_contract_record.id'},
             {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
             {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
             {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
             {'name': 'payload', 'type': 'json', 'required': False},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ({'field': 'contract_record_id',
                     'target_table': 'contract_lifecycle_contract_record',
                     'target_column': 'id',
                     'cardinality': 'many-to-one',
                     'ownership': 'same_pbc'},)},
 {'class_name': 'ContractLifecycleContractObligation',
  'table': 'contract_lifecycle_contract_obligation',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'contract_record_id',
              'type': 'integer',
              'required': True,
              'references': 'contract_lifecycle_contract_record.id'},
             {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
             {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
             {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
             {'name': 'payload', 'type': 'json', 'required': False},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ({'field': 'contract_record_id',
                     'target_table': 'contract_lifecycle_contract_record',
                     'target_column': 'id',
                     'cardinality': 'many-to-one',
                     'ownership': 'same_pbc'},)},
 {'class_name': 'ContractLifecycleApprovalWorkflow',
  'table': 'contract_lifecycle_approval_workflow',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'contract_record_id',
              'type': 'integer',
              'required': True,
              'references': 'contract_lifecycle_contract_record.id'},
             {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
             {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
             {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
             {'name': 'payload', 'type': 'json', 'required': False},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ({'field': 'contract_record_id',
                     'target_table': 'contract_lifecycle_contract_record',
                     'target_column': 'id',
                     'cardinality': 'many-to-one',
                     'ownership': 'same_pbc'},)},
 {'class_name': 'ContractLifecycleRenewalEvent',
  'table': 'contract_lifecycle_renewal_event',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'contract_record_id',
              'type': 'integer',
              'required': True,
              'references': 'contract_lifecycle_contract_record.id'},
             {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
             {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
             {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
             {'name': 'payload', 'type': 'json', 'required': False},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ({'field': 'contract_record_id',
                     'target_table': 'contract_lifecycle_contract_record',
                     'target_column': 'id',
                     'cardinality': 'many-to-one',
                     'ownership': 'same_pbc'},)},
 {'class_name': 'ContractLifecycleContractRiskAssessment',
  'table': 'contract_lifecycle_contract_risk_assessment',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'contract_record_id',
              'type': 'integer',
              'required': True,
              'references': 'contract_lifecycle_contract_record.id'},
             {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
             {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
             {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
             {'name': 'payload', 'type': 'json', 'required': False},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ({'field': 'contract_record_id',
                     'target_table': 'contract_lifecycle_contract_record',
                     'target_column': 'id',
                     'cardinality': 'many-to-one',
                     'ownership': 'same_pbc'},)},
 {'class_name': 'ContractLifecycleContractDocumentPacket',
  'table': 'contract_lifecycle_contract_document_packet',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'contract_record_id',
              'type': 'integer',
              'required': True,
              'references': 'contract_lifecycle_contract_record.id'},
             {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
             {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
             {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
             {'name': 'payload', 'type': 'json', 'required': False},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ({'field': 'contract_record_id',
                     'target_table': 'contract_lifecycle_contract_record',
                     'target_column': 'id',
                     'cardinality': 'many-to-one',
                     'ownership': 'same_pbc'},)},
 {'class_name': 'ContractLifecycleAppgenOutboxEvent',
  'table': 'contract_lifecycle_appgen_outbox_event',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'contract_record_id',
              'type': 'integer',
              'required': True,
              'references': 'contract_lifecycle_contract_record.id'},
             {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
             {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
             {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
             {'name': 'payload', 'type': 'json', 'required': False},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'ContractLifecycleAppgenInboxEvent',
  'table': 'contract_lifecycle_appgen_inbox_event',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'contract_record_id',
              'type': 'integer',
              'required': True,
              'references': 'contract_lifecycle_contract_record.id'},
             {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
             {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
             {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
             {'name': 'payload', 'type': 'json', 'required': False},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'ContractLifecycleAppgenDeadLetterEvent',
  'table': 'contract_lifecycle_appgen_dead_letter_event',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'contract_record_id',
              'type': 'integer',
              'required': True,
              'references': 'contract_lifecycle_contract_record.id'},
             {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
             {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
             {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
             {'name': 'payload', 'type': 'json', 'required': False},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()})


def model_manifest():
    schema_tables = tuple(table['owned_table'] for table in OWNED_SCHEMA.get('tables', ()))
    model_tables = tuple(model['table'] for model in MODELS)
    missing_models = tuple(table for table in schema_tables if table not in model_tables)
    external_models = tuple(table for table in model_tables if not table.startswith(f'{PBC_KEY}_'))
    relationship_targets = tuple(rel.get('target_table') for table in OWNED_SCHEMA.get('tables', ()) for rel in table.get('relationships', ()) if rel.get('target_table'))
    cross_pbc_relationships = tuple(target for target in relationship_targets if not target.startswith(f'{PBC_KEY}_'))
    return {'ok': bool(schema_tables) and bool(model_tables) and not missing_models and not external_models and not cross_pbc_relationships, 'pbc': PBC_KEY, 'schema_tables': schema_tables, 'model_tables': model_tables, 'missing_models': missing_models, 'external_models': external_models, 'cross_pbc_relationships': cross_pbc_relationships, 'relationship_targets': relationship_targets, 'side_effects': ()}


def instantiate_model(table_name, values=None):
    model = next((item for item in MODELS if item['table'] == table_name), None)
    if model is None:
        return {'ok': False, 'reason': 'unknown_model', 'table': table_name, 'side_effects': ()}
    supplied = dict(values or {})
    fields = tuple(field['name'] if isinstance(field, dict) else field for field in model.get('fields', ()))
    return {'ok': table_name.startswith(f'{PBC_KEY}_') and bool(fields), 'pbc': PBC_KEY, 'model': model['class_name'], 'table': table_name, 'fields': fields, 'payload': {field: supplied.get(field) for field in fields}, 'side_effects': ()}


def smoke_test():
    manifest = model_manifest()
    first_table = manifest['model_tables'][0] if manifest['model_tables'] else None
    instance = instantiate_model(first_table, {'id': 1}) if first_table else {'ok': False}
    return {'ok': manifest['ok'] and instance.get('ok') is True, 'manifest': manifest, 'instance': instance, 'side_effects': ()}
