"""Generated owned schema evidence for the contract_lifecycle PBC."""

SCHEMA_CONTRACT = {'format': 'appgen.contract-lifecycle-owned-schema-contract.v1',
 'ok': True,
 'tables': ({'logical_table': 'contract_record',
             'owned_table': 'contract_lifecycle_contract_record',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'contract_party',
             'owned_table': 'contract_lifecycle_contract_party',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'contract_record_id',
                                'target_table': 'contract_lifecycle_contract_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'clause_library',
             'owned_table': 'contract_lifecycle_clause_library',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'contract_record_id',
                                'target_table': 'contract_lifecycle_contract_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'contract_obligation',
             'owned_table': 'contract_lifecycle_contract_obligation',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'contract_record_id',
                                'target_table': 'contract_lifecycle_contract_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'approval_workflow',
             'owned_table': 'contract_lifecycle_approval_workflow',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'contract_record_id',
                                'target_table': 'contract_lifecycle_contract_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'renewal_event',
             'owned_table': 'contract_lifecycle_renewal_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'contract_record_id',
                                'target_table': 'contract_lifecycle_contract_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'contract_risk_assessment',
             'owned_table': 'contract_lifecycle_contract_risk_assessment',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'contract_record_id',
                                'target_table': 'contract_lifecycle_contract_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'contract_document_packet',
             'owned_table': 'contract_lifecycle_contract_document_packet',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'contract_record_id',
                                'target_table': 'contract_lifecycle_contract_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'appgen_outbox_event',
             'owned_table': 'contract_lifecycle_appgen_outbox_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'appgen_inbox_event',
             'owned_table': 'contract_lifecycle_appgen_inbox_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'appgen_dead_letter_event',
             'owned_table': 'contract_lifecycle_appgen_dead_letter_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()}),
 'migrations': ('migrations/001_initial.sql',),
 'models': ({'class_name': 'ContractLifecycleContractRecord',
             'table': 'contract_lifecycle_contract_record',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'ContractLifecycleContractParty',
             'table': 'contract_lifecycle_contract_party',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'contract_record_id',
                                'target_table': 'contract_lifecycle_contract_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'ContractLifecycleClauseLibrary',
             'table': 'contract_lifecycle_clause_library',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'contract_record_id',
                                'target_table': 'contract_lifecycle_contract_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'ContractLifecycleContractObligation',
             'table': 'contract_lifecycle_contract_obligation',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'contract_record_id',
                                'target_table': 'contract_lifecycle_contract_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'ContractLifecycleApprovalWorkflow',
             'table': 'contract_lifecycle_approval_workflow',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'contract_record_id',
                                'target_table': 'contract_lifecycle_contract_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'ContractLifecycleRenewalEvent',
             'table': 'contract_lifecycle_renewal_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'contract_record_id',
                                'target_table': 'contract_lifecycle_contract_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'ContractLifecycleContractRiskAssessment',
             'table': 'contract_lifecycle_contract_risk_assessment',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'contract_record_id',
                                'target_table': 'contract_lifecycle_contract_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'ContractLifecycleContractDocumentPacket',
             'table': 'contract_lifecycle_contract_document_packet',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'contract_record_id',
                                'target_table': 'contract_lifecycle_contract_record',
                                'target_column': 'id',
                                'cardinality': 'many-to-one',
                                'ownership': 'same_pbc'},)},
            {'class_name': 'ContractLifecycleAppgenOutboxEvent',
             'table': 'contract_lifecycle_appgen_outbox_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'ContractLifecycleAppgenInboxEvent',
             'table': 'contract_lifecycle_appgen_inbox_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'class_name': 'ContractLifecycleAppgenDeadLetterEvent',
             'table': 'contract_lifecycle_appgen_dead_letter_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'contract_record_id',
                         'type': 'integer',
                         'required': True,
                         'references': 'contract_lifecycle_contract_record.id'},
                        {'name': 'code', 'type': 'string', 'required': True, 'searchable': True},
                        {'name': 'status', 'type': 'string', 'required': True, 'default': 'draft'},
                        {'name': 'version', 'type': 'integer', 'required': True, 'default': 1},
                        {'name': 'payload', 'type': 'json', 'required': False},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()}),
 'datastore_backends': ('postgresql', 'mysql', 'mariadb'),
 'database_backends': ('postgresql', 'mysql', 'mariadb'),
 'shared_table_access': False,
 'pbc': 'contract_lifecycle',
 'owned_tables': ('contract_lifecycle_contract_record',
                  'contract_lifecycle_contract_party',
                  'contract_lifecycle_clause_library',
                  'contract_lifecycle_contract_obligation',
                  'contract_lifecycle_approval_workflow',
                  'contract_lifecycle_renewal_event',
                  'contract_lifecycle_contract_risk_assessment',
                  'contract_lifecycle_contract_document_packet',
                  'contract_lifecycle_appgen_outbox_event',
                  'contract_lifecycle_appgen_inbox_event',
                  'contract_lifecycle_appgen_dead_letter_event')}


def build_schema_contract():
    """Return generated owned schema, migration, and model evidence."""
    return dict(SCHEMA_CONTRACT)


def validate_schema_contract():
    contract = build_schema_contract()
    pbc = contract['pbc']
    owned_tables = tuple(contract.get('owned_tables', ()))
    model_tables = tuple(model['table'] for model in contract.get('models', ()))
    allowed_backends = {'postgresql', 'mysql', 'mariadb'}
    invalid_backends = tuple(backend for backend in contract.get('database_backends', ()) if backend not in allowed_backends)
    missing_models = tuple(table for table in owned_tables if table not in model_tables)
    invalid_tables = tuple(table for table in owned_tables if not table.startswith(f'{pbc}_'))
    return {'ok': contract.get('ok') is True and bool(owned_tables) and bool(contract.get('migrations')) and not invalid_tables and not missing_models and not invalid_backends and contract.get('shared_table_access') is False, 'pbc': pbc, 'owned_tables': owned_tables, 'model_tables': model_tables, 'migration_paths': tuple(contract.get('migrations', ())), 'invalid_tables': invalid_tables, 'missing_models': missing_models, 'invalid_backends': invalid_backends, 'side_effects': ()}


def smoke_test():
    return validate_schema_contract()
