"""Executable improve1 capability registry for this PBC.

This module turns the package-local improve1 backlog into code-level evidence.
It is intentionally side-effect free: callers can inspect capability coverage, plan
execution, and verify surface mappings without touching external systems.
"""

from __future__ import annotations

from dataclasses import dataclass

PBC_KEY = 'payment_orchestration'


@dataclass(frozen=True)
class Improve1Capability:
    feature_number: int
    title: str
    slug: str
    domain_tags: tuple[str, ...]
    model_artifacts: tuple[str, ...]
    ui_artifacts: tuple[str, ...]
    service_artifacts: tuple[str, ...]
    test_artifacts: tuple[str, ...]
    evidence_artifacts: tuple[str, ...]
    configurable: bool = True
    agent_assisted: bool = True
    side_effect_free_plan: bool = True

    def as_traceability_row(self) -> dict:
        return {
            "feature_number": self.feature_number,
            "title": self.title,
            "slug": self.slug,
            "domain_tags": self.domain_tags,
            "code_artifact_model": self.model_artifacts,
            "ui_surface": self.ui_artifacts,
            "service_api": self.service_artifacts,
            "test": self.test_artifacts,
            "evidence": self.evidence_artifacts,
            "configurable": self.configurable,
            "agent_assisted": self.agent_assisted,
            "side_effect_free_plan": self.side_effect_free_plan,
        }



IMPROVE1_CAPABILITIES: tuple[Improve1Capability, ...] = (
    Improve1Capability(
        feature_number=1,
        title='Gateway readiness gate',
        slug='gateway_readiness_gate',
        domain_tags=('gateway', 'readiness'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=2,
        title='Gateway health and degradation model',
        slug='gateway_health_and_degradation_model',
        domain_tags=('model',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=3,
        title='Payment token custody governance',
        slug='payment_token_custody_governance',
        domain_tags=('governance', 'payment'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=4,
        title='Token lifecycle state machine',
        slug='token_lifecycle_state_machine',
        domain_tags=('token', 'lifecycle', 'state'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=5,
        title='Checkout completion intake readiness',
        slug='checkout_completion_intake_readiness',
        domain_tags=('checkout', 'completion', 'intake'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=6,
        title='Payment intent lifecycle state machine',
        slug='payment_intent_lifecycle_state_machine',
        domain_tags=('payment',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=7,
        title='Amount and currency integrity controls',
        slug='amount_and_currency_integrity_controls',
        domain_tags=('amount', 'currency', 'integrity'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=8,
        title='Gateway route scoring',
        slug='gateway_route_scoring',
        domain_tags=('gateway', 'route', 'scoring'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=9,
        title='Counterfactual gateway routing simulation',
        slug='counterfactual_gateway_routing_simulation',
        domain_tags=('routing',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=10,
        title='Provider allocation mechanism',
        slug='provider_allocation_mechanism',
        domain_tags=('provider', 'allocation', 'mechanism'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=11,
        title='Fraud handoff lifecycle',
        slug='fraud_handoff_lifecycle',
        domain_tags=('fraud', 'handoff', 'lifecycle'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=12,
        title='Fraud-risk route suppression',
        slug='fraud_risk_route_suppression',
        domain_tags=('risk',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=13,
        title='Authorization strategy controls',
        slug='authorization_strategy_controls',
        domain_tags=('authorization', 'strategy', 'controls'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=14,
        title='Capture lifecycle controls',
        slug='capture_lifecycle_controls',
        domain_tags=('capture', 'lifecycle', 'controls'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=15,
        title='Refund lifecycle controls',
        slug='refund_lifecycle_controls',
        domain_tags=('refund', 'lifecycle', 'controls'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=16,
        title='Void lifecycle controls',
        slug='void_lifecycle_controls',
        domain_tags=('lifecycle', 'controls'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=17,
        title='Payment failure taxonomy',
        slug='payment_failure_taxonomy',
        domain_tags=('payment', 'tax'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=18,
        title='Smart retry orchestration',
        slug='smart_retry_orchestration',
        domain_tags=('orchestration',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=19,
        title='Settlement evidence model',
        slug='settlement_evidence_model',
        domain_tags=('model', 'settlement'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=20,
        title='Reconciliation handoff governance',
        slug='reconciliation_handoff_governance',
        domain_tags=('governance', 'reconciliation'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=21,
        title='Multi-currency and FX controls',
        slug='multi_currency_and_fx_controls',
        domain_tags=('multi_currency', 'controls'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=22,
        title='Payment proof generation',
        slug='payment_proof_generation',
        domain_tags=('payment',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=23,
        title='Immutable payment audit trace',
        slug='immutable_payment_audit_trace',
        domain_tags=('audit', 'payment'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=24,
        title='Dynamic payment policy screening',
        slug='dynamic_payment_policy_screening',
        domain_tags=('payment', 'policy'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=25,
        title='Runtime parameter impact controls',
        slug='runtime_parameter_impact_controls',
        domain_tags=('runtime', 'parameter', 'impact'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=26,
        title='Schema extension governance',
        slug='schema_extension_governance',
        domain_tags=('governance',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=27,
        title='AppGen-X inbox reliability',
        slug='appgen_x_inbox_reliability',
        domain_tags=('appgen_x', 'inbox', 'reliability'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=28,
        title='AppGen-X outbox delivery assurance',
        slug='appgen_x_outbox_delivery_assurance',
        domain_tags=('appgen_x', 'outbox', 'delivery'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=29,
        title='Cross-PBC boundary proof',
        slug='cross_pbc_boundary_proof',
        domain_tags=('cross_pbc', 'boundary', 'proof'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=30,
        title='Payment federation projection',
        slug='payment_federation_projection',
        domain_tags=('payment', 'project'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=31,
        title='Carbon-aware settlement windows',
        slug='carbon_aware_settlement_windows',
        domain_tags=('settlement',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=32,
        title='Gateway mix optimization',
        slug='gateway_mix_optimization',
        domain_tags=('gateway', 'optimization'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=33,
        title='Authorization and settlement forecasting',
        slug='authorization_and_settlement_forecasting',
        domain_tags=('forecast', 'settlement'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=34,
        title='Payment anomaly detection',
        slug='payment_anomaly_detection',
        domain_tags=('payment',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=35,
        title='Stochastic payment exposure model',
        slug='stochastic_payment_exposure_model',
        domain_tags=('model', 'payment'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=36,
        title='Governed payment model evidence',
        slug='governed_payment_model_evidence',
        domain_tags=('model', 'payment'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=37,
        title='Semantic payment instruction parsing',
        slug='semantic_payment_instruction_parsing',
        domain_tags=('payment',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=38,
        title='Agent-safe payment plans',
        slug='agent_safe_payment_plans',
        domain_tags=('agent', 'payment'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=39,
        title='Payment exception cockpit',
        slug='payment_exception_cockpit',
        domain_tags=('payment',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=40,
        title='Gateway routing board',
        slug='gateway_routing_board',
        domain_tags=('routing',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=41,
        title='Token vault UI safeguards',
        slug='token_vault_ui_safeguards',
        domain_tags=('token', 'vault', 'safeguards'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=42,
        title='Capture/refund console',
        slug='capture_refund_console',
        domain_tags=('capture', 'refund', 'console'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=43,
        title='Settlement and reconciliation panel',
        slug='settlement_and_reconciliation_panel',
        domain_tags=('reconciliation', 'settlement'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=44,
        title='Payment resilience drills',
        slug='payment_resilience_drills',
        domain_tags=('payment',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=45,
        title='Continuous payment control testing',
        slug='continuous_payment_control_testing',
        domain_tags=('payment',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=46,
        title='Crypto-agile payment authorization',
        slug='crypto_agile_payment_authorization',
        domain_tags=('payment',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=47,
        title='Chargeback and dispute readiness',
        slug='chargeback_and_dispute_readiness',
        domain_tags=('chargeback', 'dispute', 'readiness'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=48,
        title='Payment workbench coverage',
        slug='payment_workbench_coverage',
        domain_tags=('payment',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=49,
        title='Payment readiness score',
        slug='payment_readiness_score',
        domain_tags=('payment',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=50,
        title='End-to-end payment lifecycle proof',
        slug='end_to_end_payment_lifecycle_proof',
        domain_tags=('payment',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'repository.py', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
)



def capability_registry() -> dict:
    """Return side-effect-free registry metadata for improve1 capabilities."""
    rows = tuple(capability.as_traceability_row() for capability in IMPROVE1_CAPABILITIES)
    return {
        "ok": len(rows) == 50 and all(row["code_artifact_model"] and row["ui_surface"] and row["service_api"] and row["test"] and row["evidence"] for row in rows),
        "pbc": PBC_KEY,
        "capability_count": len(rows),
        "capabilities": rows,
        "side_effects": (),
    }


def plan_feature_execution(feature_number: int) -> dict:
    """Plan how a feature is exercised without mutating package state."""
    match = next((capability for capability in IMPROVE1_CAPABILITIES if capability.feature_number == feature_number), None)
    if match is None:
        return {"ok": False, "pbc": PBC_KEY, "reason": "unknown_feature", "side_effects": ()}
    return {
        "ok": True,
        "pbc": PBC_KEY,
        "feature_number": match.feature_number,
        "title": match.title,
        "slug": match.slug,
        "domain_tags": match.domain_tags,
        "model_artifacts": match.model_artifacts,
        "ui_artifacts": match.ui_artifacts,
        "service_artifacts": match.service_artifacts,
        "test_artifacts": match.test_artifacts,
        "evidence_artifacts": match.evidence_artifacts,
        "requires_configuration": match.configurable,
        "agent_assisted": match.agent_assisted,
        "side_effects": (),
    }


def validate_improve1_capabilities(expected_titles: tuple[str, ...]) -> dict:
    """Validate registry alignment with parsed improve1 titles."""
    actual_titles = tuple(capability.title for capability in IMPROVE1_CAPABILITIES)
    registry = capability_registry()
    return {
        "ok": len(actual_titles) == 50 and actual_titles == expected_titles and registry["ok"],
        "pbc": PBC_KEY,
        "expected_count": len(expected_titles),
        "actual_count": len(actual_titles),
        "titles_match": actual_titles == expected_titles,
        "registry_ok": registry["ok"],
        "side_effects": (),
    }
