"""Package manifest for the building_information_modeling_ops PBC."""

PBC_MANIFEST = {'advanced_capabilities': ('building_information_modeling_ops_event_sourced_operational_history',
                           'building_information_modeling_ops_multi_tenant_policy_isolation',
                           'building_information_modeling_ops_schema_evolution_resilience',
                           'building_information_modeling_ops_autonomous_anomaly_detection',
                           'building_information_modeling_ops_semantic_document_instruction_understanding',
                           'building_information_modeling_ops_predictive_risk_scoring',
                           'building_information_modeling_ops_counterfactual_scenario_simulation',
                           'building_information_modeling_ops_cryptographic_audit_proofs',
                           'building_information_modeling_ops_continuous_control_testing',
                           'building_information_modeling_ops_carbon_and_sustainability_awareness',
                           'building_information_modeling_ops_cross_pbc_event_federation',
                           'building_information_modeling_ops_governed_ai_agent_execution'),
 'analytics': ('building_information_modeling_ops_risk_score',
               'building_information_modeling_ops_workbench_metric'),
 'apis': ('POST /bim-models',
          'POST /model-versions',
          'POST /clash-issues',
          'POST /asset-objects',
          'POST /handover-packages',
          'GET /building-information-modeling-ops-workbench'),
 'capabilities': ('bim_model_management',
                  'building_information_modeling_ops_workflow',
                  'building_information_modeling_ops_analytics',
                  'configuration_schema',
                  'rule_engine',
                  'parameter_engine',
                  'owned_schema_migrations_models',
                  'appgen_x_outbox_inbox_eventing',
                  'idempotent_handlers',
                  'retry_dead_letter_evidence',
                  'permissions',
                  'seed_data',
                  'workbench',
                  'agentic_document_instruction_intake',
                  'governed_datastore_crud',
                  'ai_agent_task_assistance',
                  'configuration_workbench',
                  'continuous_release_assurance',
                  'building_information_modeling_ops_event_sourced_operational_history',
                  'building_information_modeling_ops_multi_tenant_policy_isolation',
                  'building_information_modeling_ops_schema_evolution_resilience',
                  'building_information_modeling_ops_autonomous_anomaly_detection',
                  'building_information_modeling_ops_semantic_document_instruction_understanding',
                  'building_information_modeling_ops_predictive_risk_scoring',
                  'building_information_modeling_ops_counterfactual_scenario_simulation',
                  'building_information_modeling_ops_cryptographic_audit_proofs',
                  'building_information_modeling_ops_continuous_control_testing',
                  'building_information_modeling_ops_carbon_and_sustainability_awareness',
                  'building_information_modeling_ops_cross_pbc_event_federation',
                  'building_information_modeling_ops_governed_ai_agent_execution'),
 'configuration': ('BUILDING_INFORMATION_MODELING_OPS_DATABASE_URL',
                   'BUILDING_INFORMATION_MODELING_OPS_EVENT_TOPIC',
                   'BUILDING_INFORMATION_MODELING_OPS_RETRY_LIMIT',
                   'BUILDING_INFORMATION_MODELING_OPS_DEFAULT_POLICY'),
 'consumes': ('PolicyChanged', 'AuditEventSealed', 'OperationalKpiChanged'),
 'datastore_backend': 'postgresql',
 'description': 'BIM models, versions, clashes, assets, handover data, model governance, and '
                'digital twin operations',
 'docs': ('SPECIFICATION.md', 'RELEASE_EVIDENCE.md'),
 'emits': ('BuildingInformationModelingOpsCreated',
           'BuildingInformationModelingOpsUpdated',
           'BuildingInformationModelingOpsApproved',
           'BuildingInformationModelingOpsExceptionOpened'),
 'label': 'Building Information Modeling Operations',
 'mesh': 'content',
 'migrations': ('migrations/001_initial.sql',),
 'pbc': 'building_information_modeling_ops',
 'permissions': ('building_information_modeling_ops.read',
                 'building_information_modeling_ops.create',
                 'building_information_modeling_ops.update',
                 'building_information_modeling_ops.approve',
                 'building_information_modeling_ops.admin'),
 'seed_data': ('seed_data.py',),
 'standard_features': ('bim_model_management',
                       'building_information_modeling_ops_workflow',
                       'building_information_modeling_ops_analytics',
                       'configuration_schema',
                       'rule_engine',
                       'parameter_engine',
                       'owned_schema_migrations_models',
                       'appgen_x_outbox_inbox_eventing',
                       'idempotent_handlers',
                       'retry_dead_letter_evidence',
                       'permissions',
                       'seed_data',
                       'workbench',
                       'agentic_document_instruction_intake',
                       'governed_datastore_crud',
                       'ai_agent_task_assistance',
                       'configuration_workbench',
                       'continuous_release_assurance'),
 'tables': ('bim_model',
            'model_version',
            'clash_issue',
            'asset_object',
            'handover_package',
            'model_review',
            'digital_twin_link',
            'building_information_modeling_ops_policy_rule',
            'building_information_modeling_ops_runtime_parameter',
            'building_information_modeling_ops_schema_extension',
            'building_information_modeling_ops_control_assertion',
            'building_information_modeling_ops_governed_model'),
 'template': 'crm',
 'tests': ('tests/test_contract.py',),
 'ui_fragments': ('BuildingInformationModelingOpsWorkbench',
                  'BuildingInformationModelingOpsDetail',
                  'BuildingInformationModelingOpsAssistantPanel'),
 'version': '1.0.0',
 'workflows': ('building_information_modeling_ops_create_bim_model_workflow',
               'building_information_modeling_ops_record_model_version_workflow')}
