"""Executable improve1 capability registry for this PBC.

This module turns the package-local improve1 backlog into code-level evidence.
It is intentionally side-effect free: callers can inspect capability coverage, plan
execution, and verify surface mappings without touching external systems.
"""

from __future__ import annotations

from dataclasses import dataclass

PBC_KEY = 'construction_contracts_commercials'


@dataclass(frozen=True)
class Improve1Capability:
    feature_number: int
    title: str
    slug: str
    domain_tags: tuple[str, ...]
    model_artifacts: tuple[str, ...]
    ui_artifacts: tuple[str, ...]
    service_artifacts: tuple[str, ...]
    test_artifacts: tuple[str, ...]
    evidence_artifacts: tuple[str, ...]
    configurable: bool = True
    agent_assisted: bool = True
    side_effect_free_plan: bool = True

    def as_traceability_row(self) -> dict:
        return {
            "feature_number": self.feature_number,
            "title": self.title,
            "slug": self.slug,
            "domain_tags": self.domain_tags,
            "code_artifact_model": self.model_artifacts,
            "ui_surface": self.ui_artifacts,
            "service_api": self.service_artifacts,
            "test": self.test_artifacts,
            "evidence": self.evidence_artifacts,
            "configurable": self.configurable,
            "agent_assisted": self.agent_assisted,
            "side_effect_free_plan": self.side_effect_free_plan,
        }



IMPROVE1_CAPABILITIES: tuple[Improve1Capability, ...] = (
    Improve1Capability(
        feature_number=1,
        title='Contract Commercial Lifecycle',
        slug='contract_commercial_lifecycle',
        domain_tags=('contract',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=2,
        title='Contract Type and Pricing Basis',
        slug='contract_type_and_pricing_basis',
        domain_tags=('contract', 'pricing'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=3,
        title='Scope and Schedule of Values',
        slug='scope_and_schedule_of_values',
        domain_tags=('schedule',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=4,
        title='Pay Application Intake',
        slug='pay_application_intake',
        domain_tags=('application', 'intake'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=5,
        title='Progress Measurement Evidence',
        slug='progress_measurement_evidence',
        domain_tags=('progress', 'measurement', 'evidence'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=6,
        title='Retainage Rules',
        slug='retainage_rules',
        domain_tags=('retainage', 'rules'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=7,
        title='Advance Payment and Recovery',
        slug='advance_payment_and_recovery',
        domain_tags=('payment',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=8,
        title='Variation Order Lifecycle',
        slug='variation_order_lifecycle',
        domain_tags=('variation', 'order', 'lifecycle'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=9,
        title='Change Notice Timeliness',
        slug='change_notice_timeliness',
        domain_tags=('change', 'notice', 'timeliness'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=10,
        title='Commercial Claim Register',
        slug='commercial_claim_register',
        domain_tags=('claim',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=11,
        title='Delay and Time Impact Boundary',
        slug='delay_and_time_impact_boundary',
        domain_tags=('delay', 'impact', 'boundary'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=12,
        title='Quantum Calculation',
        slug='quantum_calculation',
        domain_tags=('quantum', 'calculation'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=13,
        title='Subcontract Package Lifecycle',
        slug='subcontract_package_lifecycle',
        domain_tags=('contract',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=14,
        title='Lien Waiver Governance',
        slug='lien_waiver_governance',
        domain_tags=('governance',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=15,
        title='Bonds and Guarantees',
        slug='bonds_and_guarantees',
        domain_tags=('bonds', 'guarantees'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=16,
        title='Insurance Compliance',
        slug='insurance_compliance',
        domain_tags=('compliance',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=17,
        title='Backcharge and Contra-Charge',
        slug='backcharge_and_contra_charge',
        domain_tags=('backcharge', 'contra_charge'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=18,
        title='Liquidated Damages and Incentives',
        slug='liquidated_damages_and_incentives',
        domain_tags=('liquidated', 'damages', 'incentives'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=19,
        title='Provisional Sums and Allowances',
        slug='provisional_sums_and_allowances',
        domain_tags=('provisional', 'allowances'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=20,
        title='Escalation and Price Adjustment',
        slug='escalation_and_price_adjustment',
        domain_tags=('escalation', 'price', 'adjustment'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=21,
        title='Tax and Withholding Boundary',
        slug='tax_and_withholding_boundary',
        domain_tags=('tax',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=22,
        title='Payment Certificate Generation',
        slug='payment_certificate_generation',
        domain_tags=('payment',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=23,
        title='Final Account Workflow',
        slug='final_account_workflow',
        domain_tags=('workflow',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=24,
        title='Dispute and Determination Tracking',
        slug='dispute_and_determination_tracking',
        domain_tags=('dispute', 'determination', 'tracking'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=25,
        title='Commercial Correspondence Evidence',
        slug='commercial_correspondence_evidence',
        domain_tags=('commercial', 'correspondence', 'evidence'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=26,
        title='Contract Clause Obligation Register',
        slug='contract_clause_obligation_register',
        domain_tags=('contract',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=27,
        title='Commercial Risk Register',
        slug='commercial_risk_register',
        domain_tags=('risk',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=28,
        title='Forecast Final Cost Boundary',
        slug='forecast_final_cost_boundary',
        domain_tags=('forecast',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=29,
        title='Cash Flow Forecast',
        slug='cash_flow_forecast',
        domain_tags=('cash', 'forecast'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=30,
        title='Contractor Performance Scorecard',
        slug='contractor_performance_scorecard',
        domain_tags=('contract',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=31,
        title='Commercial Controls Workbench',
        slug='commercial_controls_workbench',
        domain_tags=('commercial', 'controls', 'workbench'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=32,
        title='Agent-Assisted Contract Review',
        slug='agent_assisted_contract_review',
        domain_tags=('agent', 'contract'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=33,
        title='Governed Agent CRUD Commands',
        slug='governed_agent_crud_commands',
        domain_tags=('agent',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=34,
        title='Commercial Document Ingestion',
        slug='commercial_document_ingestion',
        domain_tags=('document',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=35,
        title='Change Impact Simulation',
        slug='change_impact_simulation',
        domain_tags=('change', 'impact', 'simulation'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=36,
        title='Continuous Control Assertions',
        slug='continuous_control_assertions',
        domain_tags=('continuous', 'control', 'assertions'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=37,
        title='Dead-Letter and Retry Operations',
        slug='dead_letter_and_retry_operations',
        domain_tags=('dead_letter', 'retry', 'operations'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=38,
        title='Cryptographic Commercial Evidence',
        slug='cryptographic_commercial_evidence',
        domain_tags=('cryptographic', 'commercial', 'evidence'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=39,
        title='Role-Based Permission Model',
        slug='role_based_permission_model',
        domain_tags=('model',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=40,
        title='Contractor Portal Contract',
        slug='contractor_portal_contract',
        domain_tags=('contract',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=41,
        title='Lien and Statutory Compliance Localization',
        slug='lien_and_statutory_compliance_localization',
        domain_tags=('compliance',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=42,
        title='Commercial Claim Analytics',
        slug='commercial_claim_analytics',
        domain_tags=('analytics', 'claim'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=43,
        title='Variation Trend Analytics',
        slug='variation_trend_analytics',
        domain_tags=('analytics',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=44,
        title='Final Account Evidence Packet',
        slug='final_account_evidence_packet',
        domain_tags=('final', 'account', 'evidence'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=45,
        title='Financial Handoff Boundary',
        slug='financial_handoff_boundary',
        domain_tags=('financial', 'handoff', 'boundary'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=46,
        title='Sustainability and Local Content Clauses',
        slug='sustainability_and_local_content_clauses',
        domain_tags=('sustainability', 'local', 'content'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=47,
        title='Seeded Commercial Scenario Library',
        slug='seeded_commercial_scenario_library',
        domain_tags=('seeded', 'commercial', 'scenario'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=48,
        title='Full Commercial Release Simulation',
        slug='full_commercial_release_simulation',
        domain_tags=('commercial', 'release', 'simulation'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=49,
        title='Package Overlap Guardrails',
        slug='package_overlap_guardrails',
        domain_tags=('package', 'overlap', 'guardrails'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=50,
        title='Composition DSL and Unified Agent Exposure',
        slug='composition_dsl_and_unified_agent_exposure',
        domain_tags=('agent',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
)



def capability_registry() -> dict:
    """Return side-effect-free registry metadata for improve1 capabilities."""
    rows = tuple(capability.as_traceability_row() for capability in IMPROVE1_CAPABILITIES)
    return {
        "ok": len(rows) == 50 and all(row["code_artifact_model"] and row["ui_surface"] and row["service_api"] and row["test"] and row["evidence"] for row in rows),
        "pbc": PBC_KEY,
        "capability_count": len(rows),
        "capabilities": rows,
        "side_effects": (),
    }


def plan_feature_execution(feature_number: int) -> dict:
    """Plan how a feature is exercised without mutating package state."""
    match = next((capability for capability in IMPROVE1_CAPABILITIES if capability.feature_number == feature_number), None)
    if match is None:
        return {"ok": False, "pbc": PBC_KEY, "reason": "unknown_feature", "side_effects": ()}
    return {
        "ok": True,
        "pbc": PBC_KEY,
        "feature_number": match.feature_number,
        "title": match.title,
        "slug": match.slug,
        "domain_tags": match.domain_tags,
        "model_artifacts": match.model_artifacts,
        "ui_artifacts": match.ui_artifacts,
        "service_artifacts": match.service_artifacts,
        "test_artifacts": match.test_artifacts,
        "evidence_artifacts": match.evidence_artifacts,
        "requires_configuration": match.configurable,
        "agent_assisted": match.agent_assisted,
        "side_effects": (),
    }


def validate_improve1_capabilities(expected_titles: tuple[str, ...]) -> dict:
    """Validate registry alignment with parsed improve1 titles."""
    actual_titles = tuple(capability.title for capability in IMPROVE1_CAPABILITIES)
    registry = capability_registry()
    return {
        "ok": len(actual_titles) == 50 and actual_titles == expected_titles and registry["ok"],
        "pbc": PBC_KEY,
        "expected_count": len(expected_titles),
        "actual_count": len(actual_titles),
        "titles_match": actual_titles == expected_titles,
        "registry_ok": registry["ok"],
        "side_effects": (),
    }
