"""Package manifest for the clinical_trials_management PBC."""

PBC_MANIFEST = {'advanced_capabilities': ('clinical_trials_management_event_sourced_operational_history',
                           'clinical_trials_management_multi_tenant_policy_isolation',
                           'clinical_trials_management_schema_evolution_resilience',
                           'clinical_trials_management_autonomous_anomaly_detection',
                           'clinical_trials_management_semantic_document_instruction_understanding',
                           'clinical_trials_management_predictive_risk_scoring',
                           'clinical_trials_management_counterfactual_scenario_simulation',
                           'clinical_trials_management_cryptographic_audit_proofs',
                           'clinical_trials_management_continuous_control_testing',
                           'clinical_trials_management_carbon_and_sustainability_awareness',
                           'clinical_trials_management_cross_pbc_event_federation',
                           'clinical_trials_management_governed_ai_agent_execution'),
 'analytics': ('clinical_trials_management_risk_score',
               'clinical_trials_management_workbench_metric'),
 'apis': ('POST /trial-protocols',
          'POST /study-sites',
          'POST /subjects',
          'POST /consent-records',
          'POST /visit-schedules',
          'GET /clinical-trials-management-workbench'),
 'capabilities': ('trial_protocol_management',
                  'clinical_trials_management_workflow',
                  'clinical_trials_management_analytics',
                  'configuration_schema',
                  'rule_engine',
                  'parameter_engine',
                  'owned_schema_migrations_models',
                  'appgen_x_outbox_inbox_eventing',
                  'idempotent_handlers',
                  'retry_dead_letter_evidence',
                  'permissions',
                  'seed_data',
                  'workbench',
                  'agentic_document_instruction_intake',
                  'governed_datastore_crud',
                  'ai_agent_task_assistance',
                  'configuration_workbench',
                  'continuous_release_assurance',
                  'clinical_trials_management_event_sourced_operational_history',
                  'clinical_trials_management_multi_tenant_policy_isolation',
                  'clinical_trials_management_schema_evolution_resilience',
                  'clinical_trials_management_autonomous_anomaly_detection',
                  'clinical_trials_management_semantic_document_instruction_understanding',
                  'clinical_trials_management_predictive_risk_scoring',
                  'clinical_trials_management_counterfactual_scenario_simulation',
                  'clinical_trials_management_cryptographic_audit_proofs',
                  'clinical_trials_management_continuous_control_testing',
                  'clinical_trials_management_carbon_and_sustainability_awareness',
                  'clinical_trials_management_cross_pbc_event_federation',
                  'clinical_trials_management_governed_ai_agent_execution'),
 'configuration': ('CLINICAL_TRIALS_MANAGEMENT_DATABASE_URL',
                   'CLINICAL_TRIALS_MANAGEMENT_EVENT_TOPIC',
                   'CLINICAL_TRIALS_MANAGEMENT_RETRY_LIMIT',
                   'CLINICAL_TRIALS_MANAGEMENT_DEFAULT_POLICY'),
 'consumes': ('PolicyChanged', 'CustomerUpdated', 'SupplierQualified'),
 'datastore_backend': 'postgresql',
 'description': 'Protocols, trial sites, subjects, consent, visits, adverse events, monitoring, '
                'and trial data operations',
 'docs': ('SPECIFICATION.md', 'RELEASE_EVIDENCE.md'),
 'emits': ('ClinicalTrialsManagementCreated',
           'ClinicalTrialsManagementUpdated',
           'ClinicalTrialsManagementApproved',
           'ClinicalTrialsManagementExceptionOpened'),
 'label': 'Clinical Trials Management',
 'mesh': 'relationship',
 'migrations': ('migrations/001_initial.sql',),
 'pbc': 'clinical_trials_management',
 'permissions': ('clinical_trials_management.read',
                 'clinical_trials_management.create',
                 'clinical_trials_management.update',
                 'clinical_trials_management.approve',
                 'clinical_trials_management.admin'),
 'seed_data': ('seed_data.py',),
 'standard_features': ('trial_protocol_management',
                       'clinical_trials_management_workflow',
                       'clinical_trials_management_analytics',
                       'configuration_schema',
                       'rule_engine',
                       'parameter_engine',
                       'owned_schema_migrations_models',
                       'appgen_x_outbox_inbox_eventing',
                       'idempotent_handlers',
                       'retry_dead_letter_evidence',
                       'permissions',
                       'seed_data',
                       'workbench',
                       'agentic_document_instruction_intake',
                       'governed_datastore_crud',
                       'ai_agent_task_assistance',
                       'configuration_workbench',
                       'continuous_release_assurance'),
 'tables': ('trial_protocol',
            'study_site',
            'subject',
            'consent_record',
            'visit_schedule',
            'adverse_event',
            'monitoring_finding',
            'clinical_trials_management_policy_rule',
            'clinical_trials_management_runtime_parameter',
            'clinical_trials_management_schema_extension',
            'clinical_trials_management_control_assertion',
            'clinical_trials_management_governed_model'),
 'template': 'workflow',
 'tests': ('tests/test_contract.py',),
 'ui_fragments': ('ClinicalTrialsManagementWorkbench',
                  'ClinicalTrialsManagementDetail',
                  'ClinicalTrialsManagementAssistantPanel'),
 'version': '1.0.0',
 'workflows': ('clinical_trials_management_create_trial_protocol_workflow',
               'clinical_trials_management_record_study_site_workflow')}
