"""Package manifest for the grant_fund_accounting PBC."""

PBC_MANIFEST = {'advanced_capabilities': ('grant_fund_accounting_event_sourced_operational_history',
                           'grant_fund_accounting_multi_tenant_policy_isolation',
                           'grant_fund_accounting_schema_evolution_resilience',
                           'grant_fund_accounting_autonomous_anomaly_detection',
                           'grant_fund_accounting_semantic_document_instruction_understanding',
                           'grant_fund_accounting_predictive_risk_scoring',
                           'grant_fund_accounting_counterfactual_scenario_simulation',
                           'grant_fund_accounting_cryptographic_audit_proofs',
                           'grant_fund_accounting_continuous_control_testing',
                           'grant_fund_accounting_carbon_and_sustainability_awareness',
                           'grant_fund_accounting_cross_pbc_event_federation',
                           'grant_fund_accounting_governed_ai_agent_execution'),
 'analytics': ('grant_fund_accounting_risk_score', 'grant_fund_accounting_workbench_metric'),
 'apis': ('POST /grant-awards',
          'POST /fund-restrictions',
          'POST /grant-budgets',
          'POST /reimbursement-claims',
          'GET /grant-fund-workbench'),
 'capabilities': ('grant_award_management',
                  'grant_fund_accounting_workflow',
                  'grant_fund_accounting_analytics',
                  'configuration_schema',
                  'rule_engine',
                  'parameter_engine',
                  'owned_schema_migrations_models',
                  'appgen_x_outbox_inbox_eventing',
                  'idempotent_handlers',
                  'retry_dead_letter_evidence',
                  'permissions',
                  'seed_data',
                  'workbench',
                  'agentic_document_instruction_intake',
                  'governed_datastore_crud',
                  'ai_agent_task_assistance',
                  'configuration_workbench',
                  'continuous_release_assurance',
                  'grant_fund_accounting_event_sourced_operational_history',
                  'grant_fund_accounting_multi_tenant_policy_isolation',
                  'grant_fund_accounting_schema_evolution_resilience',
                  'grant_fund_accounting_autonomous_anomaly_detection',
                  'grant_fund_accounting_semantic_document_instruction_understanding',
                  'grant_fund_accounting_predictive_risk_scoring',
                  'grant_fund_accounting_counterfactual_scenario_simulation',
                  'grant_fund_accounting_cryptographic_audit_proofs',
                  'grant_fund_accounting_continuous_control_testing',
                  'grant_fund_accounting_carbon_and_sustainability_awareness',
                  'grant_fund_accounting_cross_pbc_event_federation',
                  'grant_fund_accounting_governed_ai_agent_execution'),
 'configuration': ('GRANT_FUND_ACCOUNTING_DATABASE_URL',
                   'GRANT_FUND_ACCOUNTING_EVENT_TOPIC',
                   'GRANT_FUND_ACCOUNTING_RETRY_LIMIT',
                   'GRANT_FUND_ACCOUNTING_DEFAULT_POLICY'),
 'consumes': ('JournalPosted', 'ExpenseApproved', 'PaymentCaptured'),
 'datastore_backend': 'postgresql',
 'description': 'Restricted funds, grant budgets, donor rules, allowable costs, reimbursement '
                'claims, compliance reporting, and audit trails.',
 'docs': ('SPECIFICATION.md', 'RELEASE_EVIDENCE.md', 'README.md', 'implementation-plan.md', 'implementation-status.md'),
 'emits': ('GrantAwarded',
           'ReimbursementClaimPrepared',
           'FundRestrictionApplied',
           'GrantComplianceReported'),
 'label': 'Grant and Fund Accounting',
 'mesh': 'finops',
 'migrations': ('migrations/001_initial.sql',),
 'pbc': 'grant_fund_accounting',
 'permissions': ('grant_fund_accounting.read',
                 'grant_fund_accounting.create',
                 'grant_fund_accounting.update',
                 'grant_fund_accounting.approve',
                 'grant_fund_accounting.admin'),
 'seed_data': ('seed_data.py',),
 'standard_features': ('grant_award_management',
 'grant_fund_accounting_workflow',
 'grant_fund_accounting_analytics',
 'configuration_schema',
 'rule_engine',
 'parameter_engine',
 'owned_schema_migrations_models',
 'appgen_x_outbox_inbox_eventing',
 'idempotent_handlers',
 'retry_dead_letter_evidence',
 'permissions',
 'seed_data',
 'workbench',
 'agentic_document_instruction_intake',
 'governed_datastore_crud',
 'ai_agent_task_assistance',
 'configuration_workbench',
 'continuous_release_assurance'),
 'tables': ('grant_award',
            'fund_restriction',
            'grant_budget',
            'donor_rule',
            'allowable_cost',
            'reimbursement_claim',
            'grant_compliance_report',
            'fund_audit_trail'),
 'template': 'accounting',
 'tests': ('tests/test_contract.py', 'tests/test_standalone.py'),
 'ui_fragments': ('GrantFundAccountingWorkbench',
                  'GrantFundAccountingDetail',
                  'GrantFundAccountingAssistantPanel'),
 'version': '1.0.0',
 'workflows': ('grant_award_workflow', 'grant_fund_accounting_approval_workflow', 'grant_award_intake_workflow', 'grant_cost_allowability_workflow', 'grant_drawdown_reconciliation_workflow', 'grant_funder_report_workflow', 'grant_closeout_workflow')}
