"""Package manifest for the chemical_batch_compliance PBC."""

PBC_MANIFEST = {'advanced_capabilities': ('chemical_batch_compliance_event_sourced_operational_history',
                           'chemical_batch_compliance_multi_tenant_policy_isolation',
                           'chemical_batch_compliance_schema_evolution_resilience',
                           'chemical_batch_compliance_autonomous_anomaly_detection',
                           'chemical_batch_compliance_semantic_document_instruction_understanding',
                           'chemical_batch_compliance_predictive_risk_scoring',
                           'chemical_batch_compliance_counterfactual_scenario_simulation',
                           'chemical_batch_compliance_cryptographic_audit_proofs',
                           'chemical_batch_compliance_continuous_control_testing',
                           'chemical_batch_compliance_carbon_and_sustainability_awareness',
                           'chemical_batch_compliance_cross_pbc_event_federation',
                           'chemical_batch_compliance_governed_ai_agent_execution'),
 'analytics': ('chemical_batch_compliance_risk_score',
               'chemical_batch_compliance_workbench_metric'),
 'apis': ('POST /chemical-formulas',
          'POST /batch-records',
          'POST /sds-documents',
          'POST /hazardous-materials',
          'POST /regulatory-submissions',
          'GET /chemical-batch-compliance-workbench'),
 'capabilities': ('chemical_formula_management',
                  'chemical_batch_compliance_workflow',
                  'chemical_batch_compliance_analytics',
                  'configuration_schema',
                  'rule_engine',
                  'parameter_engine',
                  'owned_schema_migrations_models',
                  'appgen_x_outbox_inbox_eventing',
                  'idempotent_handlers',
                  'retry_dead_letter_evidence',
                  'permissions',
                  'seed_data',
                  'workbench',
                  'agentic_document_instruction_intake',
                  'governed_datastore_crud',
                  'ai_agent_task_assistance',
                  'configuration_workbench',
                  'continuous_release_assurance',
                  'chemical_batch_compliance_event_sourced_operational_history',
                  'chemical_batch_compliance_multi_tenant_policy_isolation',
                  'chemical_batch_compliance_schema_evolution_resilience',
                  'chemical_batch_compliance_autonomous_anomaly_detection',
                  'chemical_batch_compliance_semantic_document_instruction_understanding',
                  'chemical_batch_compliance_predictive_risk_scoring',
                  'chemical_batch_compliance_counterfactual_scenario_simulation',
                  'chemical_batch_compliance_cryptographic_audit_proofs',
                  'chemical_batch_compliance_continuous_control_testing',
                  'chemical_batch_compliance_carbon_and_sustainability_awareness',
                  'chemical_batch_compliance_cross_pbc_event_federation',
                  'chemical_batch_compliance_governed_ai_agent_execution'),
 'configuration': ('CHEMICAL_BATCH_COMPLIANCE_DATABASE_URL',
                   'CHEMICAL_BATCH_COMPLIANCE_EVENT_TOPIC',
                   'CHEMICAL_BATCH_COMPLIANCE_RETRY_LIMIT',
                   'CHEMICAL_BATCH_COMPLIANCE_DEFAULT_POLICY'),
 'consumes': ('PolicyChanged', 'AuditEventSealed', 'OperationalKpiChanged'),
 'datastore_backend': 'postgresql',
 'description': 'Chemical formulas, batches, SDS, hazardous materials, regulatory submissions, '
                'quality, and compliance controls',
 'docs': ('SPECIFICATION.md', 'RELEASE_EVIDENCE.md'),
 'emits': ('ChemicalBatchComplianceCreated',
           'ChemicalBatchComplianceUpdated',
           'ChemicalBatchComplianceApproved',
           'ChemicalBatchComplianceExceptionOpened'),
 'label': 'Chemical Batch Compliance',
 'mesh': 'opsmfg',
 'migrations': ('migrations/001_initial.sql',),
 'pbc': 'chemical_batch_compliance',
 'permissions': ('chemical_batch_compliance.read',
                 'chemical_batch_compliance.create',
                 'chemical_batch_compliance.update',
                 'chemical_batch_compliance.approve',
                 'chemical_batch_compliance.admin'),
 'seed_data': ('seed_data.py',),
 'standard_features': ('chemical_formula_management',
                       'chemical_batch_compliance_workflow',
                       'chemical_batch_compliance_analytics',
                       'configuration_schema',
                       'rule_engine',
                       'parameter_engine',
                       'owned_schema_migrations_models',
                       'appgen_x_outbox_inbox_eventing',
                       'idempotent_handlers',
                       'retry_dead_letter_evidence',
                       'permissions',
                       'seed_data',
                       'workbench',
                       'agentic_document_instruction_intake',
                       'governed_datastore_crud',
                       'ai_agent_task_assistance',
                       'configuration_workbench',
                       'continuous_release_assurance'),
 'tables': ('chemical_formula',
            'batch_record',
            'sds_document',
            'hazardous_material',
            'regulatory_submission',
            'quality_test',
            'compliance_hold',
            'chemical_batch_compliance_policy_rule',
            'chemical_batch_compliance_runtime_parameter',
            'chemical_batch_compliance_schema_extension',
            'chemical_batch_compliance_control_assertion',
            'chemical_batch_compliance_governed_model'),
 'template': 'asset',
 'tests': ('tests/test_contract.py',),
 'ui_fragments': ('ChemicalBatchComplianceWorkbench',
                  'ChemicalBatchComplianceDetail',
                  'ChemicalBatchComplianceAssistantPanel'),
 'version': '1.0.0',
 'workflows': ('chemical_batch_compliance_create_chemical_formula_workflow',
               'chemical_batch_compliance_record_batch_record_workflow')}
