"""Executable improve1 capability registry for this PBC.

This module turns the package-local improve1 backlog into code-level evidence.
It is intentionally side-effect free: callers can inspect capability coverage, plan
execution, and verify surface mappings without touching external systems.
"""

from __future__ import annotations

from dataclasses import dataclass

PBC_KEY = 'privacy_consent_governance'


@dataclass(frozen=True)
class Improve1Capability:
    feature_number: int
    title: str
    slug: str
    domain_tags: tuple[str, ...]
    model_artifacts: tuple[str, ...]
    ui_artifacts: tuple[str, ...]
    service_artifacts: tuple[str, ...]
    test_artifacts: tuple[str, ...]
    evidence_artifacts: tuple[str, ...]
    configurable: bool = True
    agent_assisted: bool = True
    side_effect_free_plan: bool = True

    def as_traceability_row(self) -> dict:
        return {
            "feature_number": self.feature_number,
            "title": self.title,
            "slug": self.slug,
            "domain_tags": self.domain_tags,
            "code_artifact_model": self.model_artifacts,
            "ui_surface": self.ui_artifacts,
            "service_api": self.service_artifacts,
            "test": self.test_artifacts,
            "evidence": self.evidence_artifacts,
            "configurable": self.configurable,
            "agent_assisted": self.agent_assisted,
            "side_effect_free_plan": self.side_effect_free_plan,
        }



IMPROVE1_CAPABILITIES: tuple[Improve1Capability, ...] = (
    Improve1Capability(
        feature_number=1,
        title='Consent subject identity graph',
        slug='consent_subject_identity_graph',
        domain_tags=('consent', 'identity'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=2,
        title='Subject lifecycle state machine',
        slug='subject_lifecycle_state_machine',
        domain_tags=('subject', 'lifecycle', 'state'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=3,
        title='Consent grant timeline',
        slug='consent_grant_timeline',
        domain_tags=('consent',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=4,
        title='Consent withdrawal impact simulation',
        slug='consent_withdrawal_impact_simulation',
        domain_tags=('consent',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=5,
        title='Purpose taxonomy governance',
        slug='purpose_taxonomy_governance',
        domain_tags=('governance', 'tax'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=6,
        title='Purpose-conflict detection',
        slug='purpose_conflict_detection',
        domain_tags=('purpose_conflict', 'detection'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=7,
        title='Privacy notice version control',
        slug='privacy_notice_version_control',
        domain_tags=('privacy',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=8,
        title='Notice acknowledgement proof',
        slug='notice_acknowledgement_proof',
        domain_tags=('notice', 'acknowledgement', 'proof'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=9,
        title='Notice reacknowledgement orchestration',
        slug='notice_reacknowledgement_orchestration',
        domain_tags=('orchestration',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=10,
        title='Data subject request intake gate',
        slug='data_subject_request_intake_gate',
        domain_tags=('subject', 'request', 'intake'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=11,
        title='DSR workflow automation',
        slug='dsr_workflow_automation',
        domain_tags=('workflow',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=12,
        title='Authorized agent and proxy handling',
        slug='authorized_agent_and_proxy_handling',
        domain_tags=('agent',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=13,
        title='DSR identity verification risk scoring',
        slug='dsr_identity_verification_risk_scoring',
        domain_tags=('identity', 'risk'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=14,
        title='DSR response package builder',
        slug='dsr_response_package_builder',
        domain_tags=('response', 'package', 'builder'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=15,
        title='DSR SLA and extension governance',
        slug='dsr_sla_and_extension_governance',
        domain_tags=('governance',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=16,
        title='Processing activity register completeness',
        slug='processing_activity_register_completeness',
        domain_tags=('processing', 'activity', 'register'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=17,
        title='Processing basis validation',
        slug='processing_basis_validation',
        domain_tags=('processing', 'basis', 'validation'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=18,
        title='Legitimate interest assessment workflow',
        slug='legitimate_interest_assessment_workflow',
        domain_tags=('workflow',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=19,
        title='Special category and sensitive data controls',
        slug='special_category_and_sensitive_data_controls',
        domain_tags=('special', 'category', 'sensitive'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=20,
        title='Data sharing agreement governance',
        slug='data_sharing_agreement_governance',
        domain_tags=('governance',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=21,
        title='Cross-border transfer controls',
        slug='cross_border_transfer_controls',
        domain_tags=('cross_border', 'transfer', 'controls'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=22,
        title='Data product privacy review',
        slug='data_product_privacy_review',
        domain_tags=('privacy',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=23,
        title='Retention schedule governance',
        slug='retention_schedule_governance',
        domain_tags=('governance', 'schedule'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=24,
        title='Retention decision traceability',
        slug='retention_decision_traceability',
        domain_tags=('traceability',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=25,
        title='Retention impact simulation',
        slug='retention_impact_simulation',
        domain_tags=('retention', 'impact', 'simulation'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=26,
        title='Privacy risk assessment workflow',
        slug='privacy_risk_assessment_workflow',
        domain_tags=('privacy', 'risk', 'workflow'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=27,
        title='DPIA/PIA template library',
        slug='dpia_pia_template_library',
        domain_tags=('template', 'library'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=28,
        title='Privacy incident lifecycle',
        slug='privacy_incident_lifecycle',
        domain_tags=('privacy',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=29,
        title='Breach notification decision support',
        slug='breach_notification_decision_support',
        domain_tags=('notification',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=30,
        title='Consent evidence packet',
        slug='consent_evidence_packet',
        domain_tags=('consent',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=31,
        title='Cryptographic consent proof',
        slug='cryptographic_consent_proof',
        domain_tags=('consent',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=32,
        title='Privacy policy semantic compiler',
        slug='privacy_policy_semantic_compiler',
        domain_tags=('policy', 'privacy'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=33,
        title='Policy change impact analysis',
        slug='policy_change_impact_analysis',
        domain_tags=('policy',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=34,
        title='Consent lineage graph',
        slug='consent_lineage_graph',
        domain_tags=('consent',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=35,
        title='Data minimization controls',
        slug='data_minimization_controls',
        domain_tags=('minimization', 'controls'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=36,
        title='Privacy control testing library',
        slug='privacy_control_testing_library',
        domain_tags=('privacy',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=37,
        title='Consent and purpose anomaly detection',
        slug='consent_and_purpose_anomaly_detection',
        domain_tags=('consent',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=38,
        title='Privacy exception case workflow',
        slug='privacy_exception_case_workflow',
        domain_tags=('case', 'privacy', 'workflow'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=39,
        title='Subject communication preference integration',
        slug='subject_communication_preference_integration',
        domain_tags=('subject', 'communication', 'preference'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=40,
        title='Children and vulnerable subject safeguards',
        slug='children_and_vulnerable_subject_safeguards',
        domain_tags=('children', 'vulnerable', 'subject'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=41,
        title='AppGen-X event reliability proof',
        slug='appgen_x_event_reliability_proof',
        domain_tags=('event',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=42,
        title='Cross-PBC boundary proof',
        slug='cross_pbc_boundary_proof',
        domain_tags=('cross_pbc', 'boundary', 'proof'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=43,
        title='Agent-assisted DSR handling',
        slug='agent_assisted_dsr_handling',
        domain_tags=('agent',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=44,
        title='Agent-assisted privacy policy mapping',
        slug='agent_assisted_privacy_policy_mapping',
        domain_tags=('agent', 'policy', 'privacy'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=45,
        title='Privacy workbench cockpit',
        slug='privacy_workbench_cockpit',
        domain_tags=('privacy',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=46,
        title='UI capability surface proof',
        slug='ui_capability_surface_proof',
        domain_tags=('capability', 'surface', 'proof'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=47,
        title='Privacy resilience drills',
        slug='privacy_resilience_drills',
        domain_tags=('privacy',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=48,
        title='Privacy readiness score',
        slug='privacy_readiness_score',
        domain_tags=('privacy',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=49,
        title='Multi-tenant privacy isolation proof',
        slug='multi_tenant_privacy_isolation_proof',
        domain_tags=('privacy',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
    Improve1Capability(
        feature_number=50,
        title='End-to-end privacy release proof',
        slug='end_to_end_privacy_release_proof',
        domain_tags=('privacy',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'SPECIFICATION.md'),
    ),
)



def capability_registry() -> dict:
    """Return side-effect-free registry metadata for improve1 capabilities."""
    rows = tuple(capability.as_traceability_row() for capability in IMPROVE1_CAPABILITIES)
    return {
        "ok": len(rows) == 50 and all(row["code_artifact_model"] and row["ui_surface"] and row["service_api"] and row["test"] and row["evidence"] for row in rows),
        "pbc": PBC_KEY,
        "capability_count": len(rows),
        "capabilities": rows,
        "side_effects": (),
    }


def plan_feature_execution(feature_number: int) -> dict:
    """Plan how a feature is exercised without mutating package state."""
    match = next((capability for capability in IMPROVE1_CAPABILITIES if capability.feature_number == feature_number), None)
    if match is None:
        return {"ok": False, "pbc": PBC_KEY, "reason": "unknown_feature", "side_effects": ()}
    return {
        "ok": True,
        "pbc": PBC_KEY,
        "feature_number": match.feature_number,
        "title": match.title,
        "slug": match.slug,
        "domain_tags": match.domain_tags,
        "model_artifacts": match.model_artifacts,
        "ui_artifacts": match.ui_artifacts,
        "service_artifacts": match.service_artifacts,
        "test_artifacts": match.test_artifacts,
        "evidence_artifacts": match.evidence_artifacts,
        "requires_configuration": match.configurable,
        "agent_assisted": match.agent_assisted,
        "side_effects": (),
    }


def validate_improve1_capabilities(expected_titles: tuple[str, ...]) -> dict:
    """Validate registry alignment with parsed improve1 titles."""
    actual_titles = tuple(capability.title for capability in IMPROVE1_CAPABILITIES)
    registry = capability_registry()
    return {
        "ok": len(actual_titles) == 50 and actual_titles == expected_titles and registry["ok"],
        "pbc": PBC_KEY,
        "expected_count": len(expected_titles),
        "actual_count": len(actual_titles),
        "titles_match": actual_titles == expected_titles,
        "registry_ok": registry["ok"],
        "side_effects": (),
    }
