"""Package manifest for the donor_grant_fundraising PBC."""

PBC_MANIFEST = {'advanced_capabilities': ('donor_grant_fundraising_event_sourced_operational_history',
                           'donor_grant_fundraising_multi_tenant_policy_isolation',
                           'donor_grant_fundraising_schema_evolution_resilience',
                           'donor_grant_fundraising_autonomous_anomaly_detection',
                           'donor_grant_fundraising_semantic_document_instruction_understanding',
                           'donor_grant_fundraising_predictive_risk_scoring',
                           'donor_grant_fundraising_counterfactual_scenario_simulation',
                           'donor_grant_fundraising_cryptographic_audit_proofs',
                           'donor_grant_fundraising_continuous_control_testing',
                           'donor_grant_fundraising_carbon_and_sustainability_awareness',
                           'donor_grant_fundraising_cross_pbc_event_federation',
                           'donor_grant_fundraising_governed_ai_agent_execution'),
 'analytics': ('donor_grant_fundraising_risk_score', 'donor_grant_fundraising_workbench_metric'),
 'apis': ('POST /donors',
          'POST /campaigns',
          'POST /pledges',
          'POST /gifts',
          'POST /restrictions',
          'GET /donor-grant-fundraising-workbench'),
 'capabilities': ('donor_management',
                  'donor_grant_fundraising_workflow',
                  'donor_grant_fundraising_analytics',
                  'configuration_schema',
                  'rule_engine',
                  'parameter_engine',
                  'owned_schema_migrations_models',
                  'appgen_x_outbox_inbox_eventing',
                  'idempotent_handlers',
                  'retry_dead_letter_evidence',
                  'permissions',
                  'seed_data',
                  'workbench',
                  'agentic_document_instruction_intake',
                  'governed_datastore_crud',
                  'ai_agent_task_assistance',
                  'configuration_workbench',
                  'continuous_release_assurance',
                  'donor_grant_fundraising_event_sourced_operational_history',
                  'donor_grant_fundraising_multi_tenant_policy_isolation',
                  'donor_grant_fundraising_schema_evolution_resilience',
                  'donor_grant_fundraising_autonomous_anomaly_detection',
                  'donor_grant_fundraising_semantic_document_instruction_understanding',
                  'donor_grant_fundraising_predictive_risk_scoring',
                  'donor_grant_fundraising_counterfactual_scenario_simulation',
                  'donor_grant_fundraising_cryptographic_audit_proofs',
                  'donor_grant_fundraising_continuous_control_testing',
                  'donor_grant_fundraising_carbon_and_sustainability_awareness',
                  'donor_grant_fundraising_cross_pbc_event_federation',
                  'donor_grant_fundraising_governed_ai_agent_execution'),
 'configuration': ('DONOR_GRANT_FUNDRAISING_DATABASE_URL',
                   'DONOR_GRANT_FUNDRAISING_EVENT_TOPIC',
                   'DONOR_GRANT_FUNDRAISING_RETRY_LIMIT',
                   'DONOR_GRANT_FUNDRAISING_DEFAULT_POLICY'),
 'consumes': ('PolicyChanged', 'CustomerUpdated', 'SupplierQualified'),
 'datastore_backend': 'postgresql',
 'description': 'Donors, campaigns, pledges, restrictions, gifts, grant applications, stewardship, '
                'and impact reporting',
 'docs': ('SPECIFICATION.md', 'RELEASE_EVIDENCE.md'),
 'emits': ('DonorGrantFundraisingCreated',
           'DonorGrantFundraisingUpdated',
           'DonorGrantFundraisingApproved',
           'DonorGrantFundraisingExceptionOpened'),
 'label': 'Donor Grant and Fundraising',
 'mesh': 'relationship',
 'migrations': ('migrations/001_initial.sql',),
 'pbc': 'donor_grant_fundraising',
 'permissions': ('donor_grant_fundraising.read',
                 'donor_grant_fundraising.create',
                 'donor_grant_fundraising.update',
                 'donor_grant_fundraising.approve',
                 'donor_grant_fundraising.admin'),
 'seed_data': ('seed_data.py',),
 'standard_features': ('donor_management',
                       'donor_grant_fundraising_workflow',
                       'donor_grant_fundraising_analytics',
                       'configuration_schema',
                       'rule_engine',
                       'parameter_engine',
                       'owned_schema_migrations_models',
                       'appgen_x_outbox_inbox_eventing',
                       'idempotent_handlers',
                       'retry_dead_letter_evidence',
                       'permissions',
                       'seed_data',
                       'workbench',
                       'agentic_document_instruction_intake',
                       'governed_datastore_crud',
                       'ai_agent_task_assistance',
                       'configuration_workbench',
                       'continuous_release_assurance'),
 'tables': ('donor',
            'campaign',
            'pledge',
            'gift',
            'restriction',
            'grant_application',
            'stewardship_touchpoint',
            'donor_grant_fundraising_policy_rule',
            'donor_grant_fundraising_runtime_parameter',
            'donor_grant_fundraising_schema_extension',
            'donor_grant_fundraising_control_assertion',
            'donor_grant_fundraising_governed_model'),
 'template': 'workflow',
 'tests': ('tests/test_contract.py',),
 'ui_fragments': ('DonorGrantFundraisingWorkbench',
                  'DonorGrantFundraisingDetail',
                  'DonorGrantFundraisingAssistantPanel'),
 'version': '1.0.0',
 'workflows': ('donor_grant_fundraising_create_donor_workflow',
               'donor_grant_fundraising_record_campaign_workflow')}
