"""Owned model metadata for the inventory_positioning PBC."""

PBC_KEY = 'inventory_positioning'
OWNED_SCHEMA = {'schema': 'inventory_positioning',
 'table_prefix': 'inventory_positioning_',
 'tables': ({'logical_table': 'item',
             'owned_table': 'inventory_positioning_item',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'sku', 'type': 'string', 'required': True},
                        {'name': 'uom', 'type': 'string', 'required': True},
                        {'name': 'lot_tracked', 'type': 'string', 'required': True},
                        {'name': 'serial_tracked', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'item_attribute',
             'owned_table': 'inventory_positioning_item_attribute',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'attribute_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'name', 'type': 'string', 'required': True},
                        {'name': 'value', 'type': 'string', 'required': True},
                        {'name': 'source', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'item_id',
                                'target_table': 'inventory_positioning_item',
                                'target_column': 'item_id',
                                'cardinality': 'owned_child',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'item_substitution',
             'owned_table': 'inventory_positioning_item_substitution',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'substitution_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'substitute_item_id', 'type': 'string', 'required': True},
                        {'name': 'priority', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'lot',
             'owned_table': 'inventory_positioning_lot',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'lot_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'expires', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'trace_hash', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'item_id',
                                'target_table': 'inventory_positioning_item',
                                'target_column': 'item_id',
                                'cardinality': 'owned_lot',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'serial',
             'owned_table': 'inventory_positioning_serial',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'serial_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'lot_id', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'node_id', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'lot_id',
                                'target_table': 'inventory_positioning_lot',
                                'target_column': 'lot_id',
                                'cardinality': 'owned_serial',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'node',
             'owned_table': 'inventory_positioning_node',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'node_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'node_type', 'type': 'string', 'required': True},
                        {'name': 'country', 'type': 'string', 'required': True},
                        {'name': 'region', 'type': 'string', 'required': True},
                        {'name': 'calendar', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'node_calendar',
             'owned_table': 'inventory_positioning_node_calendar',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'calendar_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'node_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'timezone', 'type': 'string', 'required': True},
                        {'name': 'working_days', 'type': 'string', 'required': True},
                        {'name': 'cutoff_time', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'node_id',
                                'target_table': 'inventory_positioning_node',
                                'target_column': 'node_id',
                                'cardinality': 'owned_calendar',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'node_capacity',
             'owned_table': 'inventory_positioning_node_capacity',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'capacity_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'node_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True},
                        {'name': 'daily_capacity', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'node_identity',
             'owned_table': 'inventory_positioning_node_identity',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'identity_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'node_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'did', 'type': 'string', 'required': True},
                        {'name': 'issuer', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'inventory_position',
             'owned_table': 'inventory_positioning_inventory_position',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'position_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'node_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True},
                        {'name': 'on_hand', 'type': 'string', 'required': True},
                        {'name': 'reserved', 'type': 'string', 'required': True},
                        {'name': 'quarantine', 'type': 'string', 'required': True},
                        {'name': 'in_transit', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'item_id',
                                'target_table': 'inventory_positioning_item',
                                'target_column': 'item_id',
                                'cardinality': 'owned_position',
                                'ownership': 'same_pbc'},
                               {'field': 'node_id',
                                'target_table': 'inventory_positioning_node',
                                'target_column': 'node_id',
                                'cardinality': 'owned_position',
                                'ownership': 'same_pbc'})},
            {'logical_table': 'position_snapshot',
             'owned_table': 'inventory_positioning_position_snapshot',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'snapshot_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'position_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'as_of', 'type': 'string', 'required': True},
                        {'name': 'on_hand', 'type': 'string', 'required': True},
                        {'name': 'available', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'receipt',
             'owned_table': 'inventory_positioning_receipt',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'receipt_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'node_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True},
                        {'name': 'quantity', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'receipt_line',
             'owned_table': 'inventory_positioning_receipt_line',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'receipt_line_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'receipt_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True},
                        {'name': 'quantity', 'type': 'string', 'required': True},
                        {'name': 'lot_id', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'receipt_id',
                                'target_table': 'inventory_positioning_receipt',
                                'target_column': 'receipt_id',
                                'cardinality': 'owned_child',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'adjustment',
             'owned_table': 'inventory_positioning_adjustment',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'adjustment_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'node_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True},
                        {'name': 'quantity', 'type': 'string', 'required': True},
                        {'name': 'reason', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'cycle_count',
             'owned_table': 'inventory_positioning_cycle_count',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'cycle_count_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'node_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True},
                        {'name': 'physical_count', 'type': 'integer', 'required': True},
                        {'name': 'variance', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'reservation',
             'owned_table': 'inventory_positioning_reservation',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'reservation_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'order_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True},
                        {'name': 'quantity', 'type': 'string', 'required': True},
                        {'name': 'expires_at', 'type': 'datetime', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'allocation',
             'owned_table': 'inventory_positioning_allocation',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'allocation_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'order_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True},
                        {'name': 'quantity_allocated', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'allocation_line',
             'owned_table': 'inventory_positioning_allocation_line',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'allocation_line_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'allocation_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'node_id', 'type': 'string', 'required': True},
                        {'name': 'lot_id', 'type': 'string', 'required': True},
                        {'name': 'quantity', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'allocation_id',
                                'target_table': 'inventory_positioning_allocation',
                                'target_column': 'allocation_id',
                                'cardinality': 'owned_child',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'allocation_expiry',
             'owned_table': 'inventory_positioning_allocation_expiry',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'expiry_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'allocation_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'expires_at', 'type': 'datetime', 'required': True},
                        {'name': 'released', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'quality_hold',
             'owned_table': 'inventory_positioning_quality_hold',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'hold_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'node_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True},
                        {'name': 'quantity', 'type': 'string', 'required': True},
                        {'name': 'reason', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'quality_release',
             'owned_table': 'inventory_positioning_quality_release',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'release_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'hold_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'released_by', 'type': 'string', 'required': True},
                        {'name': 'released_at', 'type': 'datetime', 'required': True},
                        {'name': 'evidence_hash', 'type': 'json', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ({'field': 'hold_id',
                                'target_table': 'inventory_positioning_quality_hold',
                                'target_column': 'hold_id',
                                'cardinality': 'owned_release',
                                'ownership': 'same_pbc'},)},
            {'logical_table': 'in_transit_projection',
             'owned_table': 'inventory_positioning_in_transit_projection',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'transit_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'quantity', 'type': 'string', 'required': True},
                        {'name': 'confidence', 'type': 'decimal', 'required': True},
                        {'name': 'eta_days', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'traceability_event',
             'owned_table': 'inventory_positioning_traceability_event',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'trace_event_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'lot_id', 'type': 'string', 'required': True},
                        {'name': 'event_type', 'type': 'string', 'required': True},
                        {'name': 'trace_hash', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'backorder',
             'owned_table': 'inventory_positioning_backorder',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'backorder_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'order_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True},
                        {'name': 'quantity', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'replenishment_signal',
             'owned_table': 'inventory_positioning_replenishment_signal',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'signal_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'recommended_quantity', 'type': 'string', 'required': True},
                        {'name': 'reason', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'replenishment_plan',
             'owned_table': 'inventory_positioning_replenishment_plan',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'plan_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'node_id', 'type': 'string', 'required': True},
                        {'name': 'quantity', 'type': 'string', 'required': True},
                        {'name': 'due_date', 'type': 'datetime', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'reconciliation',
             'owned_table': 'inventory_positioning_reconciliation',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'reconciliation_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'ledger', 'type': 'string', 'required': True},
                        {'name': 'physical_count', 'type': 'integer', 'required': True},
                        {'name': 'variance', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'policy_screening',
             'owned_table': 'inventory_positioning_policy_screening',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'screening_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'decision', 'type': 'string', 'required': True},
                        {'name': 'policy', 'type': 'string', 'required': True},
                        {'name': 'evidence_hash', 'type': 'json', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'stock_proof',
             'owned_table': 'inventory_positioning_stock_proof',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'proof_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'proof_hash', 'type': 'string', 'required': True},
                        {'name': 'public_claims', 'type': 'json', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'cross_node_federation',
             'owned_table': 'inventory_positioning_cross_node_federation',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'federation_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'external_system', 'type': 'string', 'required': True},
                        {'name': 'projection_hash', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'carbon_fulfillment',
             'owned_table': 'inventory_positioning_carbon_fulfillment',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'carbon_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'node_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'carbon_intensity', 'type': 'string', 'required': True},
                        {'name': 'selected', 'type': 'string', 'required': True},
                        {'name': 'scheduled_at', 'type': 'datetime', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'channel_allocation',
             'owned_table': 'inventory_positioning_channel_allocation',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'channel_allocation_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'channel', 'type': 'string', 'required': True},
                        {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'quantity', 'type': 'string', 'required': True},
                        {'name': 'clearing_bid', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'anomaly_signal',
             'owned_table': 'inventory_positioning_anomaly_signal',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'signal_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'entropy', 'type': 'string', 'required': True},
                        {'name': 'observed_at', 'type': 'datetime', 'required': True},
                        {'name': 'decision', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'stock_risk_model',
             'owned_table': 'inventory_positioning_stock_risk_model',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'risk_model_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'risk_score', 'type': 'decimal', 'required': True},
                        {'name': 'model_version', 'type': 'string', 'required': True},
                        {'name': 'explanations', 'type': 'json', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'seed_data',
             'owned_table': 'inventory_positioning_seed_data',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'seed_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'node_type', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'uom', 'type': 'string', 'required': True},
                        {'name': 'allocation_policy', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'schema_extension',
             'owned_table': 'inventory_positioning_schema_extension',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'extension_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'table_name', 'type': 'string', 'required': True},
                        {'name': 'field_name', 'type': 'string', 'required': True},
                        {'name': 'field_type', 'type': 'string', 'required': True},
                        {'name': 'version', 'type': 'integer', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'control_assertion',
             'owned_table': 'inventory_positioning_control_assertion',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'control_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'assertion', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'evidence_hash', 'type': 'json', 'required': True},
                        {'name': 'tested_at', 'type': 'datetime', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'governed_model',
             'owned_table': 'inventory_positioning_governed_model',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'model_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'name', 'type': 'string', 'required': True},
                        {'name': 'feature_lineage', 'type': 'string', 'required': True},
                        {'name': 'drift_score', 'type': 'decimal', 'required': True},
                        {'name': 'governance_status', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'rule',
             'owned_table': 'inventory_positioning_rule',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'rule_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
                        {'name': 'scope', 'type': 'string', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'predicate', 'type': 'json', 'required': True},
                        {'name': 'compiled_hash', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'parameter',
             'owned_table': 'inventory_positioning_parameter',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'parameter_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'name', 'type': 'string', 'required': True},
                        {'name': 'value', 'type': 'string', 'required': True},
                        {'name': 'bounds', 'type': 'string', 'required': True},
                        {'name': 'compiled_hash', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'configuration',
             'owned_table': 'inventory_positioning_configuration',
             'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
                        {'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'configuration_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'database_backend', 'type': 'string', 'required': True},
                        {'name': 'event_topic', 'type': 'string', 'required': True},
                        {'name': 'retry_limit', 'type': 'string', 'required': True},
                        {'name': 'default_uom', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'appgen_outbox_event',
             'owned_table': 'inventory_positioning_appgen_outbox_event',
             'fields': ({'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'event_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'event_type', 'type': 'string', 'required': True},
                        {'name': 'topic', 'type': 'string', 'required': True},
                        {'name': 'idempotency_key', 'type': 'string', 'required': True},
                        {'name': 'audit_hash', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'appgen_inbox_event',
             'owned_table': 'inventory_positioning_appgen_inbox_event',
             'fields': ({'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'event_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'event_type', 'type': 'string', 'required': True},
                        {'name': 'idempotency_key', 'type': 'string', 'required': True},
                        {'name': 'attempts', 'type': 'integer', 'required': True},
                        {'name': 'status', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()},
            {'logical_table': 'dead_letter_event',
             'owned_table': 'inventory_positioning_dead_letter_event',
             'fields': ({'name': 'tenant', 'type': 'string', 'required': True},
                        {'name': 'event_id',
                         'type': 'string',
                         'required': True,
                         'primary_key': True,
                         'nullable': False},
                        {'name': 'event_type', 'type': 'string', 'required': True},
                        {'name': 'idempotency_key', 'type': 'string', 'required': True},
                        {'name': 'attempts', 'type': 'integer', 'required': True},
                        {'name': 'reason', 'type': 'string', 'required': True},
                        {'name': 'created_at', 'type': 'datetime', 'required': True},
                        {'name': 'updated_at', 'type': 'datetime', 'required': True}),
             'relationships': ()})}
MODELS = ({'class_name': 'InventoryPositioningItem',
  'table': 'inventory_positioning_item',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'sku', 'type': 'string', 'required': True},
             {'name': 'uom', 'type': 'string', 'required': True},
             {'name': 'lot_tracked', 'type': 'string', 'required': True},
             {'name': 'serial_tracked', 'type': 'string', 'required': True},
             {'name': 'status', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningItemAttribute',
  'table': 'inventory_positioning_item_attribute',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'attribute_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'name', 'type': 'string', 'required': True},
             {'name': 'value', 'type': 'string', 'required': True},
             {'name': 'source', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ({'field': 'item_id',
                     'target_table': 'inventory_positioning_item',
                     'target_column': 'item_id',
                     'cardinality': 'owned_child',
                     'ownership': 'same_pbc'},)},
 {'class_name': 'InventoryPositioningItemSubstitution',
  'table': 'inventory_positioning_item_substitution',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'substitution_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'substitute_item_id', 'type': 'string', 'required': True},
             {'name': 'priority', 'type': 'string', 'required': True},
             {'name': 'status', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningLot',
  'table': 'inventory_positioning_lot',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'lot_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'expires', 'type': 'string', 'required': True},
             {'name': 'status', 'type': 'string', 'required': True},
             {'name': 'trace_hash', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ({'field': 'item_id',
                     'target_table': 'inventory_positioning_item',
                     'target_column': 'item_id',
                     'cardinality': 'owned_lot',
                     'ownership': 'same_pbc'},)},
 {'class_name': 'InventoryPositioningSerial',
  'table': 'inventory_positioning_serial',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'serial_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'lot_id', 'type': 'string', 'required': True},
             {'name': 'status', 'type': 'string', 'required': True},
             {'name': 'node_id', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ({'field': 'lot_id',
                     'target_table': 'inventory_positioning_lot',
                     'target_column': 'lot_id',
                     'cardinality': 'owned_serial',
                     'ownership': 'same_pbc'},)},
 {'class_name': 'InventoryPositioningNode',
  'table': 'inventory_positioning_node',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'node_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'node_type', 'type': 'string', 'required': True},
             {'name': 'country', 'type': 'string', 'required': True},
             {'name': 'region', 'type': 'string', 'required': True},
             {'name': 'calendar', 'type': 'string', 'required': True},
             {'name': 'status', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningNodeCalendar',
  'table': 'inventory_positioning_node_calendar',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'calendar_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'node_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'timezone', 'type': 'string', 'required': True},
             {'name': 'working_days', 'type': 'string', 'required': True},
             {'name': 'cutoff_time', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ({'field': 'node_id',
                     'target_table': 'inventory_positioning_node',
                     'target_column': 'node_id',
                     'cardinality': 'owned_calendar',
                     'ownership': 'same_pbc'},)},
 {'class_name': 'InventoryPositioningNodeCapacity',
  'table': 'inventory_positioning_node_capacity',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'capacity_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'node_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True},
             {'name': 'daily_capacity', 'type': 'string', 'required': True},
             {'name': 'status', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningNodeIdentity',
  'table': 'inventory_positioning_node_identity',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'identity_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'node_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'did', 'type': 'string', 'required': True},
             {'name': 'issuer', 'type': 'string', 'required': True},
             {'name': 'status', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningInventoryPosition',
  'table': 'inventory_positioning_inventory_position',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'position_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'node_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True},
             {'name': 'on_hand', 'type': 'string', 'required': True},
             {'name': 'reserved', 'type': 'string', 'required': True},
             {'name': 'quarantine', 'type': 'string', 'required': True},
             {'name': 'in_transit', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ({'field': 'item_id',
                     'target_table': 'inventory_positioning_item',
                     'target_column': 'item_id',
                     'cardinality': 'owned_position',
                     'ownership': 'same_pbc'},
                    {'field': 'node_id',
                     'target_table': 'inventory_positioning_node',
                     'target_column': 'node_id',
                     'cardinality': 'owned_position',
                     'ownership': 'same_pbc'})},
 {'class_name': 'InventoryPositioningPositionSnapshot',
  'table': 'inventory_positioning_position_snapshot',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'snapshot_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'position_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'as_of', 'type': 'string', 'required': True},
             {'name': 'on_hand', 'type': 'string', 'required': True},
             {'name': 'available', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningReceipt',
  'table': 'inventory_positioning_receipt',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'receipt_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'node_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True},
             {'name': 'quantity', 'type': 'string', 'required': True},
             {'name': 'status', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningReceiptLine',
  'table': 'inventory_positioning_receipt_line',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'receipt_line_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'receipt_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True},
             {'name': 'quantity', 'type': 'string', 'required': True},
             {'name': 'lot_id', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ({'field': 'receipt_id',
                     'target_table': 'inventory_positioning_receipt',
                     'target_column': 'receipt_id',
                     'cardinality': 'owned_child',
                     'ownership': 'same_pbc'},)},
 {'class_name': 'InventoryPositioningAdjustment',
  'table': 'inventory_positioning_adjustment',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'adjustment_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'node_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True},
             {'name': 'quantity', 'type': 'string', 'required': True},
             {'name': 'reason', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningCycleCount',
  'table': 'inventory_positioning_cycle_count',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'cycle_count_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'node_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True},
             {'name': 'physical_count', 'type': 'integer', 'required': True},
             {'name': 'variance', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningReservation',
  'table': 'inventory_positioning_reservation',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'reservation_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'order_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True},
             {'name': 'quantity', 'type': 'string', 'required': True},
             {'name': 'expires_at', 'type': 'datetime', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningAllocation',
  'table': 'inventory_positioning_allocation',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'allocation_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'order_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True},
             {'name': 'quantity_allocated', 'type': 'string', 'required': True},
             {'name': 'status', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningAllocationLine',
  'table': 'inventory_positioning_allocation_line',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'allocation_line_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'allocation_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'node_id', 'type': 'string', 'required': True},
             {'name': 'lot_id', 'type': 'string', 'required': True},
             {'name': 'quantity', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ({'field': 'allocation_id',
                     'target_table': 'inventory_positioning_allocation',
                     'target_column': 'allocation_id',
                     'cardinality': 'owned_child',
                     'ownership': 'same_pbc'},)},
 {'class_name': 'InventoryPositioningAllocationExpiry',
  'table': 'inventory_positioning_allocation_expiry',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'expiry_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'allocation_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'expires_at', 'type': 'datetime', 'required': True},
             {'name': 'released', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningQualityHold',
  'table': 'inventory_positioning_quality_hold',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'hold_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'node_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True},
             {'name': 'quantity', 'type': 'string', 'required': True},
             {'name': 'reason', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningQualityRelease',
  'table': 'inventory_positioning_quality_release',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'release_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'hold_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'released_by', 'type': 'string', 'required': True},
             {'name': 'released_at', 'type': 'datetime', 'required': True},
             {'name': 'evidence_hash', 'type': 'json', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ({'field': 'hold_id',
                     'target_table': 'inventory_positioning_quality_hold',
                     'target_column': 'hold_id',
                     'cardinality': 'owned_release',
                     'ownership': 'same_pbc'},)},
 {'class_name': 'InventoryPositioningInTransitProjection',
  'table': 'inventory_positioning_in_transit_projection',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'transit_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'quantity', 'type': 'string', 'required': True},
             {'name': 'confidence', 'type': 'decimal', 'required': True},
             {'name': 'eta_days', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningTraceabilityEvent',
  'table': 'inventory_positioning_traceability_event',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'trace_event_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'lot_id', 'type': 'string', 'required': True},
             {'name': 'event_type', 'type': 'string', 'required': True},
             {'name': 'trace_hash', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningBackorder',
  'table': 'inventory_positioning_backorder',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'backorder_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'order_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True},
             {'name': 'quantity', 'type': 'string', 'required': True},
             {'name': 'status', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningReplenishmentSignal',
  'table': 'inventory_positioning_replenishment_signal',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'signal_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'recommended_quantity', 'type': 'string', 'required': True},
             {'name': 'reason', 'type': 'string', 'required': True},
             {'name': 'status', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningReplenishmentPlan',
  'table': 'inventory_positioning_replenishment_plan',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'plan_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'node_id', 'type': 'string', 'required': True},
             {'name': 'quantity', 'type': 'string', 'required': True},
             {'name': 'due_date', 'type': 'datetime', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningReconciliation',
  'table': 'inventory_positioning_reconciliation',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'reconciliation_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'ledger', 'type': 'string', 'required': True},
             {'name': 'physical_count', 'type': 'integer', 'required': True},
             {'name': 'variance', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningPolicyScreening',
  'table': 'inventory_positioning_policy_screening',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'screening_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'decision', 'type': 'string', 'required': True},
             {'name': 'policy', 'type': 'string', 'required': True},
             {'name': 'evidence_hash', 'type': 'json', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningStockProof',
  'table': 'inventory_positioning_stock_proof',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'proof_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'proof_hash', 'type': 'string', 'required': True},
             {'name': 'public_claims', 'type': 'json', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningCrossNodeFederation',
  'table': 'inventory_positioning_cross_node_federation',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'federation_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'external_system', 'type': 'string', 'required': True},
             {'name': 'projection_hash', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningCarbonFulfillment',
  'table': 'inventory_positioning_carbon_fulfillment',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'carbon_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'node_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'carbon_intensity', 'type': 'string', 'required': True},
             {'name': 'selected', 'type': 'string', 'required': True},
             {'name': 'scheduled_at', 'type': 'datetime', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningChannelAllocation',
  'table': 'inventory_positioning_channel_allocation',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'channel_allocation_id',
              'type': 'string',
              'required': True,
              'primary_key': True,
              'nullable': False},
             {'name': 'channel', 'type': 'string', 'required': True},
             {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'quantity', 'type': 'string', 'required': True},
             {'name': 'clearing_bid', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningAnomalySignal',
  'table': 'inventory_positioning_anomaly_signal',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'signal_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'entropy', 'type': 'string', 'required': True},
             {'name': 'observed_at', 'type': 'datetime', 'required': True},
             {'name': 'decision', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningStockRiskModel',
  'table': 'inventory_positioning_stock_risk_model',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'risk_model_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'item_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'risk_score', 'type': 'decimal', 'required': True},
             {'name': 'model_version', 'type': 'string', 'required': True},
             {'name': 'explanations', 'type': 'json', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningSeedData',
  'table': 'inventory_positioning_seed_data',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'seed_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'node_type', 'type': 'string', 'required': True},
             {'name': 'status', 'type': 'string', 'required': True},
             {'name': 'uom', 'type': 'string', 'required': True},
             {'name': 'allocation_policy', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningSchemaExtension',
  'table': 'inventory_positioning_schema_extension',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'extension_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'table_name', 'type': 'string', 'required': True},
             {'name': 'field_name', 'type': 'string', 'required': True},
             {'name': 'field_type', 'type': 'string', 'required': True},
             {'name': 'version', 'type': 'integer', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningControlAssertion',
  'table': 'inventory_positioning_control_assertion',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'control_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'assertion', 'type': 'string', 'required': True},
             {'name': 'status', 'type': 'string', 'required': True},
             {'name': 'evidence_hash', 'type': 'json', 'required': True},
             {'name': 'tested_at', 'type': 'datetime', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningGovernedModel',
  'table': 'inventory_positioning_governed_model',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'model_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'name', 'type': 'string', 'required': True},
             {'name': 'feature_lineage', 'type': 'string', 'required': True},
             {'name': 'drift_score', 'type': 'decimal', 'required': True},
             {'name': 'governance_status', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningRule',
  'table': 'inventory_positioning_rule',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'rule_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'scope', 'type': 'string', 'required': True},
             {'name': 'status', 'type': 'string', 'required': True},
             {'name': 'predicate', 'type': 'json', 'required': True},
             {'name': 'compiled_hash', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningParameter',
  'table': 'inventory_positioning_parameter',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'parameter_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'name', 'type': 'string', 'required': True},
             {'name': 'value', 'type': 'string', 'required': True},
             {'name': 'bounds', 'type': 'string', 'required': True},
             {'name': 'compiled_hash', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningConfiguration',
  'table': 'inventory_positioning_configuration',
  'fields': ({'name': 'id', 'type': 'integer', 'primary_key': True, 'nullable': False},
             {'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'configuration_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'database_backend', 'type': 'string', 'required': True},
             {'name': 'event_topic', 'type': 'string', 'required': True},
             {'name': 'retry_limit', 'type': 'string', 'required': True},
             {'name': 'default_uom', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningAppgenOutboxEvent',
  'table': 'inventory_positioning_appgen_outbox_event',
  'fields': ({'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'event_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'event_type', 'type': 'string', 'required': True},
             {'name': 'topic', 'type': 'string', 'required': True},
             {'name': 'idempotency_key', 'type': 'string', 'required': True},
             {'name': 'audit_hash', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningAppgenInboxEvent',
  'table': 'inventory_positioning_appgen_inbox_event',
  'fields': ({'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'event_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'event_type', 'type': 'string', 'required': True},
             {'name': 'idempotency_key', 'type': 'string', 'required': True},
             {'name': 'attempts', 'type': 'integer', 'required': True},
             {'name': 'status', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()},
 {'class_name': 'InventoryPositioningDeadLetterEvent',
  'table': 'inventory_positioning_dead_letter_event',
  'fields': ({'name': 'tenant', 'type': 'string', 'required': True},
             {'name': 'event_id', 'type': 'string', 'required': True, 'primary_key': True, 'nullable': False},
             {'name': 'event_type', 'type': 'string', 'required': True},
             {'name': 'idempotency_key', 'type': 'string', 'required': True},
             {'name': 'attempts', 'type': 'integer', 'required': True},
             {'name': 'reason', 'type': 'string', 'required': True},
             {'name': 'created_at', 'type': 'datetime', 'required': True},
             {'name': 'updated_at', 'type': 'datetime', 'required': True}),
  'relationships': ()})


def model_manifest():
    """Return executable owned model/table alignment evidence."""
    schema_tables = tuple(table['owned_table'] for table in OWNED_SCHEMA.get('tables', ()))
    model_tables = tuple(model['table'] for model in MODELS)
    missing_models = tuple(table for table in schema_tables if table not in model_tables)
    external_models = tuple(table for table in model_tables if not table.startswith(f'{PBC_KEY}_'))
    relationship_targets = tuple(
        relationship.get('target_table')
        for table in OWNED_SCHEMA.get('tables', ())
        for relationship in table.get('relationships', ())
        if relationship.get('target_table')
    )
    cross_pbc_relationships = tuple(
        target for target in relationship_targets if not target.startswith(f'{PBC_KEY}_')
    )
    return {
        'ok': bool(schema_tables)
        and bool(model_tables)
        and not missing_models
        and not external_models
        and not cross_pbc_relationships,
        'pbc': PBC_KEY,
        'schema_tables': schema_tables,
        'model_tables': model_tables,
        'missing_models': missing_models,
        'external_models': external_models,
        'cross_pbc_relationships': cross_pbc_relationships,
        'relationship_targets': relationship_targets,
        'side_effects': (),
    }


def instantiate_model(table_name, values=None):
    """Create a side-effect-free model payload for validation and tests."""
    model = next((item for item in MODELS if item['table'] == table_name), None)
    if model is None:
        return {'ok': False, 'reason': 'unknown_model', 'table': table_name, 'side_effects': ()}
    supplied = dict(values or {})
    fields = tuple(field['name'] if isinstance(field, dict) else field for field in model.get('fields', ()))
    payload = {field: supplied.get(field) for field in fields}
    return {
        'ok': table_name.startswith(f'{PBC_KEY}_') and bool(fields),
        'pbc': PBC_KEY,
        'model': model['class_name'],
        'table': table_name,
        'fields': fields,
        'payload': payload,
        'side_effects': (),
    }


def smoke_test():
    """Exercise model alignment and model payload creation."""
    manifest = model_manifest()
    first_table = manifest['model_tables'][0] if manifest['model_tables'] else None
    instance = instantiate_model(first_table, {'id': 1}) if first_table else {'ok': False}
    return {
        'ok': manifest['ok'] and instance.get('ok') is True,
        'manifest': manifest,
        'instance': instance,
        'side_effects': (),
    }
