"""Package manifest for the smart_city_mobility_operations PBC."""

PBC_MANIFEST = {'advanced_capabilities': ('smart_city_mobility_operations_event_sourced_operational_history',
                           'smart_city_mobility_operations_multi_tenant_policy_isolation',
                           'smart_city_mobility_operations_schema_evolution_resilience',
                           'smart_city_mobility_operations_autonomous_anomaly_detection',
                           'smart_city_mobility_operations_semantic_document_instruction_understanding',
                           'smart_city_mobility_operations_predictive_risk_scoring',
                           'smart_city_mobility_operations_counterfactual_scenario_simulation',
                           'smart_city_mobility_operations_cryptographic_audit_proofs',
                           'smart_city_mobility_operations_continuous_control_testing',
                           'smart_city_mobility_operations_carbon_and_sustainability_awareness',
                           'smart_city_mobility_operations_cross_pbc_event_federation',
                           'smart_city_mobility_operations_governed_ai_agent_execution'),
 'analytics': ('smart_city_mobility_operations_risk_score',
               'smart_city_mobility_operations_workbench_metric'),
 'apis': ('POST /transit-services',
          'POST /parking-assets',
          'POST /signal-plans',
          'POST /traffic-incidents',
          'POST /curb-allocations',
          'GET /smart-city-mobility-operations-workbench'),
 'capabilities': ('transit_service_management',
                  'smart_city_mobility_operations_workflow',
                  'smart_city_mobility_operations_analytics',
                  'configuration_schema',
                  'rule_engine',
                  'parameter_engine',
                  'owned_schema_migrations_models',
                  'appgen_x_outbox_inbox_eventing',
                  'idempotent_handlers',
                  'retry_dead_letter_evidence',
                  'permissions',
                  'seed_data',
                  'workbench',
                  'agentic_document_instruction_intake',
                  'governed_datastore_crud',
                  'ai_agent_task_assistance',
                  'configuration_workbench',
                  'continuous_release_assurance',
                  'smart_city_mobility_operations_event_sourced_operational_history',
                  'smart_city_mobility_operations_multi_tenant_policy_isolation',
                  'smart_city_mobility_operations_schema_evolution_resilience',
                  'smart_city_mobility_operations_autonomous_anomaly_detection',
                  'smart_city_mobility_operations_semantic_document_instruction_understanding',
                  'smart_city_mobility_operations_predictive_risk_scoring',
                  'smart_city_mobility_operations_counterfactual_scenario_simulation',
                  'smart_city_mobility_operations_cryptographic_audit_proofs',
                  'smart_city_mobility_operations_continuous_control_testing',
                  'smart_city_mobility_operations_carbon_and_sustainability_awareness',
                  'smart_city_mobility_operations_cross_pbc_event_federation',
                  'smart_city_mobility_operations_governed_ai_agent_execution'),
 'configuration': ('SMART_CITY_MOBILITY_OPERATIONS_DATABASE_URL',
                   'SMART_CITY_MOBILITY_OPERATIONS_EVENT_TOPIC',
                   'SMART_CITY_MOBILITY_OPERATIONS_RETRY_LIMIT',
                   'SMART_CITY_MOBILITY_OPERATIONS_DEFAULT_POLICY'),
 'consumes': ('PolicyChanged', 'AuditEventSealed', 'OperationalKpiChanged'),
 'datastore_backend': 'postgresql',
 'description': 'Transit, parking, traffic signals, incidents, curb management, multimodal '
                'services, and city mobility analytics',
 'docs': ('SPECIFICATION.md', 'RELEASE_EVIDENCE.md'),
 'emits': ('SmartCityMobilityOperationsCreated',
           'SmartCityMobilityOperationsUpdated',
           'SmartCityMobilityOperationsApproved',
           'SmartCityMobilityOperationsExceptionOpened'),
 'label': 'Smart City Mobility Operations',
 'mesh': 'opsmfg',
 'migrations': ('migrations/001_initial.sql',),
 'pbc': 'smart_city_mobility_operations',
 'permissions': ('smart_city_mobility_operations.read',
                 'smart_city_mobility_operations.create',
                 'smart_city_mobility_operations.update',
                 'smart_city_mobility_operations.approve',
                 'smart_city_mobility_operations.admin'),
 'seed_data': ('seed_data.py',),
 'standard_features': ('transit_service_management',
                       'smart_city_mobility_operations_workflow',
                       'smart_city_mobility_operations_analytics',
                       'configuration_schema',
                       'rule_engine',
                       'parameter_engine',
                       'owned_schema_migrations_models',
                       'appgen_x_outbox_inbox_eventing',
                       'idempotent_handlers',
                       'retry_dead_letter_evidence',
                       'permissions',
                       'seed_data',
                       'workbench',
                       'agentic_document_instruction_intake',
                       'governed_datastore_crud',
                       'ai_agent_task_assistance',
                       'configuration_workbench',
                       'continuous_release_assurance'),
 'tables': ('transit_service',
            'parking_asset',
            'signal_plan',
            'traffic_incident',
            'curb_allocation',
            'mobility_sensor',
            'service_disruption',
            'smart_city_mobility_operations_policy_rule',
            'smart_city_mobility_operations_runtime_parameter',
            'smart_city_mobility_operations_schema_extension',
            'smart_city_mobility_operations_control_assertion',
            'smart_city_mobility_operations_governed_model'),
 'template': 'asset',
 'tests': ('tests/test_contract.py',),
 'ui_fragments': ('SmartCityMobilityOperationsWorkbench',
                  'SmartCityMobilityOperationsDetail',
                  'SmartCityMobilityOperationsAssistantPanel'),
 'version': '1.0.0',
 'workflows': ('smart_city_mobility_operations_create_transit_service_workflow',
               'smart_city_mobility_operations_record_parking_asset_workflow')}
