DOC_HEADER = """
# coding: utf-8
# AUTOGENERATED BY fabgen from %s
# Copyright (C) Nyimbi Odero, %s

 """


VIEW_HEADER = """
import calendar
from flask import redirect, flash, url_for, Markup, g
from flask import render_template
from flask_appbuilder.models.sqla.interface import SQLAInterface
from flask_appbuilder.views import ModelView, BaseView, MasterDetailView, MultipleView, RestCRUDView, CompactCRUDMixin
from flask_appbuilder import ModelView, ModelRestApi, CompactCRUDMixin, aggregate_count, action, expose, BaseView, has_access
from flask_appbuilder.charts.views import ChartView, TimeChartView, GroupByChartView
from flask_appbuilder.models.group import aggregate_count
from flask_appbuilder.widgets import ListThumbnail, ListWidget
from flask_appbuilder.widgets import FormVerticalWidget, FormInlineWidget, FormHorizontalWidget, ShowBlockWidget
from flask_appbuilder.models.sqla.filters import FilterStartsWith, FilterEqualFunction as FA
from flask import g
# If you want to enable search
# from elasticsearch import Elasticsearch

from . import appbuilder, db

from .models import *
from .mixins import *

##########
# Various Utilities
hide_list = ['created_by', 'changed_by', 'created_on', 'changed_on']

#To pretty Print from PersonMixin
def pretty_month_year(value):
    return calendar.month_name[value.month] + ' ' + str(value.year)


def pretty_year(value):
    return str(value.year)


# def fill_gender():
#   try:
#       db.session.add(Gender(name='Male'))
#       db.session.add(Gender(name='Female'))
#       db.session.commit()
#   except:
#       db.session.rollback()
#############

def get_user():
    return g.user

"""

MODEL_HEADER = """
import enum
import datetime
from datetime import timedelta, datetime, date

from sqlalchemy.orm import relationship, query, defer, deferred, column_property, mapper
from sqlalchemy.schema import FetchedValue
from sqlalchemy.ext.hybrid import hybrid_property, hybrid_method
from sqlalchemy import (Column, Integer, String, ForeignKey,
    Sequence, Float, Text, BigInteger, Date,
    DateTime, Time, Boolean, Index, CheckConstraint,
    UniqueConstraint, ForeignKeyConstraint, Numeric, LargeBinary , Table, func)

# IMPORT Postgresql Specific Types
from sqlalchemy.dialects.postgresql import *
from sqlalchemy.dialects.postgresql import (
    ARRAY, BIGINT, BIT, BOOLEAN, BYTEA, CHAR, CIDR, DATE,
    DOUBLE_PRECISION, ENUM, FLOAT, HSTORE, INET, INTEGER,
    INTERVAL, JSON, JSONB, MACADDR, NUMERIC, OID, REAL, SMALLINT, TEXT,
    TIME, TIMESTAMP, UUID, VARCHAR, INT4RANGE, INT8RANGE, NUMRANGE,
    DATERANGE, TSRANGE, TSTZRANGE, TSVECTOR, aggregate_order_by )

from flask_appbuilder import Model
from flask_appbuilder.models.mixins import AuditMixin, FileColumn, ImageColumn, UserExtensionMixin
from flask_appbuilder.filemanager import ImageManager

from flask_appbuilder.models.decorators import renders
from sqlalchemy_utils import aggregated, force_auto_coercion, observes
from sqlalchemy_utils.types import TSVectorType   #Searchability look at DocMixin
from sqlalchemy.ext.associationproxy import association_proxy

from flask_appbuilder.security.sqla.models import User

# To create GraphSQL API
# import graphene
# from graphene_sqlalchemy import SQLAlchemyObjectType

# Versioning Mixin
# from sqlalchemy_continuum import make_versioned
#Add __versioned__ = {}


# from sqlalchemy_searchable import make_searchable
# from flask_graphql import GraphQLView

# ActiveRecord Model Features
# from sqlalchemy_mixins import AllFeaturesMixin, ActiveRecordMixin


from .mixins import *

# Here is how to extend the User model
#class UserExtended(Model, UserExtensionMixin):
#    contact_group_id = Column(Integer, ForeignKey('contact_group.id'), nullable=True)
#    contact_group = relationship('ContactGroup')

# UTILITY CLASSES
# import arrow,


# Initialize sqlalchemy_utils
#force_auto_coercion()
# Keep versions of all data
# make_versioned()
# make_searchable()


"""

MODEL_FOOTER = """
# And that's all she said
"""

API_HEADER ="""
from flask_appbuilder import ModelRestApi
from flask_appbuilder.api import BaseApi, expose
from flask_appbuilder.models.sqla.interface import SQLAInterface
from flask_appbuilder.models.filters import BaseFilter
from sqlalchemy import or_
from sqlalchemy.sql import text

from . import appbuilder, db
from .models import *
"""

VIEW_BODY ="""
class {0}View(ModelView):# MasterDetailView, MultipleView
    # {1}
    datamodel=SQLAInterface({0}, db.session)
    # To enable Elasticsearch integration, uncomment below
    # search_vector = Text("search_vector", nullable=True)
    add_title = "Add {0}"
    list_title = "List {2}"
    edit_title = "Edit {0}"
    show_title = "Show {0}"
    #add_widget = (FormVerticalWidget|FormInlineWidget)
    show_widget = ShowBlockWidget
    #list_widget = (ListThumbnail|ListWidget)
    #base_order = ("name", "asc")
    search_exclude_columns = person_search_exclude_columns + biometric_columns + person_search_exclude_columns
    # add_exclude_columns = edit_exclude_columns = audit_exclude_columns

    # add_columns = ref_columns + {1} # person_list_columns + ref_columns + contact_columns
    # edit_columns = ref_columns + {1} # person_list_columns + ref_columns + contact_columns
    #edit_exclude_columns = {1} # person_list_columns + ref_columns + contact_columns

    # list_columns = ref_columns + {1} # person_list_columns + ref_columns + contact_columns
    #show_columns = []
    #show_exclude_columns = []
    #search_columns = []
    #search_exclude_columns = []
    #list_widget = ListBlock|ListItem|ListThumbnail|ListWidget (default)
    #related_views =[]
    #show_fieldsets = person_show_fieldset + contact_fieldset
    #edit_fieldsets = add_fieldsets = \
			# ref_fieldset + person_fieldset + contact_fieldset #+  activity_fieldset + place_fieldset + biometric_fieldset + employment_fieldset
    #description_columns = {{'name':'your models name column','address':'the address column'}}
    #show_template = "appbuilder/general/model/show_cascade.html"
    #edit_template = "appbuilder/general/model/edit_cascade.html"

    # @action("muldelete", "Delete", Markup("<p>Delete all Really?</p><p>Ok then...</p>"), "fa-rocket")
    # def muldelete(self, items):
    #     self.datamodel.delete_all(items)
    #     self.update_redirect()
    #     return redirect(self.get_redirect())

# For Elasticsearch integration
#     def post_update(self, item):
#         es = Elasticsearch()
#         doc = {{"search_vector": item.search_vector}}
#         es.index(index="my_index", id=item.id, body=doc)
#
#     def post_insert(self, item):
#         self.post_update(item)
#
#     @expose("/search/")
#     def search(self):
#         q = request.args.get("q", "")
#         es = Elasticsearch()
#         search_body = {{"query": {{"match": {{"search_vector": q}}}}}}
#         results = es.search(index="my_index", body=search_body)
#         return self.render_template(
#             "search_results.html",
#             results=results["hits"]["hits"],
#             query=q,
#           )
"""

VIEW_REG_HEADER = """

# How to create a MasterDetailView

#class DetailView(ModelView):
#    datamodel = SQLAInterface(DetailTable, db.session)

#class MasterView(MasterDetailView):
#    datamodel = SQLAInterface(MasterTable, db.session)
#    related_views = [DetailView]


# How to create a MultipleView
#class MultipleViewsExp(MultipleView):
#    views = [GroupModelView, ContactModelView]

#View Registration
db.create_all()
fill_gender()
"""

#TODO Change to this view using the included example (chatgpt)
VIEW_MASTER_DETAILX ="""
class PersonModelView(ModelView):
    datamodel = SQLAInterface(Person)

class PersonDetailModelView(ModelView):
    datamodel = SQLAInterface(Person)
    show = "detail"

person_master_view = PersonModelView()
person_detail_view = PersonDetailModelView()
person_master_detail_view = MasterDetailView(master=person_master_view, detail=person_detail_view)

appbuilder.add_view(person_master_detail_view, "Person List", icon="fa-folder-open-o", category="People")
"""

VIEW_MASTER_DETAIL = """
class {0}{1}DetailView(ModelView):
    datamodel = SQLAInterface({1}, db.session)
    show = 'detail'

class {0}{1}MasterView(MasterDetailView):
    datamodel = SQLAInterface({0}, db.session)
    related_views = [{0}{1}DetailView]

#appbuilder.add_view({0}{1}MasterView(), "{0}-{1}", icon="fa-folder-open-o", category="Master Detail", category_icon = "fa-envelope")
"""

VIEW_REG = 'appbuilder.add_view(%s, "%s", icon="fa-folder-open-o", category="Setup")'
API_REG = 'appbuilder.add_api(%sModelApi)'


VIEW_REG_MD = 'appbuilder.add_view({0}{1}MasterView(), "{0}-{1}", icon="fa-folder-open-o", category="Master Detail", category_icon = "fa-envelope")'


VIEW_FOOTER = """
appbuilder.add_link("rest_api", href="/swagger/v1", icon="fa-sliders", label="REST Api", category="Utilities")
appbuilder.add_link("graphql", href="/graphql", icon="fa-wrench", label="GraphQL", category="Utilities")

#appbuilder.add_separator("Setup")
#appbuilder.add_separator("My Views")
#appbuilder.add_link(name, href, icon='', label='', category='', category_icon='', category_label='', baseview=None)

'''
     Application wide 404 error handler
'''
 
@appbuilder.app.errorhandler(404)
def page_not_found(e):
    return (
        render_template(
           "404.html", base_template=appbuilder.base_template, appbuilder=appbuilder
        ),
        404,
     )


db.create_all()
"""

API_BODY = """
# API
class {0}ModelApi(ModelRestApi):
    # {1}
    resource_name = '{3}'
    datamodel = SQLAInterface({0})
    add_title = "Add {0}"
    list_title = "List {2}"
    edit_title = "Edit {0}"
    show_title = "Show {0}"
    #base_order = ("name", "asc")
    # search_exclude_columns = person_search_exclude_columns + biometric_columns + person_search_exclude_columns
    # add_exclude_columns = edit_exclude_columns = audit_exclude_columns
    # add_columns = {1} # person_list_columns + ref_columns + contact_columns
    # edit_columns = {1} # person_list_columns + ref_columns + contact_columns
    #edit_exclude_columns = {1} # person_list_columns + ref_columns + contact_columns
    # list_columns = {1} # person_list_columns + ref_columns + contact_columns
    #show_columns = []
    #show_exclude_columns = []
    #search_columns = []
    #search_exclude_columns = []
    #related_views =[]
    #show_fieldsets = person_show_fieldset + contact_fieldset
    #edit_fieldsets = add_fieldsets = \
			# ref_fieldset + person_fieldset + contact_fieldset #+  activity_fieldset + place_fieldset + biometric_fieldset + employment_fieldset
    #description_columns = {{'name':'your models name column','address':'the address column'}}
    # Allowed order columns
    page_size = 20
    # Use this property to change default page size
    # max_page_size = -1 # : Optional[int] = None
    # class override for the FAB_API_MAX_SIZE, use special -1 to allow for any page size
    # description_columns= [] #: Optional[Dict[str, str]] = None
    #
    #     Dictionary with column descriptions that will be shown on the forms::
    #
    #         class MyView(ModelView):
    #             datamodel = SQLAModel(MyTable, db.session)
    #
    #             description_columns = {{'name':'your models name column',
    #                                     'address':'the address column'}}
    #
    # validators_columns: Optional[Dict[str, Callable]] = None
    #  Dictionary to add your own marshmallow validators

    # add_query_rel_fields = None
    #
    #     Add Customized query for related add fields.
    #     Assign a dictionary where the keys are the column names of
    #     the related models to filter, the value for each key, is a list of lists with the
    #     same format as base_filter
    #     {{'relation col name':[['Related model col',FilterClass,'Filter Value'],...],...}}
    #     Add a custom filter to form related fields::
    #
    #         class ContactModelView(ModelRestApi):
    #             datamodel = SQLAModel(Contact)
    #             add_query_rel_fields = {{'group':[['name',FilterStartsWith,'W']]}}
    #
    #
    # edit_query_rel_fields = None
    #
    #     Add Customized query for related edit fields.
    #     Assign a dictionary where the keys are the column names of
    #     the related models to filter, the value for each key, is a list of lists with the
    #     same format as base_filter
    #     {{'relation col name':[['Related model col',FilterClass,'Filter Value'],...],...}}
    #     Add a custom filter to form related fields::
    #
    #         class ContactModelView(ModelRestApi):
    #             datamodel = SQLAModel(Contact, db.session)
    #             edit_query_rel_fields = {{'group':[['name',FilterStartsWith,'W']]}}
    #
    #
    # order_rel_fields = None
    #
    #     Impose order on related fields.
    #     assign a dictionary where the keys are the related column names::
    #
    #         class ContactModelView(ModelRestApi):
    #             datamodel = SQLAModel(Contact)
    #             order_rel_fields = {{
    #                 'group': ('name', 'asc')
    #                 'gender': ('name', 'asc')
    #             }}
    #
    # list_model_schema = [] # : Optional[Schema] = None
    #  Override to provide your own marshmallow Schema for JSON to SQLA dumps
    # add_model_schema: Optional[Schema] = None
    #  Override to provide your own marshmallow Schema for JSON to SQLA dumps
    # edit_model_schema: Optional[Schema] = None
    #  Override to provide your own marshmallow Schema for JSON to SQLA dumps
    # show_model_schema: Optional[Schema] = None
    #  Override to provide your own marshmallow Schema for JSON to SQLA dumps
    # model2schemaconverter = Model2SchemaConverter
    #  Override to use your own Model2SchemaConverter (inherit from BaseModel2SchemaConverter)
"""

MODEL_EXT = """
    ## Example stuff you can add to a table
    # def __repr__(self):
    #     return self.name
    #
    # def month_year(self):
    #     date = self.birthday or mindate
    #     return datetime.datetime(date.year, date.month, 1) or mindate
    #
    # def year(self):
    #     date = self.birthday or mindate
    #     return datetime.datetime(date.year, 1, 1)
    #
    # @hybrid_property
    # def length(self):
    #     return self.end - self.start
    #
    # @hybrid_method
    # def contains(self, point):
    #     return (self.start <= point) & (point <= self.end)
    #
    #
    # @hybrid_method
    # def intersects(self, other):
    #     return self.contains(other.start) | self.contains(other.end)
"""

GQL_HEADER = """
import graphene
from graphene_sqlalchemy import SQLAlchemyObjectType, SQLAlchemyConnectionField
from graphene import relay

from flask_appbuilder.security.sqla.models import User, Role, Permission, PermissionView, RegisterUser
from .models import *
"""

GQL_IMPORT = "from .models import {0} as {0}Model"

GQL_SEC_IMPORT = "from flask_appbuilder.security.sqla.models import {0} as {0}Model"


# https://github.com/graphql-python/graphene-sqlalchemy
GQL_CLASS = """
class {0}_gql(SQLAlchemyObjectType):
    class Meta:
        model = {0}Model
        interfaces = (relay.Node, )
        # use `only_fields` to only expose specific fields ie "name"
        # only_fields = ("name",)
        # use `exclude_fields` to exclude specific fields ie "last_name"
        # exclude_fields = ("last_name",)
"""

GQL_QUERY_HDR = """
class Query(graphene.ObjectType):
    node = relay.Node.Field()
"""

GQL_QUERY="""    # Allows sorting over multiple columns, by default over the primary key
    all_{0} = SQLAlchemyConnectionField({0}_gql.connection) #sort={0}_gql.sort_argument())"""


GQL_FOOTER = """
schema = graphene.Schema(query=Query)
"""
