"""Package manifest for the food_safety_quality_compliance PBC."""

PBC_MANIFEST = {'advanced_capabilities': ('food_safety_quality_compliance_event_sourced_operational_history',
                           'food_safety_quality_compliance_multi_tenant_policy_isolation',
                           'food_safety_quality_compliance_schema_evolution_resilience',
                           'food_safety_quality_compliance_autonomous_anomaly_detection',
                           'food_safety_quality_compliance_semantic_document_instruction_understanding',
                           'food_safety_quality_compliance_predictive_risk_scoring',
                           'food_safety_quality_compliance_counterfactual_scenario_simulation',
                           'food_safety_quality_compliance_cryptographic_audit_proofs',
                           'food_safety_quality_compliance_continuous_control_testing',
                           'food_safety_quality_compliance_carbon_and_sustainability_awareness',
                           'food_safety_quality_compliance_cross_pbc_event_federation',
                           'food_safety_quality_compliance_governed_ai_agent_execution'),
 'analytics': ('food_safety_quality_compliance_risk_score',
               'food_safety_quality_compliance_workbench_metric'),
 'apis': ('POST /haccp-plans',
          'POST /critical-control-points',
          'POST /inspections',
          'POST /nonconformances',
          'POST /recall-events',
          'GET /food-safety-quality-compliance-workbench'),
 'capabilities': ('haccp_plan_management',
                  'food_safety_quality_compliance_workflow',
                  'food_safety_quality_compliance_analytics',
                  'configuration_schema',
                  'rule_engine',
                  'parameter_engine',
                  'owned_schema_migrations_models',
                  'appgen_x_outbox_inbox_eventing',
                  'idempotent_handlers',
                  'retry_dead_letter_evidence',
                  'permissions',
                  'seed_data',
                  'workbench',
                  'agentic_document_instruction_intake',
                  'governed_datastore_crud',
                  'ai_agent_task_assistance',
                  'configuration_workbench',
                  'continuous_release_assurance',
                  'food_safety_quality_compliance_event_sourced_operational_history',
                  'food_safety_quality_compliance_multi_tenant_policy_isolation',
                  'food_safety_quality_compliance_schema_evolution_resilience',
                  'food_safety_quality_compliance_autonomous_anomaly_detection',
                  'food_safety_quality_compliance_semantic_document_instruction_understanding',
                  'food_safety_quality_compliance_predictive_risk_scoring',
                  'food_safety_quality_compliance_counterfactual_scenario_simulation',
                  'food_safety_quality_compliance_cryptographic_audit_proofs',
                  'food_safety_quality_compliance_continuous_control_testing',
                  'food_safety_quality_compliance_carbon_and_sustainability_awareness',
                  'food_safety_quality_compliance_cross_pbc_event_federation',
                  'food_safety_quality_compliance_governed_ai_agent_execution'),
 'configuration': ('FOOD_SAFETY_QUALITY_COMPLIANCE_DATABASE_URL',
                   'FOOD_SAFETY_QUALITY_COMPLIANCE_EVENT_TOPIC',
                   'FOOD_SAFETY_QUALITY_COMPLIANCE_RETRY_LIMIT',
                   'FOOD_SAFETY_QUALITY_COMPLIANCE_DEFAULT_POLICY'),
 'consumes': ('PolicyChanged', 'AuditEventSealed', 'OperationalKpiChanged'),
 'datastore_backend': 'postgresql',
 'description': 'HACCP plans, inspections, nonconformance, recalls, supplier audits, food quality, '
                'and regulatory evidence',
 'docs': ('SPECIFICATION.md', 'RELEASE_EVIDENCE.md'),
 'emits': ('FoodSafetyQualityComplianceCreated',
           'FoodSafetyQualityComplianceUpdated',
           'FoodSafetyQualityComplianceApproved',
           'FoodSafetyQualityComplianceExceptionOpened'),
 'label': 'Food Safety Quality Compliance',
 'mesh': 'opsmfg',
 'migrations': ('migrations/001_initial.sql',),
 'pbc': 'food_safety_quality_compliance',
 'permissions': ('food_safety_quality_compliance.read',
                 'food_safety_quality_compliance.create',
                 'food_safety_quality_compliance.update',
                 'food_safety_quality_compliance.approve',
                 'food_safety_quality_compliance.admin'),
 'seed_data': ('seed_data.py',),
 'standard_features': ('haccp_plan_management',
                       'food_safety_quality_compliance_workflow',
                       'food_safety_quality_compliance_analytics',
                       'configuration_schema',
                       'rule_engine',
                       'parameter_engine',
                       'owned_schema_migrations_models',
                       'appgen_x_outbox_inbox_eventing',
                       'idempotent_handlers',
                       'retry_dead_letter_evidence',
                       'permissions',
                       'seed_data',
                       'workbench',
                       'agentic_document_instruction_intake',
                       'governed_datastore_crud',
                       'ai_agent_task_assistance',
                       'configuration_workbench',
                       'continuous_release_assurance'),
 'tables': ('haccp_plan',
            'critical_control_point',
            'inspection',
            'nonconformance',
            'recall_event',
            'supplier_audit',
            'quality_hold',
            'food_safety_quality_compliance_policy_rule',
            'food_safety_quality_compliance_runtime_parameter',
            'food_safety_quality_compliance_schema_extension',
            'food_safety_quality_compliance_control_assertion',
            'food_safety_quality_compliance_governed_model'),
 'template': 'asset',
 'tests': ('tests/test_contract.py',),
 'ui_fragments': ('FoodSafetyQualityComplianceWorkbench',
                  'FoodSafetyQualityComplianceDetail',
                  'FoodSafetyQualityComplianceAssistantPanel'),
 'version': '1.0.0',
 'workflows': ('food_safety_quality_compliance_create_haccp_plan_workflow',
               'food_safety_quality_compliance_record_critical_control_point_workflow')}
