"""Package manifest for the utility_outage_restoration PBC."""

PBC_MANIFEST = {'advanced_capabilities': ('utility_outage_restoration_event_sourced_operational_history',
                           'utility_outage_restoration_multi_tenant_policy_isolation',
                           'utility_outage_restoration_schema_evolution_resilience',
                           'utility_outage_restoration_autonomous_anomaly_detection',
                           'utility_outage_restoration_semantic_document_instruction_understanding',
                           'utility_outage_restoration_predictive_risk_scoring',
                           'utility_outage_restoration_counterfactual_scenario_simulation',
                           'utility_outage_restoration_cryptographic_audit_proofs',
                           'utility_outage_restoration_continuous_control_testing',
                           'utility_outage_restoration_carbon_and_sustainability_awareness',
                           'utility_outage_restoration_cross_pbc_event_federation',
                           'utility_outage_restoration_governed_ai_agent_execution'),
 'analytics': ('utility_outage_restoration_risk_score',
               'utility_outage_restoration_workbench_metric'),
 'apis': ('POST /outage-incidents',
          'POST /device-interruptions',
          'POST /switching-steps',
          'POST /crew-assignments',
          'POST /restoration-estimates',
          'GET /utility-outage-restoration-workbench'),
 'capabilities': ('outage_incident_management',
                  'utility_outage_restoration_workflow',
                  'utility_outage_restoration_analytics',
                  'configuration_schema',
                  'rule_engine',
                  'parameter_engine',
                  'owned_schema_migrations_models',
                  'appgen_x_outbox_inbox_eventing',
                  'idempotent_handlers',
                  'retry_dead_letter_evidence',
                  'permissions',
                  'seed_data',
                  'workbench',
                  'agentic_document_instruction_intake',
                  'governed_datastore_crud',
                  'ai_agent_task_assistance',
                  'configuration_workbench',
                  'continuous_release_assurance',
                  'utility_outage_restoration_event_sourced_operational_history',
                  'utility_outage_restoration_multi_tenant_policy_isolation',
                  'utility_outage_restoration_schema_evolution_resilience',
                  'utility_outage_restoration_autonomous_anomaly_detection',
                  'utility_outage_restoration_semantic_document_instruction_understanding',
                  'utility_outage_restoration_predictive_risk_scoring',
                  'utility_outage_restoration_counterfactual_scenario_simulation',
                  'utility_outage_restoration_cryptographic_audit_proofs',
                  'utility_outage_restoration_continuous_control_testing',
                  'utility_outage_restoration_carbon_and_sustainability_awareness',
                  'utility_outage_restoration_cross_pbc_event_federation',
                  'utility_outage_restoration_governed_ai_agent_execution'),
 'configuration': ('UTILITY_OUTAGE_RESTORATION_DATABASE_URL',
                   'UTILITY_OUTAGE_RESTORATION_EVENT_TOPIC',
                   'UTILITY_OUTAGE_RESTORATION_RETRY_LIMIT',
                   'UTILITY_OUTAGE_RESTORATION_DEFAULT_POLICY'),
 'consumes': ('PolicyChanged', 'AuditEventSealed', 'OperationalKpiChanged'),
 'datastore_backend': 'postgresql',
 'description': 'Outage detection, switching, crew dispatch, restoration estimates, customer '
                'impact, and reliability reporting',
 'docs': ('SPECIFICATION.md', 'RELEASE_EVIDENCE.md'),
 'emits': ('UtilityOutageRestorationCreated',
           'UtilityOutageRestorationUpdated',
           'UtilityOutageRestorationApproved',
           'UtilityOutageRestorationExceptionOpened'),
 'label': 'Utility Outage Restoration',
 'mesh': 'opsmfg',
 'migrations': ('migrations/001_initial.sql',),
 'pbc': 'utility_outage_restoration',
 'permissions': ('utility_outage_restoration.read',
                 'utility_outage_restoration.create',
                 'utility_outage_restoration.update',
                 'utility_outage_restoration.approve',
                 'utility_outage_restoration.admin'),
 'seed_data': ('seed_data.py',),
 'standard_features': ('outage_incident_management',
                       'utility_outage_restoration_workflow',
                       'utility_outage_restoration_analytics',
                       'configuration_schema',
                       'rule_engine',
                       'parameter_engine',
                       'owned_schema_migrations_models',
                       'appgen_x_outbox_inbox_eventing',
                       'idempotent_handlers',
                       'retry_dead_letter_evidence',
                       'permissions',
                       'seed_data',
                       'workbench',
                       'agentic_document_instruction_intake',
                       'governed_datastore_crud',
                       'ai_agent_task_assistance',
                       'configuration_workbench',
                       'continuous_release_assurance'),
 'tables': ('outage_incident',
            'device_interruption',
            'switching_step',
            'crew_assignment',
            'restoration_estimate',
            'customer_impact',
            'reliability_metric',
            'utility_outage_restoration_policy_rule',
            'utility_outage_restoration_runtime_parameter',
            'utility_outage_restoration_schema_extension',
            'utility_outage_restoration_control_assertion',
            'utility_outage_restoration_governed_model'),
 'template': 'asset',
 'tests': ('tests/test_contract.py',),
 'ui_fragments': ('UtilityOutageRestorationWorkbench',
                  'UtilityOutageRestorationDetail',
                  'UtilityOutageRestorationAssistantPanel'),
 'version': '1.0.0',
 'workflows': ('utility_outage_restoration_create_outage_incident_workflow',
               'utility_outage_restoration_record_device_interruption_workflow')}
