"""Executable improve1 capability registry for this PBC.

This module turns the package-local improve1 backlog into code-level evidence.
It is intentionally side-effect free: callers can inspect capability coverage, plan
execution, and verify surface mappings without touching external systems.
"""

from __future__ import annotations

from dataclasses import dataclass

PBC_KEY = 'telecom_network_operations'


@dataclass(frozen=True)
class Improve1Capability:
    feature_number: int
    title: str
    slug: str
    domain_tags: tuple[str, ...]
    model_artifacts: tuple[str, ...]
    ui_artifacts: tuple[str, ...]
    service_artifacts: tuple[str, ...]
    test_artifacts: tuple[str, ...]
    evidence_artifacts: tuple[str, ...]
    configurable: bool = True
    agent_assisted: bool = True
    side_effect_free_plan: bool = True

    def as_traceability_row(self) -> dict:
        return {
            "feature_number": self.feature_number,
            "title": self.title,
            "slug": self.slug,
            "domain_tags": self.domain_tags,
            "code_artifact_model": self.model_artifacts,
            "ui_surface": self.ui_artifacts,
            "service_api": self.service_artifacts,
            "test": self.test_artifacts,
            "evidence": self.evidence_artifacts,
            "configurable": self.configurable,
            "agent_assisted": self.agent_assisted,
            "side_effect_free_plan": self.side_effect_free_plan,
        }



IMPROVE1_CAPABILITIES: tuple[Improve1Capability, ...] = (
    Improve1Capability(
        feature_number=1,
        title='Canonical site hierarchy and geospatial identity',
        slug='canonical_site_hierarchy_and_geospatial_identity',
        domain_tags=('identity',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=2,
        title='Cell, sector, carrier, and radio identity model',
        slug='cell_sector_carrier_and_radio_identity_model',
        domain_tags=('identity', 'model'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=3,
        title='Circuit and service path topology',
        slug='circuit_and_service_path_topology',
        domain_tags=('service',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=4,
        title='Fiber route, strand, and splice ownership',
        slug='fiber_route_strand_and_splice_ownership',
        domain_tags=('fiber', 'route', 'strand'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=5,
        title='Alarm catalog normalization across vendors',
        slug='alarm_catalog_normalization_across_vendors',
        domain_tags=('alarm', 'catalog', 'normalization'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=6,
        title='Root-cause alarm correlation and suppression',
        slug='root_cause_alarm_correlation_and_suppression',
        domain_tags=('root_cause', 'alarm', 'correlation'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=7,
        title='Trouble ticket ownership and boundary rules',
        slug='trouble_ticket_ownership_and_boundary_rules',
        domain_tags=('trouble', 'ticket', 'ownership'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=8,
        title='Planned work and maintenance window depth',
        slug='planned_work_and_maintenance_window_depth',
        domain_tags=('planned', 'maintenance', 'window'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=9,
        title='Outage lifecycle and major incident control',
        slug='outage_lifecycle_and_major_incident_control',
        domain_tags=('outage', 'lifecycle', 'major'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=10,
        title='SLA clock engine tied to service impact',
        slug='sla_clock_engine_tied_to_service_impact',
        domain_tags=('service',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=11,
        title='Capacity modeling for radio, transport, and core edges',
        slug='capacity_modeling_for_radio_transport_and_core_edges',
        domain_tags=('model',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=12,
        title='Performance KPI catalog with telecom baselines',
        slug='performance_kpi_catalog_with_telecom_baselines',
        domain_tags=('performance', 'catalog', 'telecom'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=13,
        title='Congestion and degradation early warning',
        slug='congestion_and_degradation_early_warning',
        domain_tags=('congestion', 'degradation', 'early'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=14,
        title='Field operations boundary',
        slug='field_operations_boundary',
        domain_tags=('field', 'operations', 'boundary'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=15,
        title='Inventory boundary',
        slug='inventory_boundary',
        domain_tags=('inventory',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=16,
        title='NOC workbench queue design',
        slug='noc_workbench_queue_design',
        domain_tags=('workbench', 'queue', 'design'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=17,
        title='Topology, map, and path UI',
        slug='topology_map_and_path_ui',
        domain_tags=('topology',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=18,
        title='Site detail UI with power and access context',
        slug='site_detail_ui_with_power_and_access_context',
        domain_tags=('detail', 'power', 'access'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=19,
        title='Outage war room UI',
        slug='outage_war_room_ui',
        domain_tags=('outage',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=20,
        title='Planned work calendar and conflict UI',
        slug='planned_work_calendar_and_conflict_ui',
        domain_tags=('planned', 'calendar', 'conflict'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=21,
        title='Alarm triage agent skill',
        slug='alarm_triage_agent_skill',
        domain_tags=('agent',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=22,
        title='Trouble ticket summarizer and next-action skill',
        slug='trouble_ticket_summarizer_and_next_action_skill',
        domain_tags=('trouble', 'ticket', 'summarizer'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=23,
        title='Planned work risk reviewer skill',
        slug='planned_work_risk_reviewer_skill',
        domain_tags=('risk',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=24,
        title='Outage communications drafting skill',
        slug='outage_communications_drafting_skill',
        domain_tags=('outage', 'communications', 'drafting'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=25,
        title='Performance degradation investigator skill',
        slug='performance_degradation_investigator_skill',
        domain_tags=('performance', 'degradation', 'investigator'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=26,
        title='Telecom event taxonomy and naming',
        slug='telecom_event_taxonomy_and_naming',
        domain_tags=('event', 'tax'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=27,
        title='Event ordering, idempotency, and replay safety',
        slug='event_ordering_idempotency_and_replay_safety',
        domain_tags=('event', 'safety'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=28,
        title='Event-sourced operational timeline',
        slug='event_sourced_operational_timeline',
        domain_tags=('event',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=29,
        title='Impact propagation from network fault to service and customer',
        slug='impact_propagation_from_network_fault_to_service_and_customer',
        domain_tags=('customer', 'service'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=30,
        title='External integration boundaries for OSS and customer systems',
        slug='external_integration_boundaries_for_oss_and_customer_systems',
        domain_tags=('customer',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=31,
        title='Circuit restoration and reroute playbooks',
        slug='circuit_restoration_and_reroute_playbooks',
        domain_tags=('circuit', 'restoration', 'reroute'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=32,
        title='Fiber cut response playbooks',
        slug='fiber_cut_response_playbooks',
        domain_tags=('fiber', 'response', 'playbooks'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=33,
        title='Power and environmental incident handling',
        slug='power_and_environmental_incident_handling',
        domain_tags=('power', 'environmental', 'incident'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=34,
        title='Field evidence capture and spares boundary',
        slug='field_evidence_capture_and_spares_boundary',
        domain_tags=('field', 'evidence', 'capture'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=35,
        title='Search and topology query language',
        slug='search_and_topology_query_language',
        domain_tags=('search',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=36,
        title='Bulk reconciliation with discovery and monitoring feeds',
        slug='bulk_reconciliation_with_discovery_and_monitoring_feeds',
        domain_tags=('reconciliation',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=37,
        title='Stale inventory and orphaned topology controls',
        slug='stale_inventory_and_orphaned_topology_controls',
        domain_tags=('inventory',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=38,
        title='Release evidence matrix for telecom scenarios',
        slug='release_evidence_matrix_for_telecom_scenarios',
        domain_tags=('release', 'evidence', 'matrix'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=39,
        title='Seed scenarios and synthetic incident library',
        slug='seed_scenarios_and_synthetic_incident_library',
        domain_tags=('scenarios', 'synthetic', 'incident'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=40,
        title='Change approval, freeze windows, and rollback governance',
        slug='change_approval_freeze_windows_and_rollback_governance',
        domain_tags=('approval', 'governance'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=41,
        title='SLA breach forecasting and escalation',
        slug='sla_breach_forecasting_and_escalation',
        domain_tags=('forecast',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=42,
        title='Capacity forecasting with reservation awareness',
        slug='capacity_forecasting_with_reservation_awareness',
        domain_tags=('forecast',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=43,
        title='KPI anomaly detection with operator feedback',
        slug='kpi_anomaly_detection_with_operator_feedback',
        domain_tags=('anomaly', 'detection', 'operator'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=44,
        title='Customer and service view stitched from telecom causes',
        slug='customer_and_service_view_stitched_from_telecom_causes',
        domain_tags=('customer', 'service'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=45,
        title='Dead-letter and replay workbench',
        slug='dead_letter_and_replay_workbench',
        domain_tags=('dead_letter', 'replay', 'workbench'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=46,
        title='Regional calendar, market hierarchy, and local operating rules',
        slug='regional_calendar_market_hierarchy_and_local_operating_rules',
        domain_tags=('market',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=47,
        title='Role segmentation and least-privilege telecom controls',
        slug='role_segmentation_and_least_privilege_telecom_controls',
        domain_tags=('segmentation', 'least_privilege', 'telecom'),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=48,
        title='Document intake for MOP, RCA, and field reports',
        slug='document_intake_for_mop_rca_and_field_reports',
        domain_tags=('document',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=49,
        title='Separate executive and NOC dashboard projections',
        slug='separate_executive_and_noc_dashboard_projections',
        domain_tags=('project',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
    Improve1Capability(
        feature_number=50,
        title='Manifest-to-backlog traceability gate',
        slug='manifest_to_backlog_traceability_gate',
        domain_tags=('traceability',),
        model_artifacts=('models.py', 'migrations/001_initial.sql', 'schema_contract.py', 'manifest.py'),
        ui_artifacts=('ui.py', 'forms.py', 'wizards.py', 'controls.py', 'agent.py'),
        service_artifacts=('services.py', 'service_contract.py', 'routes.py', 'runtime.py', 'standalone.py'),
        test_artifacts=('tests/test_contract.py', 'tests/test_improve1_traceability.py', 'tests/test_standalone.py'),
        evidence_artifacts=('release_evidence.py', 'RELEASE_EVIDENCE.md', 'capability_assurance.py', 'implementation-status.md', 'SPECIFICATION.md', 'README.md'),
    ),
)



def capability_registry() -> dict:
    """Return side-effect-free registry metadata for improve1 capabilities."""
    rows = tuple(capability.as_traceability_row() for capability in IMPROVE1_CAPABILITIES)
    return {
        "ok": len(rows) == 50 and all(row["code_artifact_model"] and row["ui_surface"] and row["service_api"] and row["test"] and row["evidence"] for row in rows),
        "pbc": PBC_KEY,
        "capability_count": len(rows),
        "capabilities": rows,
        "side_effects": (),
    }


def plan_feature_execution(feature_number: int) -> dict:
    """Plan how a feature is exercised without mutating package state."""
    match = next((capability for capability in IMPROVE1_CAPABILITIES if capability.feature_number == feature_number), None)
    if match is None:
        return {"ok": False, "pbc": PBC_KEY, "reason": "unknown_feature", "side_effects": ()}
    return {
        "ok": True,
        "pbc": PBC_KEY,
        "feature_number": match.feature_number,
        "title": match.title,
        "slug": match.slug,
        "domain_tags": match.domain_tags,
        "model_artifacts": match.model_artifacts,
        "ui_artifacts": match.ui_artifacts,
        "service_artifacts": match.service_artifacts,
        "test_artifacts": match.test_artifacts,
        "evidence_artifacts": match.evidence_artifacts,
        "requires_configuration": match.configurable,
        "agent_assisted": match.agent_assisted,
        "side_effects": (),
    }


def validate_improve1_capabilities(expected_titles: tuple[str, ...]) -> dict:
    """Validate registry alignment with parsed improve1 titles."""
    actual_titles = tuple(capability.title for capability in IMPROVE1_CAPABILITIES)
    registry = capability_registry()
    return {
        "ok": len(actual_titles) == 50 and actual_titles == expected_titles and registry["ok"],
        "pbc": PBC_KEY,
        "expected_count": len(expected_titles),
        "actual_count": len(actual_titles),
        "titles_match": actual_titles == expected_titles,
        "registry_ok": registry["ok"],
        "side_effects": (),
    }
