"""Package manifest for the customer_success_management PBC."""

PBC_MANIFEST = {'pbc': 'customer_success_management',
 'label': 'Customer Success Management',
 'mesh': 'relationship',
 'description': 'Health scores, onboarding plans, adoption telemetry, renewals, expansion signals, playbooks, and '
                'churn risk workflows.',
 'version': '1.0.0',
 'datastore_backend': 'postgresql',
 'tables': ('customer_success_account',
            'customer_health_score',
            'onboarding_plan',
            'adoption_signal',
            'renewal_plan',
            'expansion_signal',
            'success_playbook',
            'churn_risk_case'),
 'apis': ('POST /success-accounts',
          'POST /health-scores',
          'POST /onboarding-plans',
          'POST /renewal-plans',
          'GET /customer-success-workbench'),
 'emits': ('CustomerHealthChanged', 'RenewalPlanCreated', 'ExpansionSignalDetected', 'ChurnRiskRaised'),
 'consumes': ('CustomerUpdated', 'SubscriptionRenewed', 'ServiceTicketResolved'),
 'template': 'crm',
 'ui_fragments': ('CustomerSuccessManagementWorkbench',
                  'CustomerSuccessManagementDetail',
                  'CustomerSuccessManagementAssistantPanel'),
 'permissions': ('customer_success_management.read',
                 'customer_success_management.create',
                 'customer_success_management.update',
                 'customer_success_management.approve',
                 'customer_success_management.admin'),
 'configuration': ('CUSTOMER_SUCCESS_MANAGEMENT_DATABASE_URL',
                   'CUSTOMER_SUCCESS_MANAGEMENT_EVENT_TOPIC',
                   'CUSTOMER_SUCCESS_MANAGEMENT_RETRY_LIMIT',
                   'CUSTOMER_SUCCESS_MANAGEMENT_DEFAULT_POLICY'),
 'migrations': ('migrations/001_initial.sql',),
 'seed_data': ('seed_data.py',),
 'tests': ('tests/test_contract.py',),
 'docs': ('SPECIFICATION.md', 'RELEASE_EVIDENCE.md'),
 'capabilities': ('customer_success_account_management',
                  'customer_success_management_workflow',
                  'customer_success_management_analytics',
                  'configuration_schema',
                  'rule_engine',
                  'parameter_engine',
                  'owned_schema_migrations_models',
                  'appgen_x_outbox_inbox_eventing',
                  'idempotent_handlers',
                  'retry_dead_letter_evidence',
                  'permissions',
                  'seed_data',
                  'workbench',
                  'agentic_document_instruction_intake',
                  'governed_datastore_crud',
                  'customer_success_management_event_sourced_operational_history',
                  'customer_success_management_multi_tenant_policy_isolation',
                  'customer_success_management_schema_evolution_resilience',
                  'customer_success_management_autonomous_anomaly_detection',
                  'customer_success_management_semantic_document_instruction_understanding',
                  'customer_success_management_predictive_risk_scoring',
                  'customer_success_management_counterfactual_scenario_simulation',
                  'customer_success_management_cryptographic_audit_proofs',
                  'customer_success_management_continuous_control_testing',
                  'customer_success_management_carbon_and_sustainability_awareness',
                  'customer_success_management_cross_pbc_event_federation',
                  'customer_success_management_governed_ai_agent_execution'),
 'standard_features': ('customer_success_account_management',
                       'customer_success_management_workflow',
                       'customer_success_management_analytics',
                       'configuration_schema',
                       'rule_engine',
                       'parameter_engine',
                       'owned_schema_migrations_models',
                       'appgen_x_outbox_inbox_eventing',
                       'idempotent_handlers',
                       'retry_dead_letter_evidence',
                       'permissions',
                       'seed_data',
                       'workbench',
                       'agentic_document_instruction_intake',
                       'governed_datastore_crud'),
 'advanced_capabilities': ('customer_success_management_event_sourced_operational_history',
                           'customer_success_management_multi_tenant_policy_isolation',
                           'customer_success_management_schema_evolution_resilience',
                           'customer_success_management_autonomous_anomaly_detection',
                           'customer_success_management_semantic_document_instruction_understanding',
                           'customer_success_management_predictive_risk_scoring',
                           'customer_success_management_counterfactual_scenario_simulation',
                           'customer_success_management_cryptographic_audit_proofs',
                           'customer_success_management_continuous_control_testing',
                           'customer_success_management_carbon_and_sustainability_awareness',
                           'customer_success_management_cross_pbc_event_federation',
                           'customer_success_management_governed_ai_agent_execution'),
 'workflows': ('customer_success_account_workflow', 'customer_success_management_approval_workflow'),
 'analytics': ('customer_success_management_risk_score', 'customer_success_management_workbench_metric')}
