"""Package manifest for the pharma_manufacturing_quality PBC."""

PBC_MANIFEST = {'advanced_capabilities': ('pharma_manufacturing_quality_event_sourced_operational_history',
                           'pharma_manufacturing_quality_multi_tenant_policy_isolation',
                           'pharma_manufacturing_quality_schema_evolution_resilience',
                           'pharma_manufacturing_quality_autonomous_anomaly_detection',
                           'pharma_manufacturing_quality_semantic_document_instruction_understanding',
                           'pharma_manufacturing_quality_predictive_risk_scoring',
                           'pharma_manufacturing_quality_counterfactual_scenario_simulation',
                           'pharma_manufacturing_quality_cryptographic_audit_proofs',
                           'pharma_manufacturing_quality_continuous_control_testing',
                           'pharma_manufacturing_quality_carbon_and_sustainability_awareness',
                           'pharma_manufacturing_quality_cross_pbc_event_federation',
                           'pharma_manufacturing_quality_governed_ai_agent_execution'),
 'analytics': ('pharma_manufacturing_quality_risk_score',
               'pharma_manufacturing_quality_workbench_metric'),
 'apis': ('POST /pharma-batchs',
          'POST /master-batch-records',
          'POST /validation-protocols',
          'POST /deviations',
          'POST /capas',
          'GET /pharma-manufacturing-quality-workbench'),
 'capabilities': ('pharma_batch_management',
                  'pharma_manufacturing_quality_workflow',
                  'pharma_manufacturing_quality_analytics',
                  'configuration_schema',
                  'rule_engine',
                  'parameter_engine',
                  'owned_schema_migrations_models',
                  'appgen_x_outbox_inbox_eventing',
                  'idempotent_handlers',
                  'retry_dead_letter_evidence',
                  'permissions',
                  'seed_data',
                  'workbench',
                  'agentic_document_instruction_intake',
                  'governed_datastore_crud',
                  'ai_agent_task_assistance',
                  'configuration_workbench',
                  'continuous_release_assurance',
                  'pharma_manufacturing_quality_event_sourced_operational_history',
                  'pharma_manufacturing_quality_multi_tenant_policy_isolation',
                  'pharma_manufacturing_quality_schema_evolution_resilience',
                  'pharma_manufacturing_quality_autonomous_anomaly_detection',
                  'pharma_manufacturing_quality_semantic_document_instruction_understanding',
                  'pharma_manufacturing_quality_predictive_risk_scoring',
                  'pharma_manufacturing_quality_counterfactual_scenario_simulation',
                  'pharma_manufacturing_quality_cryptographic_audit_proofs',
                  'pharma_manufacturing_quality_continuous_control_testing',
                  'pharma_manufacturing_quality_carbon_and_sustainability_awareness',
                  'pharma_manufacturing_quality_cross_pbc_event_federation',
                  'pharma_manufacturing_quality_governed_ai_agent_execution'),
 'configuration': ('PHARMA_MANUFACTURING_QUALITY_DATABASE_URL',
                   'PHARMA_MANUFACTURING_QUALITY_EVENT_TOPIC',
                   'PHARMA_MANUFACTURING_QUALITY_RETRY_LIMIT',
                   'PHARMA_MANUFACTURING_QUALITY_DEFAULT_POLICY'),
 'consumes': ('PolicyChanged', 'AuditEventSealed', 'OperationalKpiChanged'),
 'datastore_backend': 'postgresql',
 'description': 'Batch records, validation, deviations, CAPA, release, serialization, and '
                'regulated manufacturing quality',
 'docs': ('SPECIFICATION.md', 'RELEASE_EVIDENCE.md'),
 'emits': ('PharmaManufacturingQualityCreated',
           'PharmaManufacturingQualityUpdated',
           'PharmaManufacturingQualityApproved',
           'PharmaManufacturingQualityExceptionOpened'),
 'label': 'Pharma Manufacturing Quality',
 'mesh': 'opsmfg',
 'migrations': ('migrations/001_initial.sql',),
 'pbc': 'pharma_manufacturing_quality',
 'permissions': ('pharma_manufacturing_quality.read',
                 'pharma_manufacturing_quality.create',
                 'pharma_manufacturing_quality.update',
                 'pharma_manufacturing_quality.approve',
                 'pharma_manufacturing_quality.admin'),
 'seed_data': ('seed_data.py',),
 'standard_features': ('pharma_batch_management',
                       'pharma_manufacturing_quality_workflow',
                       'pharma_manufacturing_quality_analytics',
                       'configuration_schema',
                       'rule_engine',
                       'parameter_engine',
                       'owned_schema_migrations_models',
                       'appgen_x_outbox_inbox_eventing',
                       'idempotent_handlers',
                       'retry_dead_letter_evidence',
                       'permissions',
                       'seed_data',
                       'workbench',
                       'agentic_document_instruction_intake',
                       'governed_datastore_crud',
                       'ai_agent_task_assistance',
                       'configuration_workbench',
                       'continuous_release_assurance'),
 'tables': ('pharma_batch',
            'master_batch_record',
            'validation_protocol',
            'deviation',
            'capa',
            'quality_release',
            'serialization_event',
            'pharma_manufacturing_quality_policy_rule',
            'pharma_manufacturing_quality_runtime_parameter',
            'pharma_manufacturing_quality_schema_extension',
            'pharma_manufacturing_quality_control_assertion',
            'pharma_manufacturing_quality_governed_model'),
 'template': 'asset',
 'tests': ('tests/test_contract.py',),
 'ui_fragments': ('PharmaManufacturingQualityWorkbench',
                  'PharmaManufacturingQualityDetail',
                  'PharmaManufacturingQualityAssistantPanel'),
 'version': '1.0.0',
 'workflows': ('pharma_manufacturing_quality_create_pharma_batch_workflow',
               'pharma_manufacturing_quality_record_master_batch_record_workflow')}
